Translate `library/constants.po`
python/python-docs-zh-tw pull request #119
Opened 2021-10-10 10:10 UTC by jordanSu

2021-11-01 08:43 UTC, josix requested changes
感謝 @jordanSu 協助翻譯，不好意思我 review 了一段時間，主要建議的部分包含幾個譯文的翻譯也許稍微改順序或字詞會比較通順，另外還有一些詞如 `exit code`、`print` 我想需要盡量避免中英混用的情形發生，翻譯成中文應該還不會影響閱讀，特別需要注意的是在 glassory 中需要更新並且統一翻譯。還有什麼問題我們都可以再討論看看🙏

2021-11-01 08:43 UTC, josix commented on library/constants.po
>  "Last-Translator: Adrian Liaw <adrianliaw2000@gmail.com>\n"
Don't forget to update "Last-Translator" to your name

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +"被傳至函式時，相對應參數即會被賦予 ``None``。對於 ``None`` 的賦值是不合法的，"
```suggestion
"型別 ``NoneType`` 的唯一值。``None`` 經常被使用來表達缺少值，例如未"
"傳送預設的引數至函式時，相對應參數即會被賦予 ``None``。對於 ``None`` 的賦值是不合法的，"
```

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +"`__lt__`，:meth:`__add__`，:meth:`__rsub__` ......等）所回傳的特殊值，代表著"
```suggestion
"`__lt__`丶:meth:`__add__`丶:meth:`__rsub__` 等）所回傳的特殊值，代表著"
```

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +"該邏輯沒有針對其他型別的實作。同理也可以被原地二元特殊方法 (in-place binary "
```suggestion
"該運算沒有針對其他型別的實作。同理也可以被原地二元特殊方法 (in-place binary "
```

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +"當 print 此物件時，會印出訊息 \"Type license() to see the full license text"
```suggestion
"當印出物件時，會印出訊息 \"Type license() to see the full license text"
```

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +"試反射該操作到其他型別（或是其他後援 (fallback)，取決於是哪種運算子）。如果所"
```suggestion
"試反映該操作到其他型別（或是其他後援 (fallback)，取決於是哪種運算子）。如果所"
```
I guess we should add `fallback （後援）` to our temporary glossary in README

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +"Python code 中。"
```suggestion
"Python 程式碼中。"
```

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +msgstr "當 print 或是呼叫此物件時，分別會印出版權與致謝的文字。"
```suggestion
msgstr "當打印或是呼叫此物件時，分別會印出版權與致謝的文字。"
```

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +"當 print 此物件時，會印出一個訊息： \"Use quit() or Ctrl-D (i.e. EOF) to exit"
```suggestion
"當打印此物件時，會印出一個訊息： \"Use quit() or Ctrl-D (i.e. EOF) to exit"
```

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +"\" 。當被呼叫時，則會拋出 :exc:`SystemExit` 並帶有指定的 exit code 。"
```suggestion
"\" 。當被呼叫時，則會拋出 :exc:`SystemExit` 並帶有指定的返回碼（exit code） 。"
```

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +"讀成 true，但會提出一個 :exc:`DeprecationWarning`。在未來版本的 Python 將會拋"
```suggestion
"讀成 true，但會發出一個 :exc:`DeprecationWarning`。在未來版本的 Python 將會拋"
```

2021-11-01 08:43 UTC, josix commented on library/constants.po
> +"`SyntaxError`）。因此，它們可以被視為 “真正的”常數。"
```suggestion
"`SyntaxError`）。因此，它們可以被視為”真正的”常數。"
```

2021-11-02 17:02 UTC, jordanSu commented on library/constants.po
> +"當 print 此物件時，會印出訊息 \"Type license() to see the full license text"
個人覺得 "打印" 好像偏中國的用法
這邊可能可以用 "印出"? 不過 Glossary 裡面如何統一定義感覺可以再討論看看

2021-11-02 17:05 UTC, jordanSu commented on library/constants.po
> +"\" 。當被呼叫時，則會拋出 :exc:`SystemExit` 並帶有指定的 exit code 。"
返回碼我覺得 OK，也有看到[有書翻譯](https://books.google.com.tw/books?id=4-E2EAAAQBAJ&pg=PA472&lpg=PA472&dq=%22exit+code%22+%E8%BF%94%E5%9B%9E%E7%A2%BC&source=bl&ots=OwN_sUE31Q&sig=ACfU3U0SvE-RDgcpG9fQBrB20XSrJZ8n-w&hl=zh-TW&sa=X&ved=2ahUKEwijiML-kvrzAhWPN5QKHRhQDOIQ6AF6BAgmEAM)成 退出碼 (exit code)

2021-11-03 06:11 UTC, josix commented on library/constants.po
> +"當 print 此物件時，會印出訊息 \"Type license() to see the full license text"
歐對，感謝提醒，我看坊間書籍多數是使用"印出"，先翻譯成印出沒有問題，後續在 glossary 我們在討論，感謝。

2021-11-14 07:55 UTC, jordanSu commented
> 
> 
> 感謝 @jordanSu 協助翻譯，不好意思我 review 了一段時間，主要建議的部分包含幾個譯文的翻譯也許稍微改順序或字詞會比較通順，另外還有一些詞如 `exit code`、`print` 我想需要盡量避免中英混用的情形發生，翻譯成中文應該還不會影響閱讀，特別需要注意的是在 glassory 中需要更新並且統一翻譯。還有什麼問題我們都可以再討論看看🙏

@josix 感謝幫忙 review。我把全部的建議修改過了，再麻煩幫忙 review 一下，感謝

2021-11-15 09:43 UTC, josix submitted a review, later dismissed
Looks good to me! Thank you @jordanSu.

2021-11-15 09:46 UTC, josix submitted a review, later dismissed
Looks good to me! Thank you @jordanSu.

2021-11-15 09:47 UTC, josix approved these changes

2021-11-15 10:02 UTC, josix requested changes
Hello @jordanSu，抱歉我剛剛才發現我們上一個 review 是錯誤的 base branch 3.9 目前我們應該要 merge 到 3.10 當中，我改了 PR 的設定，不過有出現一些還需要補的譯文，導致 CI 沒有通過，再麻煩你處理一下，感謝🙏

2021-11-15 10:02 UTC, josix commented on library/constants.po
> +"並且會拋出 :exc:`SyntaxError`。"
Sorry @jordanSu, I found there is a sentence that has not been translated yet since I changed the base branch from `3.9` to `3.10`. Please help me update this, thanks!

2021-11-15 10:02 UTC, josix commented on library/constants.po
> +"被作為 boolean（布林）來解讀。"
Here is also the same problem mentioned above. The new sentence ` ``NotImplemented`` is the sole instance of "
"the :data:`types.NotImplementedType` type."` has not translated yet.

2021-11-19 15:24 UTC, jordanSu commented
> Hello @jordanSu，抱歉我剛剛才發現我們上一個 review 是錯誤的 base branch 3.9 目前我們應該要 merge 到 3.10 當中，我改了 PR 的設定，不過有出現一些還需要補的譯文，導致 CI 沒有通過，再麻煩你處理一下，感謝🙏

@josix 沒問題 我再來修一下

2021-11-19 16:56 UTC, josix approved these changes
LGTM, thank you @jordanSu for the hard work!

2021-11-19 16:56 UTC, merged