Traslate `library/array.po`
python/python-docs-zh-tw pull request #140
Opened 2021-11-13 15:15 UTC by tomatoprinx

resolves python/python-docs-zh-tw#139

2021-11-13 17:39 UTC, mattwang44 requested changes
Thanks for the hard work!
Please read through the README for how to correctly use spaces and punctuations. I'll keep reviewing the translated content after the commit for modifying punctuations is pushed.

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"物件型別。在建立陣列時可以使用一個字元的  :dfn:`type code` 來指定儲存的資料型"
```suggestion
"物件型別。在建立陣列時可以使用一個字元的 :dfn:`type code` 來指定儲存的資料型"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +msgstr "根據平台的不同，他有可能是 16 位元 或者 32 位元。"
```suggestion
msgstr "根據平台的不同，他有可能是 16 位元或者 32 位元。"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"type。 這個異動並沒有影響到他的作用，因爲自從 Python 3.3 開始 ``Py_UNICODE`` "
```suggestion
"type。這個異動並沒有影響到他的作用，因爲自從 Python 3.3 開始 ``Py_UNICODE`` "
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"化， *initializer* 必須是一個 list（串列）、 :term:`bytes-like object` 或包含"
You only need to denote the translated content once in an article.
```suggestion
"化， *initializer* 必須是一個 list、 :term:`bytes-like object` 或包含"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"化， *initializer* 必須是一個 list（串列）、 :term:`bytes-like object` 或包含"
```suggestion
"化， *initializer* 必須是一個 list（串列）、\ :term:`bytes-like object` 或包含"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"如果指定一個 list（串列）或 string ，新的陣列初始化時會傳入 :meth:"
```suggestion
"如果指定一個 list 或 string ，新的陣列初始化時會傳入 :meth:"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"如果指定一個 list（串列）或 string ，新的陣列初始化時會傳入 :meth:"
```suggestion
"如果指定一個 list（串列）或 string，新的陣列初始化時會傳入 :meth:"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"`fromlist` 、 :meth:`frombytes` 或 :meth:`fromunicode` 方法（參照下方）將元素"
```suggestion
"`fromlist`\ 、\ :meth:`frombytes` 或 :meth:`fromunicode` 方法（參照下方）將元素"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"引發 :ref:`審核事件(auditing event) <auditing>` ``array.__new__`` 並帶入 "
```suggestion
"引發\ :ref:`審核事件 (auditing event) <auditing>` ``array.__new__`` 並帶入引數 "
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"``typecode``, ``initializer``."
Replace with Chinese punctuation.

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"陣列支援常見的序列操作，包含索引（indexing）、切片（slicing）、串接"
Also update the following line
```suggestion
"陣列支援常見的序列操作，包含索引 (indexing)、切片 (slicing)、串接"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"必須具備相同的 type code ，其他型別的數值將導致  :exc:`TypeError` 。陣列同時"
```suggestion
"必須具備相同的 type code，其他型別的數值將導致 :exc:`TypeError`\ 。陣列同時"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"完全相同的 type code ，如果不同會導致 :exc:`TypeError` 。如果 *iterable* 不是"
```suggestion
"完全相同的 type code，如果不同會導致 :exc:`TypeError`。如果 *iterable* 不是"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"素加入陣列的最尾端。如果只有少於 *n* 個有效的元素會導致 :exc:`EOFError` ，但"
```suggestion
"素加入陣列的最尾端。如果只有少於 *n* 個有效的元素會導致 :exc:`EOFError`，但"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"從 list（串列）中新增元素。這等價於 ``for x in list: a.append(x)`` ，除了有型"
```suggestion
"從 list 中新增元素。這等價於 ``for x in list: a.append(x)``，除了有型"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"將導致 :exc:`ValueError` 。"
```suggestion
"將導致 :exc:`ValueError`。"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"數 *start* 及 *stop* 則可以被用來在指定的陣列空間中搜尋 *x* 。如果 *x* 不存在"
```suggestion
"數 *start* 及 *stop* 則可以被用來在指定的陣列空間中搜尋 *x*。如果 *x* 不存在"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +msgstr "新增選擇性的參數 *start* 及 *stop* 。"
```suggestion
msgstr "新增選擇性的參數 *start* 及 *stop*。"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +msgstr "不更改元素，將陣列轉為一般的 list（串列）。"
```suggestion
msgstr "不更改元素，將陣列轉為一般的 list。"
```

2021-11-13 17:39 UTC, mattwang44 commented on library/array.po
> +"initializer)`` 。若為空陣列則參數 *initializer* 被省略，若  *typecode* 是 "
```suggestion
"initializer)`` 。若為空陣列則參數 *initializer* 被省略，若 *typecode* 是 "
```

2021-11-20 02:36 UTC, tomatoprinx commented
Hi @mattwang44 
Thanks for your previous review and advice for space and punctuation placement. I had pushed a new commit 3f6f381 to correct it.

2021-11-20 06:46 UTC, mattwang44 requested changes

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"別。下面是 type codes 的定義。"
```suggestion
"別。下面是 type codes 的定義："
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"別。下面是 type codes 的定義。"
```suggestion
"別。以下為有被定義的 type codes。"
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"引發 :ref:`審核事件 (auditing event) <auditing>` ``array.__new__`` 並帶入引"
```suggestion
"引發\\ :ref:`審核事件 (auditing event) <auditing>` ``array.__new__`` 並帶入引"
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"數 ``typecode``， ``initializer``。"
```suggestion
"數 ``typecode``、``initializer``。"
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"化，\\ *initializer* 必須是一個 list、\\ :term:`bytes-like object` 或包含適當"
consider adding the translated content for the term `bytes-like objects`（`類位元組串物件`, as mentioned in the glossary page）.

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"區記憶體長度。緩衝區的長度單位是 bytes，並可以用 ``array.buffer_info()[1] * "
Please find out the first occurrence of the term `bytes` in this article and add the translated content with it.
If `bytes（位元組）` is used for the first occurrence, use `bytes` in the rest of the article; if `位元組 (bytes)` is used for the first occurrence, use `位元組` in the rest of the article.

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"新的程式碼中避免。關於緩衝區介面的文件在 :ref:`bufferobjects`\\ 。"
The reference of `bufferobjects` will be translated.

```suggestion
"新的程式碼中避免。關於緩衝區介面的文件在\\ :ref:`bufferobjects`\\ 。"
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"完全相同的 type code ，如果不同會導致 :exc:`TypeError`\\ 。如果 *iterable* 不"
```suggestion
"完全相同的 type code，如果不同會導致 :exc:`TypeError`\\ 。如果 *iterable* 不"
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +msgstr "為了更明確，之前的 :meth:`fromstring` 被更名為 :meth:`frombytes`\\ 。"
Please also fix the translated content of `library/array.rst:219`.

```suggestion
msgstr "將 :meth:`fromstring` 更名為 :meth:`frombytes`，使其更加清晰易懂。"
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"生時，陣列會保持原狀不會被更改。"
```suggestion
"生時，陣列會保持原狀。"
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"導致 :exc:`ValueError` 錯誤。使用 ``array.frombytes(unicodestring."
```suggestion
"導致 :exc:`ValueError`\\ 。使用 ``array.frombytes(unicodestring."
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"回傳 *i* 的最小數值，使得 *i* 成為陣列之中第一次出現 *x* 的索引。選擇性的參"
`argument` should be translated as `引數`. Please also fix all other source strings that have this term.
```suggestion
"回傳 *i* 的最小數值，使得 *i* 成為陣列之中第一次出現 *x* 的索引。選擇性的引"
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
>  msgid ""
please fix the space of this sentence.

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
>  msgid "Reverse the order of the items in the array."
fix its translation

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +msgstr "將所有元素（以 machine code 的形式）寫入 :term:`file object` *f*\\ 。"
why `machine value` is translated as `machine code`?

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"將陣列轉為一個字串。陣列的型態必須為 ``u`` 。其他型別的陣列會導致 :exc:"
```suggestion
"將陣列轉為一個字串。陣列的型態必須為 ``u``，其他型別的陣列會導致 :exc:"
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"`ValueError` 錯誤。使用 ``array.tobytes().decode(enc)`` 將其他型別的陣列轉為"
```suggestion
"`ValueError`\\ 。使用 ``array.tobytes().decode(enc)`` 將其他型別的陣列轉為"
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"initializer)`` 。若為空陣列則參數 *initializer* 被省略，若 *typecode* 是 "
```suggestion
"initializer)``。若為空陣列則 *initializer* 會被省略，若 *typecode* 是 "
```

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"``’u’`` 將被表示為字串，其他情況則被表示為數字 list。只要 :class:`~array."
the term `數字 list` is too vague.

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
> +"`eval` 便能確保其字串被轉換回一個擁有相同型別及數值的陣列。範例：\n"
`使用 eval 便能確保其字串被轉換回一個擁有相同型別及數值的陣列。` -> `便能確保該字串能夠透過 eval 來被轉換回一個擁有相同型別及數值的陣列。`

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
>  #~ msgid ""
Please help delete these outdated translations.

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
>  msgid "Module :mod:`struct`"
Should be translated as ``:mod:`struct` 模組"``. Please also fix `library/array.rst:261`.

2021-11-20 06:46 UTC, mattwang44 commented on library/array.po
>  msgid "The following data items and methods are also supported:"
Replace the period in the translated sentence with `：`.

2021-11-20 06:48 UTC, mattwang44 commented on library/array.po
>  "從 :term:`file object` *f* 讀取 *n* 個 machine value 類型的元素，接著將這些元"
consider explaining the term `machine value`.

2021-11-21 06:15 UTC, tomatoprinx commented on library/array.po
>  "從 :term:`file object` *f* 讀取 *n* 個 machine value 類型的元素，接著將這些元"
An existing translation in [tutorial/floatingpoint.po](https://github.com/python/python-docs-zh-tw/blob/3.10/tutorial/floatingpoint.po) use the word `機器數值`. I'll refer to that.

2021-11-21 14:41 UTC, tomatoprinx commented
@mattwang44 I've create commits [b1d476d](https://github.com/python/python-docs-zh-tw/pull/140/commits/b1d476d80849e5d2487766997fa2c4cfa3eebf59) and [360dcf8](https://github.com/python/python-docs-zh-tw/pull/140/commits/360dcf8cdeda2a7de996f035b950fb395a18dbb3) to fix the previous review.

2021-12-08 16:29 UTC, mattwang44 commented on library/array.po
> +"引發\\ :ref:`審核事件 (auditing event) <auditing>` ``array.__new__`` 並帶入引"
翻譯 audit event 主頁的 #165 將其譯作「稽核事件」，這邊希望也統一用詞。

```suggestion
"引發\\ :ref:`稽核事件 (auditing event) <auditing>` ``array.__new__`` 並帶入引"
```

2021-12-08 16:35 UTC, mattwang44 approved these changes
Only a few minor issues remained unsolved. A new commit is added before emerging this PR. Thanks for the efforts!

2021-12-08 17:00 UTC, merged