Translate `library/collections.po`
python/python-docs-zh-tw pull request #141
Opened 2021-11-15 17:47 UTC by mattwang44

fix #111

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr "用來建立其欄位擁有名字的 tuple 子類別的產生函數"
用來建立具名欄位的 tuple 子類別的產生函數
參見第1043行

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr "dict 的子類別，當值不存在 dict 中時會呼叫一個提供預設值的產生函式"
建議function的稱呼為「函數」或「函式」應統一

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr "dict 物件的包裝器 (wrapper)，簡化了 dict 的子類別化"
1. 微軟對wrapper的翻譯為「包裝函式」，個人無偏好何種稱呼，提供您參考
2. 「簡化了⋯⋯的子類別化」似乎有點拗口，也許可將「子類別化」改為「子類別過程」

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr "這一章節提供了多種操作 ChainMap 的案例。"
此章節提供了多種操作 ChainMap 的案例。

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr "這個方法沒有在 :class:`Counter` 物件中被實作出來。"
此方法沒有（被）實作於 :class:`Counter` 物件中。

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr "增加了富比較運算。"
感覺硬著頭皮翻，好像也蠻奇怪。建議：豐富比較運算

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr "加和減一元運算子分別是加上空的 Counter 和自空 Counter 減去的簡寫。"
加減法的一元運算子分別是加上空的 Counter、從空 Counter 減去的簡寫。

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +"出。型別上並無限制，但其值之型別必須支援加、減和比較操作。"
出。並無型別限制，但其值的型別須支援加、減及比較運算。

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr "建立一個 deque 的淺複製。"
建立一個 deque 的淺複製（shallow copy）

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr "將 iterable 參數加入 deque 的右側。"
第 216 行處的 argument 譯作「引數」，是否有必要統一其稱呼？

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +"將 iterable 參數加入 deque 的左側。要注意的是，加入後的元素順序和 iterable 參"
同第700行

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +"exc:`IndexError` 例外將被引發。"
如果此插入操作導致 deque 超過其長度上限 *maxlen*，會引發 exe:`IndexError`例外。

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +"`IndexError`\\ 。"
移除並回傳 deque 的最右側元素。若本來就沒有任何元素，則會引發 :exe:`IndexError`例外。

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +"`IndexError`\\ 。"
同第737、738行

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr ":class:`defaultdict` 物件支援以下實例變量："
variable為變數

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +"力。"
1. 「自我文件性」一詞不易理解，且將其省略不會影響句意。
2. 1053 行tuple後的「添加」，可改為「賦予其」

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +"回傳一個新的 named tuple 實例，並將指定欄位替換為新的值：\n"
本檔案前段已存在named tuple「具名元組」的稱呼

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr "透過直接賦值給 ``__doc__``，可以自定義說明文件字串："
建議customize翻譯為「自訂」、「客製化」

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +"關於為 named tuple 新增型別提示的方法，請參閱 :class:`typing.NamedTuple`，它"
同第 1214 行

2021-11-15 19:31 UTC, toto6038 commented on library/collections.po
> +msgstr ":class:`OrderedDict` 之相等性檢測會檢查順序是否相同。"
建議將 equality operation 譯作「相等性運算」

2021-11-15 21:56 UTC, mattwang44 commented on library/collections.po
> +msgstr "增加了富比較運算。"
我覺得我直接放原文好了，rich comparison 是 Python 專有名詞，找不除了 `富比較` 以外的譯文，但並不盛行。

2021-11-15 21:57 UTC, mattwang44 commented on library/collections.po
> +msgstr "dict 物件的包裝器 (wrapper)，簡化了 dict 的子類別化"
1. 現有譯文 (tutorial/classes.po) 翻作 `包裝器`，我就先沿用了。
2. updated

2021-11-15 22:04 UTC, mattwang44 commented on library/collections.po
> +"回傳一個新的 named tuple 實例，並將指定欄位替換為新的值：\n"
已於 `collections.rst:834` 附上譯文，後續皆放原文、不再翻譯

2021-11-15 22:08 UTC, mattwang44 commented on library/collections.po
> +"力。"
1. readability 和 self-documenting 意義不同，我不認為省略後會保持原意。
2. updated

2021-11-15 22:10 UTC, mattwang44 commented on library/collections.po
> +msgstr "dict 的子類別，當值不存在 dict 中時會呼叫一個提供預設值的產生函式"
皆統一為「函式」

2021-11-15 22:20 UTC, mattwang44 commented on library/collections.po
> +msgstr "將 iterable 參數加入 deque 的右側。"
此為翻譯錯誤，`argument` 應譯作 `引數`，而 `parameter` 才是 `參數`。

2021-11-15 22:23 UTC, mattwang44 commented
感謝 @toto6038！我已經根據 review comment 新增 commit 373ef73。

2022-01-03 09:46 UTC, josix requested changes
抱歉我晚 review 了，先 review 了 ChainMap 的部分，再麻煩 @mattwang44 檢查，我後續會再補上其他部分，感謝！

2022-01-03 09:46 UTC, josix commented on library/collections.po
> +msgstr "用來建立具名欄位的 tuple 子類別的產生函式"
這邊會不會需要保留 factory function 的意思？”產生函式” 感覺可能沒有包含 design pattern 中 factory method 的意涵？

2022-01-03 09:46 UTC, josix commented on library/collections.po
> +msgstr "dict 物件的包裝器 (wrapper)，簡化了 dict 的子類別過程"
這邊 subclassing 可能可以翻成動作 “子類別化”
```suggestion
msgstr "dict 物件的包裝器 (wrapper)，簡化了 dict 的子類別化過程"
```

2022-01-03 09:46 UTC, josix commented on library/collections.po
> +msgstr "list 物件的包裝器，簡化了 list 的子類別過程"
Same as above.
```suggestion
msgstr "list 物件的包裝器，簡化了 list 的子類別化過程"
```

2022-01-03 09:46 UTC, josix commented on library/collections.po
> +msgstr "字串物件的包裝器，簡化了字串的子類別過程"
Same as above.
```suggestion
msgstr "字串物件的包裝器，簡化了字串的子類別化過程"
```

2022-01-03 09:46 UTC, josix commented on library/collections.po
> +"的視野。如果沒有指定 *maps*，預設會提供一個空字典讓每個新鏈結都至少有一個映"
View 會不會翻成視圖會比較好？看起來和 MVC 的 view 雷同負責資料顯示的職責

2022-01-03 09:46 UTC, josix commented on library/collections.po
> +":class:`ChainMap` 透過指標將底層映射合併，所以當一個底層映射被更新，這些改變"
我想 reference 應該要翻成參照會比較好一些，python 中應該沒有 potienr？
```suggestion
":class:`ChainMap` 透過參照將底層映射合併，所以當一個底層映射被更新，這些改變"
```

2022-01-04 05:17 UTC, mattwang44 commented on library/collections.po
> +msgstr "用來建立具名欄位的 tuple 子類別的產生函式"
發現 glossary 裡面有翻譯成「工廠函式」，這邊就也成一樣。

2022-01-04 05:17 UTC, mattwang44 commented on library/collections.po
> +"的視野。如果沒有指定 *maps*，預設會提供一個空字典讓每個新鏈結都至少有一個映"
modified

2022-01-04 18:06 UTC, josix requested changes
Finish reviewing the `Counter` part.

2022-01-04 18:06 UTC, josix commented on library/collections.po
> +"作為 :class:`dict` 的子類別，\\ :class:`Counter` 繼承了記憶插入位置的功能。"
```suggestion
"作為 :class:`dict` 的子類別，\\ :class:`Counter` 繼承了記憶插入順序的功能。"
```

2022-01-04 18:06 UTC, josix commented on library/collections.po
> +"回傳每個元素都重複出現計算次數的 iterator 物件，其中元素的回傳順序是依照各元"
iterator 不確定有沒有已經翻譯成 "迭代器"？可能要統一一下

2022-01-04 18:23 UTC, toto6038 commented on library/collections.po
> +"回傳每個元素都重複出現計算次數的 iterator 物件，其中元素的回傳順序是依照各元"
依[國教院](https://terms.naer.edu.tw/detail/17008148/)資料，iterator 中文稱呼為「疊代器」，「『迭』代器」為誤用。
在黃敬群教授前幾日的[講座影片](https://youtu.be/pTcRq__iKzI?t=8764)中，聊天室亦有稍微討論，連結已標註時間碼。

2022-01-05 04:35 UTC, mattwang44 commented on library/collections.po
> +"作為 :class:`dict` 的子類別，\\ :class:`Counter` 繼承了記憶插入位置的功能。"
updated

2022-01-05 04:38 UTC, mattwang44 commented on library/collections.po
> +"回傳每個元素都重複出現計算次數的 iterator 物件，其中元素的回傳順序是依照各元"
已補上原文

2022-01-05 17:37 UTC, josix commented on library/collections.po
> +"回傳每個元素都重複出現計算次數的 iterator 物件，其中元素的回傳順序是依照各元"
感謝 @toto6038 補充!

2022-01-05 19:10 UTC, toto6038 commented on library/collections.po
> +msgstr "一個類似 dict 的類別，用來為多個對映 (mapping) 建立單一的視圖 (view)"
view 是否應譯作「視野」較佳？
參考資料：[國家教育研究院](http://terms.naer.edu.tw/detail/1288562/)

2022-01-05 19:10 UTC, toto6038 commented on library/collections.po
> +"搜索 (lookup) 陸續查詢底層對映，直到鍵被找到，然而讀取、更新和刪除就只會對第"
lookup 可譯為「檢索」

2022-01-05 19:10 UTC, toto6038 commented on library/collections.po
> +"的推廣。deque 支援執行緒安全 (thread-safe)，且能夠高記憶效率地在頭和尾加入和"
「且能夠高記憶效率地在頭和尾加入...」->「且能夠節省記憶體地在頭尾加入...」

2022-01-06 07:21 UTC, mattwang44 commented on library/collections.po
> +msgstr "一個類似 dict 的類別，用來為多個對映 (mapping) 建立單一的視圖 (view)"
我原先的確是查國教院所以譯作「視野」，但 @josix 之前的 [review comment](https://github.com/python/python-docs-zh-tw/pull/141#discussion_r777358808) 提到這邊比較像是指 MVC 中 view 的概念，此義普遍會被翻作「視圖」（例如[維基百科](https://zh.wikipedia.org/wiki/MVC)，但還找不到比較有公信力的機構為這個詞作翻譯），而國教院對該詞的解釋（`在關聯式資料庫中描述使用者之子綱目的用語。`）感覺並不相符，所以才改成「視圖」。

2022-01-06 07:31 UTC, mattwang44 commented on library/collections.po
> +msgstr "一個類似 dict 的類別，用來為多個對映 (mapping) 建立單一的視圖 (view)"
也許以下兩處的「檢視」也應該改成「視圖」？

https://github.com/python/python-docs-zh-tw/blob/2261735da57efc6c575995cbc952bb42d975bb22/library/collections.po#L1433-L1439
https://github.com/python/python-docs-zh-tw/blob/2261735da57efc6c575995cbc952bb42d975bb22/library/stdtypes.po#L4834-L4836

2022-01-08 08:53 UTC, josix requested changes
Finish reviewing `deque` part.

2022-01-08 08:53 UTC, josix commented on library/collections.po
> +msgstr "一個類似 dict 的類別，用來為多個對映 (mapping) 建立單一的視圖 (view)"
嗯嗯對，我覺得可以改成"視圖"

2022-01-08 08:53 UTC, josix commented on library/collections.po
> +"的推廣。deque 支援執行緒安全 (thread-safe)，且能夠高記憶效率地在頭和尾加入和"
```suggestion
"的一般化。deque 支援執行緒安全 (thread-safe)，且能夠有效率地節省記憶體在頭和尾加入和"
```

2022-01-08 08:53 UTC, josix commented on library/collections.po
> +"除了以上使用方式，deque 亦支援了疊代、pickle（封存）、``len(d)``、"
pickle 這個命名源自 Modula-3 這個語言取自醃製保留風味的意思，我想 pickle 可能可以不用翻譯。[reference here](https://stackoverflow.com/questions/27324986/pickles-why-are-they-called-that)

2022-01-09 08:56 UTC, mattwang44 commented on library/collections.po
> +"除了以上使用方式，deque 亦支援了疊代、pickle（封存）、``len(d)``、"
已更正，也在 README 裡面加註 pickle 可以保留原文就好

2022-01-09 08:56 UTC, mattwang44 commented on library/collections.po
> +"的推廣。deque 支援執行緒安全 (thread-safe)，且能夠高記憶效率地在頭和尾加入和"
modified

2022-01-09 08:56 UTC, mattwang44 commented on library/collections.po
> +"搜索 (lookup) 陸續查詢底層對映，直到鍵被找到，然而讀取、更新和刪除就只會對第"
modified

2022-01-09 08:57 UTC, mattwang44 commented on library/collections.po
> +msgstr "一個類似 dict 的類別，用來為多個對映 (mapping) 建立單一的視圖 (view)"
已更正囉～

2022-01-11 17:37 UTC, josix requested changes
Finish reviewing defaultdict

2022-01-11 17:37 UTC, josix commented on library/collections.po
> +"如果 :attr:`default_factory` 不為 ``None``，它會被呼叫（不帶引數）來為給定的 "
```suggestion
"如果 :attr:`default_factory` 不為 ``None``，它會不帶引數地被呼叫來為給定的 "
```

2022-01-11 17:37 UTC, josix commented on library/collections.po
> +"時，就如普通字典般操作（回傳該鍵所指到的 list），\\ :meth:`list.append` 也會"
nit. 可能改成對應會符合 mapping 意涵
```suggestion
"時，就如普通字典般操作（回傳該鍵所對應到的 list），\\ :meth:`list.append` 也會"
```

2022-01-12 09:31 UTC, josix requested changes
Finish reviewing `namedtuple`

2022-01-12 09:31 UTC, josix commented on library/collections.po
> +"Named tuple（具名元組）賦予 tuple 中各個位置意義，使程式碼更有可讀性與自我文"
想確認下 tuple 目前有統一翻譯成元組嗎？還是保留 tuple 原文即可，假如有統一的話記得再更新 glossary，感謝。

2022-01-12 09:31 UTC, josix commented on library/collections.po
> +"件性。它們可以用於任何普通 tuple，賦予其透過名稱（而非位置索引）來存取欄位的"
```suggestion
"件性。它們可以用於任何普通 tuple 可使用的場合，賦予其透過名稱（而非位置索引）來存取欄位的"
```

2022-01-12 09:31 UTC, josix commented on library/collections.po
> +"代的 (iterable)。子類別實例同樣有文件字串（有類別名 typename 和欄位名 "
```suggestion
"代的 (iterable)。子類別實例同樣有文件字串（docstring）（有類別名 typename 和欄位名 "
```

2022-01-12 09:31 UTC, josix commented on library/collections.po
> +msgstr "從已存在的序列或可疊代物件建立一個新實例。"
```suggestion
msgstr "從已存在的序列或可疊代物件建立一個新實例的類別方法。"
```

2022-01-12 09:37 UTC, josix commented on library/collections.po
> +"力。"
我想也可以在自我文件性後加註（self-documenting）方便理解

2022-01-12 16:39 UTC, mattwang44 commented on library/collections.po
> +"Named tuple（具名元組）賦予 tuple 中各個位置意義，使程式碼更有可讀性與自我文"
readme 有提到建議保留原文，所以在首次出現的地方（intro 部份）有附上譯文，其他地方就直接放原文

2022-01-13 12:54 UTC, josix commented on library/collections.po
> +"Named tuple（具名元組）賦予 tuple 中各個位置意義，使程式碼更有可讀性與自我文"
瞭解，感謝說明🙏

2022-01-13 13:49 UTC, josix requested changes
Finish reviewing rest parts.

2022-01-13 13:49 UTC, josix commented on library/collections.po
> +":class:`OrderedDict` 類別的 :meth:`popitem` 方法有不同的 signature，它接受傳"
不確定signature是不是需要翻[wiki 是翻成函數簽名](https://zh.wikipedia.org/wiki/%E5%87%BD%E6%95%B0%E5%8E%9F%E5%9E%8B)

2022-01-13 13:49 UTC, josix commented on library/collections.po
> +"Ordered dictionary 的 :meth:`popitem` 方法移除並回傳一個 (key, value) 鍵值"
```suggestion
"Ordered dictionary 的 :meth:`popitem` 方法移除並回傳一個鍵值（key, value）"
```

2022-01-13 13:49 UTC, josix commented on library/collections.po
> +":class:`UserDict` 類別 dict 物件的包裝器。因為已經可以直接自 :class:`dict` 建"
```suggestion
":class:`UserDict` 類別是作為 dict 物件的包裝器。因為已經可以直接自 :class:`dict` 建"
```

2022-01-13 13:49 UTC, josix commented on library/collections.po
> +"始化為其值；要注意指到 *initialdata* 的指標不會被保留，使其可被用於其他目的。"
```suggestion
"始化為其值；要注意指到 *initialdata* 的參照不會被保留，使其可被用於其他目的。"
```

2022-01-13 13:49 UTC, josix commented on library/collections.po
> +"如果希望一個自此獲得的子類別能夠別按照上述條件，那所有該類別支援的特殊方法則"
```suggestion
"如果希望一個自此獲得的子類別不遵從上述要求，那所有該類別支援的特殊方法則"
```

2022-01-13 13:49 UTC, josix commented on library/collections.po
> +":class:`UserString` 類別是字串物件的包裝器 因為已經可以從 :class:`str` 直接建"
```suggestion
":class:`UserString` 類別是字串物件的包裝器，因為已經可以從 :class:`str` 直接建"
```

2022-01-14 05:32 UTC, mattwang44 commented on library/collections.po
> +":class:`OrderedDict` 類別的 :meth:`popitem` 方法有不同的 signature，它接受傳"
modified
有填 glossary 擴充表單，之後可以來討論一下這個翻譯

2022-01-14 07:16 UTC, josix approved these changes
Let's merge it

2022-01-14 07:18 UTC, merged