Fill missing translations in tutorial/interpreter.po
python/python-docs-zh-tw pull request #16
Opened 2018-07-12 12:43 UTC by Wayne1316

翻譯以下文件

直譯器unix安裝路徑
直譯器windows安裝路徑
直譯器模式說明
首行編碼
首行編碼範例

尚有兩個未翻譯

2018-07-17 20:12 UTC, adrianliaw requested changes
Hi @Wayne1316, thanks so much for the contribution! It's a good work if you're new to open-source project contributions ✨ However, there are a lot that I think should be changed at the moment, please feel free to leave a comment if you don't agree with my thoughts.  If you need any help, feel free to ping me on Telegram also.

One thing I also want to mention is that, it's always better to name a branch or pull-request meaningfully, I've changed the PR title so it better describes what you're doing.

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +"Python 直譯器通常安裝在： file: '/usr/local/bin/python3.7 ' 的作業系統上，它"
<code>:file:\`/usr/local/bin/python3.7\`</code> is an rST "interpreted text" syntax [1], which should remain the same in the translation.  Please use the ASCII colon and backticks (instead of quotes) for these interpreted text syntax, and don't forget to remove the redundant space between `:file:` and <code>\`/usr/local/bin/python3.7\`</code>.

Also, I'm very sorry to say this but I think the translation does not deliver the meaning well, in terms of both semantics and grammar.  Please refine the translation so that the translation's meaning matches the source documentation.

[1] http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#interpreted-text

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +"中通過輸入命令可以啟動它:"
Note that the halfwidth colon should be translated into fullwidth colon in the translation, except for the ones that represents rST syntax such as "double-colon" (`::`) or "interpreted text" described previously.

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +"在 Windows 作業系統上，Python 通常安裝在：file:'C:\\\\Python36 中, 您可以在安"
As mentioned in the previous comment, the rST syntax should remain the same in the translations.

Also, the comma should be fullwidth.

s/安裝/被安裝/ (passive voice grammar
s/您可以/不過您也可以/ (notice the word "though" in the source

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +"裝程式時更改此路徑。 將此目錄添加到您的執行路徑中，可以在 DOS 視窗中的命令提"
The word "installer" can be and should be translated into "安裝程式" on its own, so it would be awkward to add "時" right after "安裝程式" since "安裝程式" is a noun in a grammatical sense.

s/將此目錄...../欲將此目錄/ (notice the word "to" in the source

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +"示字元下輸入以下命令："
s/命令/指令/


The colon here, please follow the last point in our translation guideline about rST syntax [1] since this is a double-colon which means differently from single-colon in rST.

[1] https://github.com/python/python-docs-zh-tw#rst

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +"當從 tty 讀取命令時, 直譯器提示目前為 * 交互模式 *。 在此模式下，它會提示使"
s/命令/指令/
s/交互/互動/

Please use fullwidth comma here.  Also, the space in front of the italic markup should be replaced with a "zero-width space" (see the second point of the rST translation guidelines [1]), in order to hide the redundant space that shouldn't be present in Chinese.  Third, the redundant space after the first full stop should be deleted.

The main problem in the first sentence is that the subject is missing, which may make the sentence "sounds missing something".  A better translation would be `當指令是被從 tty 讀取的時候，直譯器的模式就叫作\ *互動模式*\ 。`

[1] https://github.com/python/python-docs-zh-tw#rst

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +"用 * 主提示符號 * 輸入下一個命令，主提示通常使用三個大於符號 （``>>>``）表"
s/提示符號/提示字元/

There should be zero-width space before and after the double-backticks in order to make the markup work.

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +"示；對於多行的程式， 它會提示使用 * 次提示符 *, 預設情況下為三個點 （``..."
Same comment as the previous ones.

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +"``）。在輸出第一個提示符號之前，直譯器會輸出一則歡迎訊息，說明目前使用的版本"
s/輸出/印出/ ("輸出" is mainly the meaning of "output" or "export"

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +"若要聲明非預設編碼, 應將特殊註解添加在為檔案的 * 首 * 行。 結構如下所示::"
The comma should be replaced with the full-width comma.  The second sentence has two verb occurrences, "添加" and "為", which wouldn't make a lot of sense in grammar.

The italic text markup should follow the previous comments.  The redundant space after the full stop should be removed.

s/結構/語法/

The final double-colon in the line should be translated with the last rule of the rST guidelines [1]

[1] https://github.com/python/python-docs-zh-tw#rst

2018-07-17 20:12 UTC, adrianliaw commented on tutorial/interpreter.po
> +msgstr "例如，要聲明使用Windows-1252的編碼，您的原始碼首行應為::"
As described in the third point in the translation guidelines [1], "Windows-1252" should have a space both before and after the word.

The colon, again, should follow the rST guidelines.

[1] https://github.com/python/python-docs-zh-tw#id7

2021-05-24 03:17 UTC, StevenHsuYL commented
tutorial/interpreter.po was finished at #67 
This PR could be closed.
Thanks for your work!

2021-09-27 06:58 UTC, closed without merging