Translate `c-api/{abstract,bool,coro,descriptor,utilities}.po`
python/python-docs-zh-tw pull request #169
Opened 2021-12-09 13:27 UTC by mattwang44

fix #168

2021-12-15 03:00 UTC, mattwang44 commented
@allen91wu, would you be interested in reviewing this PR?

2021-12-15 04:32 UTC, allen91wu commented
Okay, I would review this PR~

2021-12-15 05:13 UTC, mattwang44 commented
@allen91wu I just sent you an [invitation](https://github.com/python/python-docs-zh-tw/invitations) for adding you to the team. I will assign you as the reviewer after you press the acceptance button 👍🏽.

2021-12-16 04:28 UTC, allen91wu requested changes
@mattwang44 I have left some comments. If you have any questions please let me know. 🙏

2021-12-16 04:28 UTC, allen91wu commented on faq/installed.po
> +"許多相容於 Unix 系統，例如 maxOS 和一些 Linux 發行版本預設安裝 Python；它被包"
- typo: `maxOS` -> `macOS`
```suggestion
"許多相容於 Unix 系統，例如 macOS 和一些 Linux 發行版本預設安裝 Python；它被包"
```

2021-12-16 04:28 UTC, allen91wu commented on c-api/utilities.po
> +"本章中的函式可用來執行各種工具任務，包括幫助 C 程式碼提升跨平臺可移植性、在 "
- `portable` 應被譯為 `可攜性`
 - Ref: https://terms.naer.edu.tw/detail/1284282/?index=3
```suggestion
"本章中的函式可用來執行各種工具任務，包括幫助 C 程式碼提升跨平臺可攜性 (portable)、在 "
```

2021-12-16 04:28 UTC, allen91wu commented on c-api/descriptor.po
> +"檢測。"
```suggestion
"檢查。"
```

2021-12-16 04:28 UTC, allen91wu commented on faq/installed.po
> +"常執行。你應該使用應用程式解除安裝功能而非自行刪除 Python。"
```suggestion
"常執行。你應該使用應用程式解除安裝功能而非直接刪除 Python。"
```

2021-12-16 04:28 UTC, allen91wu commented on faq/installed.po
> +"Compaq 出廠的機器都預設安裝 Python，顯然的 HP 與 Compaq 部份管理工具程式是透"
```suggestion
"Compaq 出廠的機器都預設安裝 Python。顯然的 HP 與 Compaq 部分的管理工具程式是透"
```

2021-12-16 04:28 UTC, allen91wu commented on faq/installed.po
> +"仍需再次處理這些事情。"
```suggestion
"，才能再次解決這些問題。"
```

2021-12-16 04:28 UTC, allen91wu commented on c-api/descriptor.po
> +"如果 descriptor 物件 *descr* 描述的是一個資料屬性則返回非零值，或者如果它描述"
```suggestion
"如果 descriptor 物件 *descr* 描述的是一個資料屬性則回傳非零值，或者如果它描述"
```

2021-12-16 04:28 UTC, allen91wu commented on c-api/bool.po
> +"const:`Py_True` 兩個 boolean，因此一般的建立和刪除函式並不適用於 boolean，但"
```suggestion
"const:`Py_True` 兩個 boolean。因此一般的建立和刪除函式並不適用於 boolean。但"
```

2021-12-16 04:28 UTC, allen91wu commented on c-api/bool.po
> +"Python 的 ``False`` 物件。此物件沒有任何方法，在參照 (reference) 計數上必須有"
```suggestion
"Python 的 ``False`` 物件。此物件沒有任何方法。在參照 (reference) 計數上必須有"
```

2021-12-16 04:28 UTC, allen91wu commented on c-api/bool.po
> +"Python 的 ``True`` 物件。此物件沒有任何方法，在參照計數上必須有著和其他物件一"
```suggestion
"Python 的 ``True`` 物件。此物件沒有任何方法。在參照計數上必須有著和其他物件一"
```

2021-12-16 06:13 UTC, allen91wu approved these changes
Looks good!

2021-12-16 06:22 UTC, merged