3.7 translation of tutorial/venv.po
python/python-docs-zh-tw pull request #17
Opened 2018-07-12 12:49 UTC by tai271828

This PR merged the work of https://github.com/python/python-docs-zh-tw/pull/10/files and completed the whole session of tutorial/venv.po

2018-07-13 17:22 UTC, adrianliaw requested changes
Thanks for contributing!  I've commented some suggestions in the code review, and they're mostly about conventions or formatting, and some syntax corrections.  Please feel free to give comments if you don't agree with some of my suggestions.

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +msgstr "虛擬環境與相關套件"
這邊翻譯成「相關」套件有特別的原因嗎？

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"Python 應用程式通常會用到不會和標準函式庫一起釋出的套件與模組。應用程式有時後"
s/有時後/有時候/

另外我覺得第一句有一點點不太通暢，也許「不會和標準函式庫一起釋出的套件與模組」可以改成「不在標準函式庫的套件和模組」？

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"不管安裝 1.0 或是 2.0 都會衝突，以至於應用程式無法使用。"
s/以至於/以致於/

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"需要一個特別的模組的 1.0 版，但另外一個應用程式 B 需要 2.0 版，那麼這整個需求"
我覺得「a particular module」也許翻譯成「一個特定模組」會比較順一點？

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"解決方案是創建一個 :term:`虛擬環境`，這是一個獨立的資料夾，並且裡面裝好的特定"
s/裝好的/裝好了/

另外，這個 rST 語法會讓 sphinx 無法辨識，因為「虛擬環境」並沒有出現在 glossary 頁面裡（glossary 裡面的是 "virtual environment"），這邊可以把這個：

```rst
:term:`虛擬環境`
```

替代成：

```rst
:term:`虛擬環境 <virtual environment>`
```

就不會有找不到 term 的問題了。

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"不同的應用程式可以使用不同的虛擬話環境。以前述中需要被解決的例子中，應用程式 "
s/虛擬話環境/虛擬環境/

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"A 能夠擁有他自己的虛擬環境，並且是裝好 1.0 版，然而應用程式 B 則可以是用另外"
s/他/它/

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"用來建立與管理虛擬環境的模組叫做 :mod:`venv`。 :mod:`venv`通常會安裝你能夠取"
第二個 <code>:mod:\`venv\`</code> 前面多一個空格，後面少一個空格

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"mod:`venv` 模組並且給定資料夾 path::"
這邊冒號的寫法請參照 https://github.com/python/python-docs-zh-tw#rst 的最後一項說明

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"如果 ``tutorial-env`` 不存在的話，這會建立 ``tutorial-env`` 資料夾，並且也會"
這邊最後一句我覺得需要加個「在裡面」，也就會變成「並且也會在裡面建立一個有....」，不然容易誤導使用者以為是 flat directory structure 那樣

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +msgstr "一旦你建立了一個虛擬環境，你可能需要啟動他。"
這邊的 "may" 應該是「可以」的意思，不是「可能」

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +msgstr "在 Windows 系統中，使用："
請參照 https://github.com/python/python-docs-zh-tw#rst 中冒號的使用方式

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +msgstr "在 Unix 或 MacOS 系統，使用："
同上

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"（這段程式碼適用於bash shell. 如果你是用 :program: `csh` 或者 :program:"
bash shell 前應加空格，句點應使用全形句點

<code>:program: \`csh\`</code> 則是中間不能有空格。

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"`fish` shells，應當使用替代的 ``activate.csh`` 與 ``activate.fish`` 程式"
原文的 shells 是英文文法中的複數，但中文文法裡面名詞沒有複數形式，所以這邊用單數 "shell" 應該會比較合理。

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"碼。）"
這個「程式碼」也許可以改成腳本或 script 會比較適合

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"啟動虛擬環境會改變你的 Shell 命令列提示來顯示你正在使用的虛擬環境，修改環境讓"
s/Shell 命令列提示/shell 提示字元/ （還是shell 命令提示字元？）

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"你在執行 ``python`` 的時候可以取得並定的 Python 版本並且安裝它，例如說:"
s/並定的/特定的/

另外，這裡的 "installation" 是名詞，是指「Python 的安裝（結果）」，所以意思上並不是「取得 ..... 並且安裝它」。不過在這一句的話，我覺得 "and installation" 的部分如果直接從譯文中拿掉也不會影響大意。

最後的冒號請記得使用全形冒號

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +msgstr "用 pip 管理套件們"
s/套件們/套件/

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"你使用一個叫做 :program:`pip` 的程式來安裝、升級和移除套件。``pip`` 預設會從 "
s/你使用/你可以使用/

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"Python Package Index，或是使用 ``pip`` 的限定搜索功能:"
冒號請使用全形

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"``pip`` 有好幾個子指令: \"search\", \"install\", \"uninstall\", \"freeze\", "
冒號請使用全形冒號，另外這邊的逗點也應該改成全形頓點。

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"等等。（這可以參考 :ref:`installing-index` 說明書來取得 ``pip`` 的完整文件說"
<code>:ref:\`installing-index\`</code> 的前後請參考 https://github.com/python/python-docs-zh-tw#rst 第二點的書寫方式，不然會產生不必要的空格

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +msgstr "你可以透過指定套件名字來安裝最新版本的套件:"
冒號

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +msgstr "你也可以透過給定在套件名稱之後接上 ``==`` 和版號名稱來指定特定版本:"
這邊如果把「給定」拿掉的話，語句感覺會比較通順一點。

「版號名稱」也可以直接叫做「版號」，看起來也比較不容易和「套件名稱」混淆

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"要是你重新執行指令，``pip`` 會知道已經安裝過的版本，然後什麼也不做。你可以提"
要是你重新執行「此」指令，pip 會知道「該版本已經安裝過」

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"升級到最新的版本:"
冒號

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +msgstr "``pip show`` 可以顯示特定版本的套件的資訊:"
這邊的原文好像就沒有特別講 "specific version" 或 "particular version"，所以應該可以改成
「特定~~版本的~~套件的資訊」

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"``pip freeze`` 可以複製一個整已經安裝套件的清單，但是輸出使用 ``pip "
s/已經安裝套件的清單/已經安裝的套件清單/

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"``requirements.txt`` 的檔案:"
冒號

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"可以透過``install -r`` 安裝對應的的套件。"
<code>\`\`install -r\`\`</code> 前面少一個空格

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"``pip`` 有更多功能。可以參考 :ref:`installing-index` 說明書來取得完整的 "
參考 L166

2018-07-13 17:22 UTC, adrianliaw commented on tutorial/venv.po
> +"上可以取得的話，可以參考  :ref:`distributing-index` 說明。"
s/可以// （已經出現在句子前面一段）

ref 則同上，請參考 L166

2018-08-14 10:40 UTC, tai271828 commented on tutorial/venv.po
> +msgstr "虛擬環境與相關套件"
No, just redundant words, will fix. Thanks for the review.

2018-08-14 10:45 UTC, tai271828 commented on tutorial/venv.po
> +"A 能夠擁有他自己的虛擬環境，並且是裝好 1.0 版，然而應用程式 B 則可以是用另外"
說實在的我時代的小學課本只有「他」；不過用「它」也很好。

2018-08-14 10:47 UTC, tai271828 commented on tutorial/venv.po
> +"用來建立與管理虛擬環境的模組叫做 :mod:`venv`。 :mod:`venv`通常會安裝你能夠取"
下一版我會使用統一前後都有一個空格

2018-08-14 11:06 UTC, tai271828 commented
Fixed all stuff suggested in the previous review.

2018-08-14 11:11 UTC, adrianliaw commented on tutorial/venv.po
> +"A 能夠擁有他自己的虛擬環境，並且是裝好 1.0 版，然而應用程式 B 則可以是用另外"
我以為我只會被用 3.5 磁片嗆年紀小而已，原來這個也可以.............

2018-08-15 08:48 UTC, tai271828 commented
I have built the html to check the syntax. I think the PR is ready to review again now. The only question I have is the quote:

```
有好幾個子指令： 「search」，」install」，」uninstall」, 「freeze」, 等等。
```

It looks good in my po file. However, it shows a bit weird in the translated text. Is this expected or a build process bug?

2018-08-16 13:25 UTC, adrianliaw commented
It seems like a problem from Docutils' localised smart quotes [1], there was a same problem in the Japanese translation, thus there was a docutils.conf added in CPython's Doc directory [2] that disables ja localisation's smart quotes.  Let's just keep it correct inside the po file for now, I'll send an email to the Doc-SIG some time.

[1] http://docutils.sourceforge.net/docs/user/smartquotes.html#localisation
[2] https://github.com/python/cpython/pull/4006

2018-08-22 09:00 UTC, merged