Translate `library/tempfile.po`
python/python-docs-zh-tw pull request #186
Opened 2021-12-18 08:27 UTC by mattwang44

resolve #185

2021-12-19 16:13 UTC, mattwang44 commented
@allen91wu, would you like to review this PR? (trying to slow your pace 😏)

2022-03-17 03:33 UTC, mattwang44 commented
@allen91wu 
Is there any chance you can finish reviewing this PR recently? Or should I assign it to another reviewer?

2022-06-11 11:55 UTC, ccwang002 requested changes
我列了一些我覺得有點不順的詞句，你看看要不要修改。其餘部份都 ok 👍

2022-06-11 11:55 UTC, ccwang002 commented on library/tempfile.po
> +"collect) 時所關閉）後立即銷毀。在 Unix 下，該檔案在目錄中的條目可能根本不被建"
「被垃圾回收…時所關閉」沒有翻到 implicit，可以改成「被垃圾回收…時的隱式關閉」

2022-06-11 11:55 UTC, ccwang002 commented on library/tempfile.po
> +"collect) 時所關閉）後立即銷毀。在 Unix 下，該檔案在目錄中的條目可能根本不被建"
「該檔案在目錄中的條目可能根本不被建立」這句的意思是不是「該檔案所在的目錄可能根本不被建立」？

2022-06-11 11:55 UTC, ccwang002 commented on library/tempfile.po
> +msgstr "如果可用，使用的是 :py:data:`os.O_TMPFILE` 旗標。"
「…使用的是…旗標」改成「…自此開始使用…旗標」

2022-06-11 11:55 UTC, ccwang002 commented on library/tempfile.po
> +"叫為止，此時資料會被寫入磁碟，並且寫入操作與 :func:`TemporaryFile` 相同。"
「此時資料會被寫入磁碟，並且寫入操作與…相同」應為「此時資料會被寫入磁碟，並且之後的操作與…相同」

2022-06-11 11:55 UTC, ccwang002 commented on library/tempfile.po
> +"*ignore_cleanup_errors* 為 true，則若在顯式或隱式清理期間出現的未處理例外（例"
「則若在顯式或隱式」改成「則在顯式或隱式」

2022-06-11 11:55 UTC, ccwang002 commented on library/tempfile.po
> +"發生時被引發。"
「錯誤將在任何情境清理（……）發生時被引發。」調換一下順序「錯誤將在任何情境清理發生時被引發（……）。」感覺比較好讀

2022-06-11 11:55 UTC, ccwang002 commented on library/tempfile.po
> +"案路徑有完整特性，比如透過 ``os.popen()`` 將路徑傳遞給外部命令時仍需要加引號 "
「不能保證生成的臨時檔案路徑有完整特性」要不要翻成「不能保證生成的臨時檔案路徑是使用者友善的」？

2022-06-11 11:55 UTC, ccwang002 commented on library/tempfile.po
> +":func:`mkstemp` 回傳一個 tuple，tuple 中，第一個元素是一個作業系統層級 (OS-"
不確定「OS-level handle」是否翻成「作業系統層級控制程式」

2022-06-11 11:59 UTC, ccwang002 commented on library/tempfile.po
> +"collect) 時所關閉）後立即銷毀。在 Unix 下，該檔案在目錄中的條目可能根本不被建"
```suggestion
"collect) 時的隱式關閉）後立即銷毀。在 Unix 下，該檔案所在的目錄可能根本不被建"
```

2022-06-11 12:00 UTC, ccwang002 commented on library/tempfile.po
> +msgstr "如果可用，使用的是 :py:data:`os.O_TMPFILE` 旗標。"
```suggestion
msgstr "如果可用，自此開始使用 :py:data:`os.O_TMPFILE` 旗標。"
```

2022-06-11 12:01 UTC, ccwang002 commented on library/tempfile.po
> +"*ignore_cleanup_errors* 為 true，則若在顯式或隱式清理期間出現的未處理例外（例"
```suggestion
"*ignore_cleanup_errors* 為 true，則在顯式或隱式清理期間出現的未處理例外（例"
```

2022-06-12 07:01 UTC, mattwang44 commented on library/tempfile.po
> +"collect) 時所關閉）後立即銷毀。在 Unix 下，該檔案在目錄中的條目可能根本不被建"
對，原譯文不夠精確

2022-06-12 07:12 UTC, mattwang44 commented on library/tempfile.po
> +":func:`mkstemp` 回傳一個 tuple，tuple 中，第一個元素是一個作業系統層級 (OS-"
原譯文是錯誤的，原本以為是 handler 所以翻成「控制程式」，但這邊的 handle 其實就是一個數字代號，改成「控制代碼」
- [{控制代碼、句柄}@Wikipedia](https://zh.wikipedia.org/zh-tw/%E5%8F%A5%E6%9F%84)

2022-06-12 12:46 UTC, ccwang002 approved these changes
LGTM! 辛苦啦~

2022-06-12 13:27 UTC, merged