Translate `library/queue.po`
python/python-docs-zh-tw pull request #187
Opened 2021-12-18 11:26 UTC by allen91wu

resolve #181 

## Preview
![image](https://user-images.githubusercontent.com/71866365/146639264-1e4caa63-954f-4b23-81af-e92a7578c0cc.png)

2021-12-19 16:09 UTC, mattwang44 commented
@jordanSu, would you be interested in reviewing this PR?

2022-01-10 12:53 UTC, jordanSu commented
@mattwang44 sorry for late reply, sure let me review this.

2022-01-17 03:42 UTC, mattwang44 commented
@jordanSu I've sent an invitation for joining this project (in order to set you as a reviewer) a while ago. Remember to confirm it ([link](https://github.com/python/python-docs-zh-tw/invitations)).

2022-01-17 04:28 UTC, jordanSu commented
> @jordanSu I've sent an invitation for joining this project (in order to set you as a reviewer) a while ago. Remember to confirm it ([link](https://github.com/python/python-docs-zh-tw/invitations)).

@mattwang44 sorry for missing the invitation, I found the link has expired, could you kindly send me a new one? Thanks a lot!

2022-01-17 04:31 UTC, mattwang44 commented
@jordanSu just sent!

2022-03-17 03:35 UTC, mattwang44 commented
@jordanSu 
Is there any chance you can finish reviewing this PR recently? Or should I assign it to another reviewer?

2022-03-17 03:55 UTC, jordanSu commented
@mattwang44 Sorry for late, I might not be able to review it recently, I think it would be better to assign this to another reviewer.
Sorry for making you guys wait🙇

2022-03-17 05:39 UTC, mattwang44 commented
@jordanSu NP! Thanks for the efforts. Look forward to seeing your contribution again!

2022-07-04 02:50 UTC, StevenHsuYL requested changes
幫忙 review 一下。
建議僅供參考，大多是閱讀流暢度的小建議，都可以再討論。 😃

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +msgstr ":mod:`queue` --- 同步佇列 (quene) class（類別）"
```suggestion
msgstr ":mod:`queue` --- 同步佇列 (queue) class（類別）"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +":mod:`queue` 模組實作多生產者、多消費者佇列。在執行緒程式設計中，必須在多執行"
```suggestion
":mod:`queue` module（模組）實作多生產者、多消費者佇列。在執行緒程式設計中，必須在多執行"
```
module 第一次出現，要保留原文及譯文。

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"(stack) 一樣操作）。使用優先佇列時，條目將保持排序狀態（使用 :mod:`heapq` "
```suggestion
"(stack) 一樣操作）。使用優先佇列 (priority queue) 時，條目將保持排序狀態（使用 :mod:`heapq` "
```
priority queue 建議加註原文

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"在內部，這三種型別的佇列使用鎖來臨時鎖定競爭執行緒；但是，它們並不是被設計來"
```suggestion
"在內部，這三種型別的佇列使用鎖 (lock) 來暫時阻塞競爭執行緒；但是，它們並不是被設計來"
```
temporary: 暫時
lock 建議加註原文
block 考慮統一使用「阻塞」

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"別 :class:`SimpleQueue`，其明確的實作提供了額外的保證，以換取較小的功能。"
```suggestion
"別 :class:`SimpleQueue`，其特定的實作是以較少的功能為代價，來提供額外的保證。"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"個整數，用於設置佇列中可放置的項目數的上限。一旦達到此大小，插入將被鎖定，直"
```suggestion
"個整數，用於設置佇列中可放置的項目數的上限。一旦達到此大小，插入將會阻塞，直"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"到佇列中的項目被消耗完。如果 *maxsize* 小於或等於零，則佇列大小為無限。"
```suggestion
"到佇列中的項目被消耗。如果 *maxsize* 小於或等於零，則佇列大小為無限。"
```
我的理解是，應該不用等到項目被消耗完，只要有空間就可以解除 block。

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"中可放置的項目數的上限。一旦達到此大小，插入將被鎖定，直到佇列中的項目被消耗"
```suggestion
"中可放置的項目數的上限。一旦達到此大小，插入將會阻塞，直到佇列中的項目被消耗"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"完。如果 *maxsize* 小於或等於零，則佇列大小為無限。"
```suggestion
"。如果 *maxsize* 小於或等於零，則佇列大小為無限。"
```
同上建議。

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"一旦達到此大小，插入將被鎖定，直到佇列中的項目被消耗完。如果 *maxsize* 小於或"
```suggestion
"一旦達到此大小，插入將會阻塞，直到佇列中的項目被消耗。如果 *maxsize* 小於或"
```
同上建議。

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"首先取出最低值的條目（最低值的條目是 ``sorted(list(entries))[0]`` 回傳的）。"
```suggestion
"最低值的條目會最先被取出（最低值的條目是被 ``sorted(list(entries))[0]`` 回傳的）。"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"條目的典型模式是格式為 ``(priority_number, data)`` 的 tuple。"
```suggestion
"條目的典型模式是格式為 ``(priority_number, data)`` 的 tuple（元組）。"
```
tuple 首次出現，建議以括號加上譯文。

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"如果 *data* 元素為不可比較的，則可以將資料包裝在一個 class 中，該類忽略資料項"
```suggestion
"如果 *data* 元素為不可比較的，則可以將資料包裝在一個 class 中，該 class 忽略資料項"
```
class 保留原文。

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"當對一個空的 :class:`Queue` 物件呼叫非阻塞的 :meth:`~Queue.get`\\ （或 :meth:"
```suggestion
"當對一個空的 :class:`Queue` 物件呼叫非阻塞的 (non-blocking) :meth:`~Queue.get`\\ （或 :meth:"
```
建議加註原文

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"`~Queue.get_nowait`\\ ）將引發例外。"
```suggestion
"`~Queue.get_nowait`\\ ）將引發此例外。"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"meth:`~Queue.put_nowait`）將引發例外。"
```suggestion
"meth:`~Queue.put_nowait`）將引發此例外。"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"`PriorityQueue`\\ ）提供下面描述的公開方法。"
```suggestion
"`PriorityQueue`\\ ）提供下面描述的公用 method。"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"如果佇列為空，則回傳``True``，否則返回 ``False``。如果 empty() 回傳 "
```suggestion
"如果佇列為空，則回傳 ``True``，否則回傳 ``False``。如果 empty() 回傳 "
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"如果佇列已滿，則回傳``True`` ，否則返回 ``False``。如果 full() 回傳 "
```suggestion
"如果佇列已滿，則回傳 ``True`` ，否則回傳 ``False``。如果 full() 回傳 "
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"``True``，則不保證後續呼叫 get() 不會阻塞。同樣，如果 full() 傳回 ``False``，"
```suggestion
"``True``，則不保證後續呼叫 get() 不會阻塞。同樣，如果 full() 回傳 ``False``，"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"\\ （預設值），則在必要時阻塞，直到自由槽可用。如果 *timeout* 為正數，則最多"
```suggestion
"\\ （預設值），則在必要時阻塞，直到自由槽 (free slot) 可用。如果 *timeout* 為正數，則最多"
```
首次出現建議加註原文

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"阻塞 *timeout* 秒，如果該時間內沒有可用槽，則會引發 :exc:`Full` 例外。否則"
```suggestion
"阻塞 *timeout* 秒，如果該時間內沒有可用的自由槽，則會引發 :exc:`Full` 例外。否則"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"`Full` 例外（*在這種情況下，*timeout* 將被忽略）。"
```suggestion
"`Full` 例外（在這種情況下，*timeout* 將被忽略）。"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"從佇列中刪除並返回專案。如果可選的 args *block* 為 true，並且 *timeout* 為"
```suggestion
"從佇列中移除並回傳一個項目。如果可選的 args *block* 為 true，且 *timeout* 為"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"\"None\"（預設值），則在必要時阻塞，直到項目可用。如果 *timeout* 是正數，則最"
```suggestion
" ``None``\\ （預設值），則在必要時阻塞，直到有可用的項目。如果 *timeout* 是正數，則最"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"多會阻止 *timeout* 秒，如果該時間內沒有可用的項目，則會引發 :exc:`Empty` 例"
```suggestion
"多會阻塞 *timeout* 秒，如果該時間內沒有可用的項目，則會引發 :exc:`Empty` 例"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"且 *timeout* 為\"None\"，則此操作將在底層鎖上進入不間斷等待。這意味著不會發生"
```suggestion
"且 *timeout* 為 ``None``，則此操作將在底層鎖上進入不間斷等待。這意味著不會發生"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"在 POSIX 系統上的 3.0 之前，對於 Windows 上的所有版本，如果 *block* 為 true "
```suggestion
"在 POSIX 系統的 3.0 版之前，以及 Windows 的所有版本，如果 *block* 為 true "
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"提供了兩種方法來支援追蹤放入佇列的任務是否已由常駐使用者執行緒 (daemon "
```suggestion
"有兩個 method 可以支援追蹤放入佇列的任務是否已由常駐消費者執行緒 (daemon "
```
consumer: 消費者，建議與上面的譯文統一。

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"指示以前放入佇列的任務已完成。由佇列使用者執行緒使用。對於用於獲取任務的每"
```suggestion
"指示先前放入佇列的任務已完成。由佇列消費者執行緒使用。對於用來提取任務的每"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +msgstr "如果呼叫次數超過佇列中放置的項目，則引發 :exc:`ValueError`\\ 。"
```suggestion
msgstr "如果呼叫次數超過佇列中放置的項目數量，則引發 :exc:`ValueError`\\ 。"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +msgstr "阻塞直到佇列中的所有項目都已獲取並處理完畢。"
```suggestion
msgstr "持續阻塞直到佇列中的所有項目都已被獲取並處理完畢。"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"每當項目被加到佇列中時，未完成任務的計數都會增加。每當使用者執行緒呼叫 :meth:"
```suggestion
"每當項目被加到佇列中時，未完成任務的計數都會增加。每當消費者執行緒呼叫 :meth:"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"有必需的鎖定語義 (Semantics)。"
```suggestion
"有必需的鎖定語義 (locking semantics)。"
```
建議把鎖定語義加註原文

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +msgstr "簡單佇列物件"
```suggestion
msgstr "SimpleQueue 物件"
```
因為原文兩個字之間並沒有空格，為特定物件名稱，建議保留原文不翻譯。

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +msgstr ":class:`SimpleQueue` 物件提供下面描述的公開方法。"
```suggestion
msgstr ":class:`SimpleQueue` 物件提供下面描述的公用 method。"
```
同 line 171

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"將 *item* 放入佇列中。該方法從不阻塞，並且都會成功（潛在的初階錯誤，像是分配"
```suggestion
"將 *item* 放入佇列中。此 method 從不阻塞，並且都會成功（潛在的低階錯誤，像是分配"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"從佇列中刪除並傳回項目。如果可選的 args *block* 為 true，並且 *timeout* 為"
```suggestion
"從佇列中移除並回傳一個項目。如果可選的 args *block* 為 true，且 *timeout* 為"
```
同 line 234

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"\"None\"（預設值），則在必要時阻塞，直到項目可用。如果 *timeout* 是正數，則最"
```suggestion
" ``None``\\ （預設值），則在必要時阻塞，直到有可用的項目。如果 *timeout* 是正數，則最"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +"外。否則（*block* 為 false），如果立即可用，則傳回一個項目，否則引發 :exc:"
```suggestion
"外。否則（*block* 為 false），如果立即可用，則回傳一個項目，否則引發 :exc:"
```

2022-07-04 02:50 UTC, StevenHsuYL commented on library/queue.po
> +msgstr "用於多工（而非多執行緒）上下文的佇列 class。"
```suggestion
msgstr "用於多元處理（而非多執行緒）上下文的佇列 class。"
```
Reference: [多元處理 wiki](https://zh.wikipedia.org/zh-tw/%E5%A4%9A%E5%85%83%E8%99%95%E7%90%86)

2022-07-05 18:38 UTC, mattwang44 commented
> 幫忙 review 一下。 建議僅供參考，大多是閱讀流暢度的小建議，都可以再討論。 😃

感謝 Steven！這個 PR 我會接手處理

2022-09-24 07:13 UTC, allen91wu commented
Thanks for the review from Steven. I'm just updated the file from the review. Please have a look!

2022-09-24 17:44 UTC, mattwang44 reviewed
前面 Steven 的 comment 還有一些沒修掉，要再請你檢查一下 🙏🏽

2022-09-24 17:44 UTC, mattwang44 commented on library/queue.po
> +"`LIFO (last-in, first-out)` 佇列的建構子。*maxsize* 是一個整數，用於設置佇列"
```suggestion
":abbr:`LIFO (last-in, first-out)` 佇列的建構子。*maxsize* 是一個整數，用於設置佇列"
```

2022-09-24 17:44 UTC, mattwang44 commented on library/queue.po
> +"`PriorityQueue`\\ ）提供下面描述的公用 method。"
因為都在標點符號旁邊，`\\ ` 好像都可以不用加（以前我會加，好像因此誤導了大家 🧎🏽‍♂️），可以刪掉再 build 一次檢查看看；這篇也有其他是在標點符號旁的 `\\ `，要麻煩檢查一下。

2022-09-24 17:44 UTC, mattwang44 commented on library/queue.po
> +"`PriorityQueue`\\ ）提供下面描述的公用 method。"
公開好像比較合適？需要麻煩你再查閱一下

```suggestion
"佇列物件（\\ :class:`Queue`\\ 、\\ :class:`LifoQueue`\\ 、\\ :class:"
"`PriorityQueue`\\ ）提供下面描述的公開 method。"
```

2022-09-24 17:44 UTC, mattwang44 commented on library/queue.po
> +"指示指示先前放入佇列的任務已完成。由佇列消費者執行緒使用。對於用來提取任務的"
```suggestion
"表示先前放入佇列的任務已完成。由佇列消費者執行緒使用。對於用來提取任務的"
```

2022-09-24 17:44 UTC, mattwang44 commented on library/queue.po
> +"於 :meth:`put` 已進入佇列的每個項目，都收到 :meth:`task_done` 的呼叫）。"
```suggestion
"如果目前 :meth:`join` 阻塞，它將會在所有項目都已處理完畢後恢復（代表對"
"於以 :meth:`put` 放進佇列的每個項目，都要收到 :meth:`task_done` 的呼叫）。"
```

2022-09-24 17:44 UTC, mattwang44 commented on library/queue.po
> +msgstr ":class:`SimpleQueue` 物件提供下面描述的公用 method。"
ditto
```suggestion
msgstr ":class:`SimpleQueue` 物件提供下面描述的公開 method。"
```

2022-09-24 17:44 UTC, mattwang44 commented on library/queue.po
> +"分配記憶體失敗除外）。可選的 args *block* 和 *timeout* 將被忽略，並且僅用於"
```suggestion
"將 *item* 放入佇列中。此 method 從不阻塞，並且都會成功（除了潛在的低階錯誤，像是"
"分配記憶體失敗）。可選的 args *block* 和 *timeout* 將被忽略，並且僅用於"
```

2022-09-24 17:44 UTC, mattwang44 commented on library/queue.po
> +"與 :meth:`Queue.put` 相容。"
```suggestion
"分配記憶體失敗除外）。可選的 args *block* 和 *timeout* 會被忽略，它們僅是為了"
"與 :meth:`Queue.put` 相容才存在。"
```

2022-09-24 17:44 UTC, mattwang44 commented on library/queue.po
> +msgstr "用於多工處理（而非多執行緒）上下文的佇列 class。"
```suggestion
msgstr "用於多行程處理 (multi-processing)（而非多執行緒）情境 (context) 的佇列 class。"
```

2022-09-24 17:44 UTC, mattwang44 commented on library/queue.po
> +"`~collections.deque.append` 和 :meth:`~collections.deque.popleft` 操作，這些"
```suggestion
":class:`collections.deque` 是無界佇列的替代實作，具有快速且具原子性 (atomic) 的 :meth:"
"`~collections.deque.append` 和 :meth:`~collections.deque.popleft` 操作，這些"
```

2022-09-24 17:46 UTC, mattwang44 commented on library/queue.po
> +msgstr "用於多工（而非多執行緒）上下文的佇列 class。"
process 一詞目前多翻譯為`行程`

```suggestion
msgstr "用於多行程處理 (multi-processing)（而非多執行緒）情境 (context) 的佇列 class。"
```

2022-09-26 16:10 UTC, mattwang44 commented
@allen91wu 還差 FIFO 那段 (`../../library/queue.rst:37`) 的 `消耗完` 要改成 `消耗`
https://github.com/python/python-docs-zh-tw/pull/187#discussion_r912492247

2022-09-26 16:13 UTC, allen91wu commented
@mattwang44 感謝提醒，已經 push 修正過後的版本

2022-09-26 19:06 UTC, mattwang44 submitted a review, later dismissed
LGTM
看 @StevenHsuYL 有沒有興趣再檢查一下~

2022-09-27 13:28 UTC, StevenHsuYL commented on library/queue.po
> +"與 :meth:`Queue.put` 相容才存在。"
```suggestion
"與 :meth:`Queue.put` 相容才存在。"

#: ../../library/queue.rst:243
msgid ""
"This method has a C implementation which is reentrant.  That is, a ``put()`` "
"or ``get()`` call can be interrupted by another ``put()`` call in the same "
"thread without deadlocking or corrupting internal state inside the queue.  "
"This makes it appropriate for use in destructors such as ``__del__`` methods "
"or :mod:`weakref` callbacks."
msgstr ""
"此 method 有一個可重入 (reentrant) 的 C 實作。意思就是，一個 ``put()`` 或 "
"``get()`` 呼叫，可以被同一執行緒中的另一個 ``put()`` 呼叫中斷，而不會造成死"
"鎖 (deadlock) 或損壞佇列中的內部狀態。這使得它適合在解構子 (destructor) 中使"
"用，像是 ``__del__`` methods 或 :mod:`weakref` 回呼函式 (callback)。"
```

建議加上這段，譯文較完整。
不過這段目前 html 會編不出來，除非在 cpython 對應 rst 檔的  ``.. impl-detail::`` 
下面加一個空行，才能正常顯示譯文。
（我是去修改rst才成功的，之後有空我再去提issue）

Preview:
![library-queue](https://user-images.githubusercontent.com/81967953/192539389-8545def8-17db-489b-9130-e907cfdac28a.jpeg)

2022-09-27 19:45 UTC, mattwang44 commented on library/queue.po
> +"與 :meth:`Queue.put` 相容才存在。"
大大也太細心，不過這個在 make merge 的時候是不是就會被註解掉？

2022-09-28 01:43 UTC, StevenHsuYL commented on library/queue.po
> +"與 :meth:`Queue.put` 相容才存在。"
我也不知道 make merge 會不會被註解掉，但我發現 glossary.po 的 "CPython implementation detail" 是有成功編譯的，
然後發現編譯成功與失敗的差別，只在於 rst 原始檔有留一個空行在 `.. impl-detail::` 下面。
如果這段先放在註解也沒關係，等到 rst 修正空行之後，再把它放回來也可以。
請見 glossary: [iterator](https://docs.python.org/zh-tw/3/glossary.html#term-iterator)。

2022-09-28 03:30 UTC, StevenHsuYL approved these changes, later dismissed
LGTM (with optional editing later). 👍

2022-09-29 03:17 UTC, allen91wu commented
@mattwang44 @StevenHsuYL 
I’m just updated the file from Steven’s suggestion. Please have a look.

2022-09-29 04:47 UTC, StevenHsuYL commented
> @mattwang44 @StevenHsuYL I’m just updated the file from Steven’s suggestion. Please have a look.

line 360-371 好像重複貼上了，再麻煩修改一下，謝謝！

2022-09-29 11:16 UTC, mattwang44 approved these changes
LGTM
Thanks for the great work!

2022-09-29 11:17 UTC, merged

2022-09-30 02:31 UTC, StevenHsuYL commented on library/queue.po
> +"與 :meth:`Queue.put` 相容才存在。"
This issue will be fixed at https://github.com/python/cpython/pull/97652.

2022-09-30 04:08 UTC, mattwang44 commented on library/queue.po
> +"與 :meth:`Queue.put` 相容才存在。"
Great! Thanks for reporting the issue.