Translating tutorial/whatnow
python/python-docs-zh-tw pull request #19
Opened 2018-07-12 13:43 UTC by chairco

close #13

2018-07-15 09:14 UTC, adrianliaw requested changes
感謝幫忙翻譯這個頁面～～✨✨有一些小細節是希望可以修正的，大多都是跟中文文法相關，或是一些用詞上面的建議，如果有不同意的地方歡迎拿出來討論！再麻煩你囉！

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +msgstr "本教學是 Python 文件中的一部分。這份匯總裡頭的其他文件會有："
這邊的「匯總」也許是要翻譯「set」？如果是的話，我會偏好翻譯成「文件集」，「匯總」會比較貼近 summary、aggregation 這類的意思，應該不適用在這個翻譯

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +msgstr ":ref:`library-index`:"
最後一個冒號請用全形冒號～（非 rST 語法的一部分）

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"你確實該瀏覽這份手冊，它提供了完整的（儘管簡潔）參考素材像是類型、函式與標準"
"though" 可以有「僅管」或「但」的意思，這裡應該比較貼近「但」。

s/類型/型別/

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"函式庫裡的模組。標準 Python 分佈包含了*大量*的附加程式碼。有些模組可以讀取 "
s/標準/標準的/
s/分佈/發行版/

星號語法前後需要依照 https://github.com/python/python-docs-zh-tw#rst 的第二點注意事項加上沒有寬度的分隔符號。

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"縮資料，及許多其他任務。瀏覽 Library Reference 可以讓你了解何種會是可用的想"
看了一下原文，似乎這個 "Library Reference" 指的就是 "The Python Standard Library" 文件集（即 library/ 底下的內容），這樣的話就可以比照 [library/index.po](https://github.com/python/python-docs-zh-tw/blob/3.7/library/index.po#L35-L36) 裡面所用的「函式庫參考手冊」。

另外，「give you an idea」意思就是「讓你了解」，所以這句話的意思比較接近「可以讓你了解有什麼東西可以用」。

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +msgstr ":ref:`installing-index` 解釋如何安裝其他 Python 使用者所編寫得模組。"
s/得/的/

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +":ref:`reference-index`: Python 語法以及語意的詳細說明。這份文件閱讀起來會有些"
<code>:ref:\`reference-index\`</code>後面的冒號請用全形冒號。

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"https://www.python.org：主要的 Python 網站。它包含程式碼，文件以及指向 "
程式碼後面的逗點應該是要用頓點。

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"Python 周圍相關的網頁。網站是鏡像的並設置於世界各地，像是歐洲、日本以及澳大利"
原文的「around」應該是指「around the web」，跟 Python 沒有關係，這邊我覺得「Python 周圍」可以改成只說「Python」就可以了。

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"https://pypi.org：Python 套件索引，之前也被暱稱為 Cheese Shop，是個使用者所建"
「Python 套件索引」這邊宜加上括弧注釋原文（注意應該要用「The Python Package Index」，"The" 強調了單一性）

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"裡並且被找到。"
s/並且被找到/讓其他人能找到/

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"立用來提供下載 Python 模組的索引。一旦開始發佈相關程式碼，你可以將其註冊到這"
這句好像有點難翻，我目前能想到最通暢的翻譯是「是個索引，彙整了使用者自建可供下載的 Python 模組」（我也不確定怎麼翻會比較好

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"當大的程式碼範例，大量的模組以及有用的腳本。一些值得注意與特別貢獻則被收集在"
s/範例/範例集/

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"一本名為 Python Cookbook (O’Reilly & Associates, ISBN 0-596-00797-3.) 書中。"
s/書中/的書中/

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"http://www.pyvideo.org 從研討會與使用者群組聚會裡所收集到與 Python 相關的影片"
s/所收集到/收集/ （這樣感覺比較順

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"https://code.activestate.com/recipes/langs/python/：Python Cookbook 是一個相"
話說這個網站好像叫做 ActiveState 還是 ActivePython，不知道是原本就寫錯還是這個專案中間有改名，翻譯就先照原文的說法吧XD 不需要動

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"https://scipy.org：Python 項目包含用於高速陣列計算和操作的模塊，以及用於如線"
原文的 "Scientific Python" 算是一個專名，我想應該要保持原文，在譯文中保有「Scientific Python 專案」的內容（如同上面的 Python Cookbook）

s/計算/運算/
s/模塊/模組/

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"性代數，傅利葉變換，非線性求解器，隨機變數分佈，統計分析等一系列。"
這邊的分隔符號語法上應該用頓點。

s/隨機變數分佈/亂數分佈/

s/一系列/一系列的套件/

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"python`，或將它們寄送 mailing list 至 python-list@python.org 的郵寄清單。新聞"
s/寄送 mailing list 至 python-list@python.org 的郵寄清單/寄送至 python-list@python.org 的郵寄清單（mailing list）/ （一樣也是單純覺得這樣比較順一點

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"以百計的內容，詢問（和回答）問題，建議新功能，宣佈新的模組。郵寄清單存檔在 "
這邊一樣請用頓點。

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"張貼之前，請先確認以下清單 :ref:`Frequently Asked Questions <faq-index>` (也"
s/以下清單 ......./....... 這個清單/

另外，因為原文的 "Frequently Asked Questions" 其實是為了代替 `faq-index` 這個頁面的標題（原本的標題是 "Python Frequently Asked Questions"，見 https://docs.python.org/3/faq/index.html#faq-index ），這邊的譯文應該要保持我們在 `faq-index` 頁面的標題翻譯（https://github.com/python/python-docs-zh-tw/blob/3.7/faq/index.po#L24 ），所以這個 ref 應該會是 <code>:ref:\`常見問題 &lt;faq-index&gt;\`</code> （別忘記前後應該要加上「沒有寬度的分隔符號」）

2018-07-15 09:14 UTC, adrianliaw commented on tutorial/whatnow.po
> +"被稱 FAQ)。 FAQ 會回覆已經多次出現的問題解答，也可能包含已經解決問題的方法。"
FAQ 前有一個多餘的空格

s/回覆/回答/
s/解答//
s/包含已經解決問題的方法/已經包含解決問題的方法/

2018-07-15 11:16 UTC, chairco commented on tutorial/whatnow.po
> +"立用來提供下載 Python 模組的索引。一旦開始發佈相關程式碼，你可以將其註冊到這"
不會太困難的，我想就是把 Pypi 講清楚就好？『彙總了 Python 模組的索引，並能提供給使用者下載這些模組。』這樣呢？

2018-07-15 11:24 UTC, chairco commented on tutorial/whatnow.po
> +"性代數，傅利葉變換，非線性求解器，隨機變數分佈，統計分析等一系列。"
random number distributions 比較偏向是科學計算或是統計用語，通常在電腦科學上確實無法做到真正的隨機數，所以通常會用亂數來表示。例如亂數產生器（當然也可以說是隨機變數產生器，但因為不是真的隨機），但在這邊我會認為是在講科學、統計上用語可能用隨機數分佈會稍微好一些。

2018-07-15 11:25 UTC, chairco commented on tutorial/whatnow.po
> +"python`，或將它們寄送 mailing list 至 python-list@python.org 的郵寄清單。新聞"
不知道我在寫啥 XD

2018-07-15 11:27 UTC, chairco commented on tutorial/whatnow.po
> +msgstr "本教學是 Python 文件中的一部分。這份匯總裡頭的其他文件會有："
同意`文件集`比較好，已經修改。

2018-07-15 11:31 UTC, chairco commented on tutorial/whatnow.po
> +msgstr ":ref:`library-index`:"
已修正

2018-07-15 11:32 UTC, chairco commented on tutorial/whatnow.po
> +"你確實該瀏覽這份手冊，它提供了完整的（儘管簡潔）參考素材像是類型、函式與標準"
已修正

2018-07-15 11:32 UTC, chairco commented on tutorial/whatnow.po
> +"函式庫裡的模組。標準 Python 分佈包含了*大量*的附加程式碼。有些模組可以讀取 "
已修正

2018-07-15 11:34 UTC, chairco commented on tutorial/whatnow.po
> +"縮資料，及許多其他任務。瀏覽 Library Reference 可以讓你了解何種會是可用的想"
如果根據上下文改成：瀏覽函式庫參考手冊可以讓你了解那些模組可能會是有用的。
東西我想他是指模組這類意思，這樣會不會更好？

2018-07-15 11:35 UTC, chairco commented on tutorial/whatnow.po
> +msgstr ":ref:`installing-index` 解釋如何安裝其他 Python 使用者所編寫得模組。"
吃的得，白的的

2018-07-15 11:35 UTC, chairco commented on tutorial/whatnow.po
> +":ref:`reference-index`: Python 語法以及語意的詳細說明。這份文件閱讀起來會有些"
已修正

2018-07-15 11:35 UTC, chairco commented on tutorial/whatnow.po
> +"https://www.python.org：主要的 Python 網站。它包含程式碼，文件以及指向 "
已修正

2018-07-15 11:37 UTC, chairco commented on tutorial/whatnow.po
> +"Python 周圍相關的網頁。網站是鏡像的並設置於世界各地，像是歐洲、日本以及澳大利"
Python 相關聯呢？

2018-07-15 11:37 UTC, chairco commented on tutorial/whatnow.po
> +"https://pypi.org：Python 套件索引，之前也被暱稱為 Cheese Shop，是個使用者所建"
已修正

2018-07-15 11:37 UTC, chairco commented on tutorial/whatnow.po
> +"裡並且被找到。"
已修正

2018-07-15 11:38 UTC, chairco commented on tutorial/whatnow.po
> +"當大的程式碼範例，大量的模組以及有用的腳本。一些值得注意與特別貢獻則被收集在"
已修正

2018-07-15 11:38 UTC, chairco commented on tutorial/whatnow.po
> +"一本名為 Python Cookbook (O’Reilly & Associates, ISBN 0-596-00797-3.) 書中。"
的書籍中？好像比較不會那麼乾

2018-07-15 11:38 UTC, chairco commented on tutorial/whatnow.po
> +"http://www.pyvideo.org 從研討會與使用者群組聚會裡所收集到與 Python 相關的影片"
已修正

2018-07-15 11:39 UTC, chairco commented on tutorial/whatnow.po
> +"https://scipy.org：Python 項目包含用於高速陣列計算和操作的模塊，以及用於如線"
已修正（猜得出是從推薦翻譯翻過來的吧）

2018-07-15 11:40 UTC, chairco commented on tutorial/whatnow.po
> +"以百計的內容，詢問（和回答）問題，建議新功能，宣佈新的模組。郵寄清單存檔在 "
以修正

2018-07-15 11:54 UTC, chairco commented
標題做了更動：`現在可以來學習些什麼？`是覺得會比較符合這篇內容，原本的`現在來做些什麼？`會容易不被重視，但事實上這篇概要的說明一些外部的資源學習管道。

然後謝謝 @adrianliaw  的 review 如果有問題請再告訴我。

2018-07-15 12:25 UTC, chairco commented on tutorial/whatnow.po
> +"張貼之前，請先確認以下清單 :ref:`Frequently Asked Questions <faq-index>` (也"
感謝，這個挺細節已修正。

2018-07-15 12:26 UTC, chairco commented on tutorial/whatnow.po
> +"被稱 FAQ)。 FAQ 會回覆已經多次出現的問題解答，也可能包含已經解決問題的方法。"
已修正

2018-07-16 08:48 UTC, adrianliaw commented on tutorial/whatnow.po
> +"性代數，傅利葉變換，非線性求解器，隨機變數分佈，統計分析等一系列。"
了解，感謝說明～～

2018-07-16 08:51 UTC, adrianliaw commented on tutorial/whatnow.po
> +"縮資料，及許多其他任務。瀏覽 Library Reference 可以讓你了解何種會是可用的想"
但原文是說 "available"，所以意思不大像是「有用的」，而是「可以用的」，不過我蠻喜歡你提出的這個翻譯，感覺可以加在一起變成「瀏覽函式庫參考手冊可以讓你了解有哪些模組可以用」。你覺得呢？

2018-07-16 08:52 UTC, adrianliaw commented on tutorial/whatnow.po
> +msgstr ":ref:`installing-index` 解釋如何安裝其他 Python 使用者所編寫得模組。"
小時候字音字形沒有白學

2018-07-16 08:53 UTC, adrianliaw commented on tutorial/whatnow.po
> +"Python 周圍相關的網頁。網站是鏡像的並設置於世界各地，像是歐洲、日本以及澳大利"
也可以，有看到修改後的結果了～～

2018-07-16 09:01 UTC, adrianliaw commented on tutorial/whatnow.po
> +"立用來提供下載 Python 模組的索引。一旦開始發佈相關程式碼，你可以將其註冊到這"
不過這邊可能要強調一下原文裡面提到的 "user-created" Python modules，因為「Python 模組」可以指標准函式庫裡面的模組，雖然看 context 還是可以推論出來，但最好還是能有翻譯到 "user-created Python modules"。不過我覺得你提出的這個翻譯蠻順的！👍

2018-07-16 09:16 UTC, adrianliaw commented on tutorial/whatnow.po
> +"https://pypi.org：Python 套件索引（The Python Package ），之前也被暱稱為 "
少了 Index XD

2018-07-16 09:33 UTC, adrianliaw commented on tutorial/whatnow.po
> +"一本名為 Python Cookbook (O’Reilly & Associates, ISBN 0-596-00797-3.) 書中。"
也可以～～

2018-07-16 09:59 UTC, adrianliaw commented
@chairco 同意你這邊提出來的翻譯，整個看起來我覺得算蠻順的了，這邊主要就是剩下 PyPI 的一個 typo，剩下的都算是可改可不改，有空間可以討論的部分，這些我就回覆在 comment 裡了，再請你看一下囉～～感謝！

2018-07-17 00:37 UTC, chairco commented on tutorial/whatnow.po
> +"立用來提供下載 Python 模組的索引。一旦開始發佈相關程式碼，你可以將其註冊到這"
彙總了使用者開發 Python 模組的索引，並提供模組能夠被下載。修改的與原本文字更符合一些

2018-07-17 00:39 UTC, chairco commented on tutorial/whatnow.po
> +"縮資料，及許多其他任務。瀏覽 Library Reference 可以讓你了解何種會是可用的想"
歐給 👍

2018-07-17 01:30 UTC, chairco commented
好的，我把 final 的版本推上來了～

2018-07-17 05:48 UTC, adrianliaw approved these changes

2018-07-17 05:48 UTC, merged

2018-07-17 05:49 UTC, adrianliaw commented
🕺