Translate `library/copy.po`
python/python-docs-zh-tw pull request #206
Opened 2022-01-20 10:48 UTC by mattwang44

resolve #205

preview:
![image](https://user-images.githubusercontent.com/24987826/150324256-70b5faba-df9d-4bbd-9da7-bdd492d15562.png)

2022-02-09 17:48 UTC, josix requested changes

2022-02-09 17:48 UTC, josix commented on library/copy.po
> +"該模組不複製模組、方法、堆疊追蹤（stack trace）、堆疊幀（stack frame）、檔"
這邊不太確定 stack frame 應該翻譯成堆疊幀還是堆疊框，找不太到比較常見的繁中用語。

2022-02-09 17:48 UTC, josix commented on library/copy.po
> +"類別可以使用與控制 pickle 操作相同的介面來控制複製操作，關於這些方法的描述資"
```suggestion
"類別可以使用與操作 pickle 相同的介面來控制複製操作，關於這些方法的描述資"
```

2022-02-10 05:07 UTC, mattwang44 commented on library/copy.po
> +"該模組不複製模組、方法、堆疊追蹤（stack trace）、堆疊幀（stack frame）、檔"
感覺「框」才是正確的
https://terms.naer.edu.tw/detail/1278927/?index=1

2022-02-10 06:43 UTC, josix approved these changes
LGTM!

2022-02-10 06:43 UTC, merged