Translating library/asyncio
python/python-docs-zh-tw pull request #22
Opened 2018-07-17 05:35 UTC by chairco

希望 asyncio 這一拖拉頁面能幫忙解決掉（聽說 core team 想對 asyncio library 的教學做大幅度調整）不過還沒聽到太多消息就先來做吧。

2018-07-19 04:05 UTC, adrianliaw reviewed
先 review 到一半，這一篇因為不是第一階段目標，有空才會 review 完XD

2018-07-19 04:05 UTC, adrianliaw commented on library/asyncio.po
> +msgstr ":mod:`asyncio` — 非同步 I/O、事件迴圈、協同程序與任務"
這邊的名詞宜加上括弧注釋原文

2018-07-19 04:05 UTC, adrianliaw commented on library/asyncio.po
> +"Asyncio 模組提供一個在單一線程（single-threaded）內使用協同程序（coroutines）"
這邊如果直接寫出 "Asyncio" 模組的話，應該直接用 inline literal 語法：<code>\`\`asyncio\`\` 模組提供 ....</code>

2018-07-19 04:05 UTC, adrianliaw commented on library/asyncio.po
> +"撰寫並發（concurrent）的程式碼，並使用多路復用 I/O（multiplexing I/O）方式來"
我覺得這邊原文應該是在列舉使用情境，所以應該也是使用頓點。

s/多路復用/多路複用/

2018-07-19 04:05 UTC, adrianliaw commented on library/asyncio.po
> +"連接 sockets 與其他的資源，運作在網路客戶端與伺服器端以及其他相關的原始基礎架"
s/sockets/socket/ （中文文法裡沒有複數概念

如果把這邊原文的這些逗點如上一則留言一樣看作頓點，那這邊 "running clients and servers" 應該會是「運行網路客戶端與伺服器」。"and other related primitives" 則會代表「multiplexing I/O over sockets、network client & server 之外的其他基礎操作」，我覺得這邊的 "primitives" 意思應該是作業 系統的基礎操作（原始操作？）[1]

[1] 可以參考看看這個，這篇問答有提到 `send`、`receive` 這種 OS primitive： https://stackoverflow.com/questions/8022399/meaning-of-primitive-in-operating-system-algorithm-context

2018-07-19 04:47 UTC, chairco commented on library/asyncio.po
> +"連接 sockets 與其他的資源，運作在網路客戶端與伺服器端以及其他相關的原始基礎架"
感謝，我沒注意到 s 

這個 primitive 是令我想了一下，會翻譯成原始架構一開始也如你提供的連結所說明，作業系統裡面稱呼 read, write, wait 這類最基礎的架構為 primitive。看過你的想法，這邊是需要呼應前面幾項動作，如果單單稱為原始基礎架構有點上文不接下文。如果這樣呢：`以及其他相關的原始（primitives）的作業系統操作`，一樣保留 primitives 但作業系統操作就是我們翻譯者解釋 primitives 這個關鍵詞？

2018-07-19 04:50 UTC, chairco commented
拍謝啦，知道有計劃性，但是想說最近很常用到 asyncio 乾脆一邊查文件一邊翻譯好惹，算是一種現學現賣？？好想 cue TP 喔喔喔喔喔，疑？

2018-07-19 04:50 UTC, chairco commented on library/asyncio.po
> +"撰寫並發（concurrent）的程式碼，並使用多路復用 I/O（multiplexing I/O）方式來"
已修正

2018-07-19 04:50 UTC, chairco commented on library/asyncio.po
> +"Asyncio 模組提供一個在單一線程（single-threaded）內使用協同程序（coroutines）"
已修正

2018-07-19 04:50 UTC, chairco commented on library/asyncio.po
> +msgstr ":mod:`asyncio` — 非同步 I/O、事件迴圈、協同程序與任務"
已修正

2018-08-02 09:19 UTC, adrianliaw requested changes
@chairco 再麻煩你囉 🙏

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"``Asyncio`` 模組提供一個在單一線程（single-threaded）內使用協同程序"
inline literal 裡面的 asyncio 應該要小寫喔，因為是 module 的名稱

s/線程/執行緒/g （記得改掉後面其他的「線程」

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"（coroutines）撰寫並發（concurrent）的程式碼、並使用多路複用 I/"
s/並使用/使用/

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"O（multiplexing I/O）方式來連接 socket 與其他的資源、運作在網路客戶端與伺服器"
s/運作在/執行/
s/客戶端/用戶端/ （客戶端好像是中國的翻譯，台灣好像比較說用戶端
s/伺服器端/伺服器/ （大部分的翻譯好像都是寫「用戶端-伺服器」[1]

[1] https://zh.wikipedia.org/wiki/%E4%B8%BB%E5%BE%9E%E5%BC%8F%E6%9E%B6%E6%A7%8B

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"端以及其他相關的原始（primitives）的作業系統操作。以下列表包含著更多的套件的"
這邊的最後一個「以及」宜效仿原文在前面加上逗號，因為原文這樣逗開的意思應該是 "writing .... using coroutines", "multiplexing .... and other resources", "runnig .... and servers", "and other related primitives"

另外，我更正一下上一輪的 review，我其實也不確定這邊的 primitives 是不是指 OS primitives（如果你確定的話就保持這個翻譯吧），但是在原文沒有指出的情形下我會偏好直接逐字翻成「其他相關的原始操作（primitives）」

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"一個可插入的\\ :ref:`事件循環 <asyncio-event-loop>`\\ 實現於各類特定的系統;"
這邊的 "implementations" 是個名詞，翻成動詞的「實現」會有點怪，"implementation" 應該翻譯成「實作」，可以作名詞用。也許可以翻譯成「有各類特定系統的實作」

另外，這一排句子最後面的分號宜用全形分號，原文裡面的分號就真的是語意上分號的意思

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"能具體的支援 TCP、UDP、SSL、副流程管道（subprocess pipes）、延遲呼叫及其他"
s/具體的/具體地/

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"相似於\\  :mod:`concurrent.futures`\\  的模組並實現\\  :class:`Future`\\  類"
如果前後原本就有空格，就不需要用「沒有寬度的分隔符號」來保障 rST 語法，這邊可以把多餘的 <code>\\&nbsp;</code> 去除掉

另外，這一句的主詞應該是 <code>:class:\`Future\`</code>，整句應該要圍繞在 "asyncio 裡面的 Future"，而不是 concurrent.futures（目前語意上是圍繞在「相似於 concurrent.futures 的模組」）

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"協同程序與任務是基於\\  ``yield from``\\（\\ :PEP:`380`\\ ），來協助以同步方"
這邊的 "to help" 比較像是「以便 ......」的意思。

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +msgstr "取消支持\\  :class:`Future`\\s 與協同程序;"
支援 Future 與協同程序的取消

(cancellation support - N.) (for - prep.) (Futures and coroutines - N.)

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"程序（coroutines）與任務（ tasks）"
tasks 前面多了一個空格

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +":mod:`asyncio` — 非同步 I/O（Asynchronous I/O）、事件迴圈（event loop）、協同"
asynchronous 應該小寫，它不是專名

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +msgstr "**原始碼：** :source:`Lib/asyncio/`"
全形冒號後面不應該有空格，應該用「沒有寬度的分隔符號」

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"類似\\  :mod:`threading`\\  模組\\  :ref:`同步處理原語（synchronization "
「類似 threading 模組」後面宜加逗點，才能強調「同步處理原語」是主詞。

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"primitives） <asyncio-sync>`\\  用於單一線程的協同程序;"
原文中有 "between" coroutines，譯文中應該要加上「之間」，「用於單一執行緒的協同程序之間」，這樣比較能正確表達原文的意思

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"一個用來將工作傳遞到線程池的介面，當某些時候你必須得去呼叫與使用一個會造成阻"
這兩個句子應該前後對調比較順，「當某些時候 .... 的函式庫時，此模組有一個用來將工作 .... 的介面」

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"非同步程式設計與傳統的”同步（sequential）”程式設計相較起來更為複雜：請參見"
請使用中文的引號

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +"debug-mode>`\\ 可用來檢查常見問題。"
s/可用來檢查常見問題/可以偵測常見問題/

2018-08-02 09:19 UTC, adrianliaw commented on library/asyncio.po
> +":mod:`asyncio` 模組是根據\\  :PEP:`3156`\\  所設計。基本的傳輸與協議等動機請"
s/協議/協定/

2021-11-22 09:19 UTC, mattwang44 commented
I'll take over this PR.

- [ ] rebase to 3.10 and resolve conflict or fuzzy entries.
- [ ] update based on existing review comments.
- [ ] review translated content.

2021-12-13 00:03 UTC, adrianliaw commented on library/asyncio.po
> +"protocols>`\\ 來實現高效能協定；"
s/實現/實作

2021-12-13 00:03 UTC, adrianliaw commented on library/asyncio.po
> +msgstr "控制\\ :ref:`子程序 (subprocess) <asyncio-subprocess>`；"
這個子程序漏掉了～～

2021-12-13 00:03 UTC, adrianliaw commented on library/asyncio.po
> +"用於\\ :meth:`網路 <loop.create_server>`\\ 、執行\\ :meth:`子程序 <loop."
這邊也是

2021-12-13 07:29 UTC, mattwang44 commented on library/asyncio.po
> +"protocols>`\\ 來實現高效能協定；"
fixed

2021-12-13 07:29 UTC, mattwang44 commented on library/asyncio.po
> +msgstr "控制\\ :ref:`子程序 (subprocess) <asyncio-subprocess>`；"
fixed

2021-12-13 07:29 UTC, mattwang44 commented on library/asyncio.po
> +"用於\\ :meth:`網路 <loop.create_server>`\\ 、執行\\ :meth:`子程序 <loop."
fixed

2021-12-14 08:53 UTC, adrianliaw approved these changes
:pray:

2021-12-14 09:33 UTC, merged