Translate `library/asyncio-llapi-index.po`
python/python-docs-zh-tw pull request #227
Opened 2022-02-07 06:25 UTC by mattwang44

resolve #226 

preview:

![image](https://user-images.githubusercontent.com/24987826/152735494-9c7c1991-6b08-4afa-9a23-4b1c93ffdb1e.png)

2022-02-07 06:32 UTC, mattwang44 commented on library/asyncio-llapi-index.po
> +msgstr "回傳當前行程域中的 Policy。"
could have better translation for the term `process-wide`?

2022-02-07 06:36 UTC, mattwang44 commented on library/asyncio-llapi-index.po
> +msgstr "事件迴圈 Policies"
Since it's a special term in Python asyncio like `Future` and `Task`, the term `policy` is maintained (not translated).

2022-02-08 08:00 UTC, josix commented on library/asyncio-llapi-index.po
> +msgstr "回傳當前行程域中的 Policy。"
Will it translated to `整個行程` be better?

2022-02-08 19:37 UTC, josix requested changes

2022-02-08 19:37 UTC, josix commented on library/asyncio-llapi-index.po
> +msgstr "一直運行事件迴圈。"
```suggestion
msgstr "持續運行事件迴圈。"
```

2022-02-08 19:37 UTC, josix commented on library/asyncio-llapi-index.po
> +msgstr "獲取當前偵錯模式。"
這邊需再討論是否 debug 統一翻譯為`除錯`或 `偵錯`
```suggestion
msgstr "獲取當前除錯模式。"
```

2022-02-08 19:37 UTC, josix commented on library/asyncio-llapi-index.po
> +msgstr "為回呼函式排程"
```suggestion
msgstr "為回呼函式（Callbacks）排程"
```

2022-02-08 19:37 UTC, josix commented on library/asyncio-llapi-index.po
> +msgstr "儘快呼叫回呼函式 (callback)。"
nit. invoke 似乎比較常翻譯為`調用`
```suggestion
msgstr "儘快調用回呼函式 (callback)。"
```

2022-02-08 19:37 UTC, josix commented on library/asyncio-llapi-index.po
> +msgstr "在連線丟失或被關閉時被呼叫。"
```suggestion
msgstr "在失去連線或連線關閉時被呼叫。"
```

2022-02-08 19:37 UTC, josix commented on library/asyncio-llapi-index.po
> +msgstr "在給定時間\\ *之後*\\ 呼叫回呼函式。"
```suggestion
msgstr "在給定時間\\ *之後*\\ 調用回呼函式。"
```

2022-02-08 19:37 UTC, josix commented on library/asyncio-llapi-index.po
> +msgstr "在給定時間\\ *當下*\\ 呼叫回呼函式。"
```suggestion
msgstr "在給定時間\\ *當下*\\ 調用回呼函式。"
```

2022-02-09 03:21 UTC, mattwang44 commented on library/asyncio-llapi-index.po
> +msgstr "獲取當前偵錯模式。"
我來改成「除錯」好了，感覺比較貼近原意

2022-02-09 03:24 UTC, mattwang44 commented on library/asyncio-llapi-index.po
> +msgstr "為回呼函式排程"
這條 string 是某個段落的標題，所以我就沒有在這邊附註原文（標記 callback 原文處是 `asyncio-llapi-index.rst:87`）

2022-02-09 05:02 UTC, josix commented on library/asyncio-llapi-index.po
> +msgstr "為回呼函式排程"
Got it!

2022-02-09 05:02 UTC, josix approved these changes
LGTM! Thanks @mattwang44.

2022-02-09 05:02 UTC, merged