translated_v01
python/python-docs-zh-tw pull request #25
Opened 2018-07-23 18:19 UTC by cypevan

數學標示部份不是很確定。rST 半形還是全形請協助校對，感謝。

2018-07-24 10:47 UTC, adrianliaw requested changes
非常感謝你的幫忙！✨我目前還 review 到一半，不過有一些需要修改的地方是 rST 語法或是通暢的問題，要再麻煩你把這個翻譯文件裡其他相似的地方也修改一下了。感謝！如果有不確定的可以透過 GitHub 留言或是在 Telegram 敲我

2018-07-24 10:47 UTC, adrianliaw commented on tutorial/floatingpoint.po
> +"浮點數，在電腦以基數為 2（binary）分數來表示。舉例說明，在十進位分數：\n"
這邊括弧中的內容也可以翻譯（就是把括弧中的 binary 寫成「二進位」）

2018-07-24 10:47 UTC, adrianliaw commented on tutorial/floatingpoint.po
> +"::"
依照 rST 語法的規則 [1]，這兩個冒號應該要寫成

```rst
十進位分數：

::
```

或是

```rst
十進位分數： ::
```

請注意前者的中間有一個空行，後者的全形冒號和兩個半形冒號之間有空格。不然 rST 會認不得，要再麻煩改掉後面所有同樣的情況了！

[1] http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#literal-blocks

2018-07-24 10:47 UTC, adrianliaw commented on tutorial/floatingpoint.po
> +"如 1/10 + 2/100 + 5/1000 以二進位分數方式表示為：\n"
請注意這幾個段落其實是一段話，中間夾雜一些程式碼（程式碼沒有在 po 檔裡），請參考原文 [2] 的先後順序，有助於讓產生出的中文翻譯語意上能把整個段落串起來

[2] https://docs.python.org/3/tutorial/floatingpoint.html

2018-07-24 10:47 UTC, adrianliaw commented on tutorial/floatingpoint.po
> +"0/2 + 0/4 + 1/8。  這兩種分數具有相同數值，唯一差別為第一種標記法是十進位分"
句點後有多餘的空格，英文裡面空兩格算是英文的書寫習慣，中文的話全形標點符號不需要有前後空格

2018-07-24 10:47 UTC, adrianliaw commented on tutorial/floatingpoint.po
> +"的情況是，當您輸入十進位的浮點數值，計算機將轉換為近似的二進位浮點數值儲存。"
s/近似/逼近/ （似乎比較常聽到用「逼近」這個字，雖然近似也可以用，我是覺得「近似」比較是形容詞，而「逼近」是個動詞

2018-07-24 10:47 UTC, adrianliaw commented on tutorial/floatingpoint.po
> +msgstr "只能得到近似值："
這一句比較麻煩的是，這一句在原文中出現兩次（請參考上面的原文連結），因此可能需要修改一下避免產生出來的文件會重複兩次「只能得到近似值」：

<img width="824" alt="screen shot 2018-07-24 at 18 41 23" src="https://user-images.githubusercontent.com/2776892/43133399-35b1a77c-8f71-11e8-8c01-a52bce4807b1.png">

另外，這邊似乎沒有保留原文的雙冒號語法

2018-07-24 10:47 UTC, adrianliaw commented on tutorial/floatingpoint.po
> +"數值 1/10 說明，二進制分數表示為 \" 3602879701896397 / 2 ** 55 \"，其接近但不"
原文這邊的 <code>\`\`3602879701896397 / 2 ** 55\`\`</code> 是一個 rST 的 inline literal 語法 [3]，是用兩個 backtick <code>``</code> 來表示，而不是一個 double-quote

[3] http://docutils.sourceforge.net/docs/user/rst/quickref.html#inline-markup

2021-10-26 08:20 UTC, mattwang44 commented
see #89

2021-10-26 08:20 UTC, closed without merging