Translating tutorial/module
python/python-docs-zh-tw pull request #28
Opened 2018-08-27 06:16 UTC by PatinaHo

目前翻譯到
- [ ] 6.1 More on Modules
- [ ]  6.1.1 Executing modules as scripts
- [ ]  6.1.2 The Modules Search Path
- [ ]  6.1.3 "Compiled" Python files
6.2 / 6.3 / 6.4 的翻譯還在進行中。

2018-09-07 08:23 UTC, adrianliaw requested changes
感謝你的翻譯！✨這邊我雖然留了 51 個 code review，但其實大概 70% 都是空格的修正以及 rST 語法的修正，也有很多都是用詞上面的統一化等 [1]。如果有不知道怎麼改或是我說明不清楚的地方，請儘量在 GitHub 上留言或是在 Telegram 群組或是私訊問我。再麻煩你修改了！

[1] 關於空格的使用請參考翻譯守則： https://github.com/python/python-docs-zh-tw#id5

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"式實例中使用它們。這種檔案稱為\\ *模組（module）*\\ ；模組中的定義可以\\ *導"
我覺得 "interactive instance of the interpreter" 逐字翻會有點難懂，提議可以把「直譯器的互動式實例」改成「互動模式下的直譯器」，這樣如何？

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"入（import）*\\ 到其他模組中，或是導入至 \\ *主（main）*\\ 模組（即您在最頂"
"import" 這個詞應該以不翻譯為主（見[術語表](https://github.com/python/python-docs-zh-tw#glossary)），這邊的話我們可以寫成「import（導入）」，而後面所有使用到 import 一詞的地方我們可以直接寫 import。

另外，由於這邊的 import 是被動形式，所以應該要改成：模組中的定義可以「被」import 到其他模組中

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"層、計算機模式下執行的腳本中，所使用的變數集合）。"
我查了一下 "calculator mode" 這個用詞，看起來 calculator mode == interactive mode [1]，我覺得這樣的話翻譯裡就統一都用「互動模式」。

另外這邊語意和原文有點不太一樣，整句剖析下來應該是：

(the collection of variables that you have access to) ([in a script executed at the top level] and [in calculator mode])

所以這邊的斷句會需要修改一下。

[1] https://stackoverflow.com/questions/39240325/what-is-calculator-mode

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"模組是指包含 Python 定義和語句的檔案，檔案名稱是模組名稱的字尾加上\\ :file:‘."
「的字尾」在這邊應該是不需要的，因為 "suffix" 是指檔案名稱的 suffix 而不是模組名稱的字尾，這邊我覺得直接把「的字尾」拿掉就和原文的意思一樣了。

另外，這邊的 rST 語法是 <code>:file:\`.py\`</code>，是 backtick 而不是 single quote。（我上次用 PoEdit 的時候它好像會自己換掉，如果你是遇到這個狀況的話請跟我說！）

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"py’\\ 。在模組中，模組的名稱（作為字串）可用作全域變數\\ ``__name__``\\ 的"
s/可用作/會是/

另外，這邊句子中的 __name__ 算是一個中英混雜的狀況，因此前後應該要有實際的空格。這樣的情況下，就不需要在 <code>\`\`\_\_name\_\_\`\`</code> 的前後加上倒斜線

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"現在進入 Python 直譯器並用以下命令導入這個模組：\n"
s/命令/指令/g （請將後面所有的「命令」換成「指令」）
s/導入/import/g （請將後面所有的「導入」換成 import，除非真的是字面上「導入」的意思）

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"``fibo``\\ 的模組名稱。使用此模組名稱，就可以訪問函數：\n"
s/訪問/存取/

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"這並不會將\\ ``fibo``\\ 中定義的函數名稱直接輸入當前的符號表中；它只會輸入\\ "
s/函數/函式/g （請記得把後面所有的函數改成函式，感謝！）

另外這邊的兩個 fibo 前後都應該要有實質的空格，不需要加上倒斜線。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"如果您打算經常使用其中某個函數，可以將其指定至區域名稱：\n"
雖然這邊原文是寫 local name，但意思應該比較像「區域變數」，寫成區域變數也比較符合常用的中文術語。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"\\ *第一次*\\ 執行模組的導入語句時執行。[#]_（如果檔案被當成腳本執行，也會執"
如果說「它們只會在第一次被 import 時才會執行」，這樣好像會比較簡單

另外 `[#]_` 這個是 rST 的 footnote 語法，前後也會需要加上「沒有寬度的分隔符號」

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"式取用模組的全域變數，以相同的符號引用函數，\\ ``modname. itemname``\\ 。"
「以相同的符號引用函數」應翻譯為「以和引用函式一樣的寫法」。

另外 `modname.itemname` 的中間不應該有空格。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"在一個模組中可以導入其他模組。把所有的\\ :keyword: `import`\\ 語句放在模組"
這邊的 `:keyword:` 和 <code>\`import\`</code> 之間不應該有空格。另外這邊前後也需要實際的空格，不需要加上倒斜線。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"（就這邊來說，腳本也是一樣）的最開頭是個慣例，但並沒有強制。 被導入的模組名稱"
句點後面有多餘的空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"值。例如，用您喜歡的文字編輯器在資料夾中創一個名為\\ :file:`fibo.py`\\ 的檔"
fibo.py 如同上一個 comment

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"\\ :keyword: `import`\\ 語句有另一種變形寫法，可以直接將名稱從欲導入的模組，"
keyword 和 import 之間不應該有空格，另外 import 的後面應該要有實質的空格，不需要加上倒斜線，不過前面的倒斜線可以拿掉沒關係，因為是句子的開頭，開頭不應該有空格。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"號表中（因此，示例中的\\ ``fibo``\\ 未被定義）。"
fibo 前後不應該有倒斜線

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"情況下，Python 程式設計師不大使用這種名稱，因為它在直譯器中引入了一組未知的名"
這邊的 facility 指的是 `from ... import *` （這個的確是 Python 的一個非常不好的 bad practice），而不是以底線開頭命名。因此，「這種名稱」應該改成「這個功能」會比較好。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"稱，並且可能隱藏了某些您已經定義的內容。"
比起「隱藏」，我覺得「覆蓋」會是一個更貼切的用詞。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"請注意，一般情況下並不建議從模組或套件中導入\\ ``*``\\ 的做法，因為它通常會導"
這邊的星號前後應該要有實際的空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"致可讀性較差的程式碼。但若是使用它來保存互動式會話中的鍵入動作，則是可以接受"
s/保存互動式會話中的鍵入動作/在互動模式中節省打字時間/

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"如果模組名稱後面出現\\ :keyword: `as`\\ ，則\\ :keyword: `as`\\ 之後的名稱將"
keyword 和 as 之間不應該有空格。另外除了逗號前面的那一個分隔符號，前後都應該要有實質的空格。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"這個導入方式和\\ ``import fibo``\\ 同樣有效，唯一的差別是現在要用\\ ``fib``"
這邊所有的倒斜線都應該拿掉。

另外，"effectively" 通常意思是「實質上」，所以「同樣有效」也許可以改成「實質上是一樣的」。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"在使用時也可用\\ :keyword:`from`\\ 獲得類似的效果：\n"
from 前後應該要有空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"出於效率原因，每個模組在每次和直譯器的對話（interpreter session）中僅會導入一"
"session" 這個字真的太難翻譯成中文了，直接保留原文用字吧，「每個直譯器 session」

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"次。因此，如果您更改了模組，則必須重啟直譯器 — 或者，如果只是一個要交互測試的"
中文的破折號應該占兩格。

「交互測試」聽起來有點像是某個專業術語XD 我覺得可以寫成「如果只是一個想要在互動模式下測試的模組」

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"模組，可以使用\\ :func:`importlib.reload`。例如：\\ ``import importlib; "
"importlib.reload" 之前應該要有空格。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +msgstr "以腳本執行模組"
這邊我覺得可以翻成「把模組當作腳本執行」

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"如同你的導入指令，模組中的代碼會被執行，但 “__name__” 設置為 “” __main__  "
s/如同你的導入指令/如同使用 import 指令/
s/代碼/程式碼/
s/設置為/被設為/

這邊應該要用兩個 backtick，如同原文。
另外也留意原文是寫 <code>\`\`"\_\_main\_\_"\`\`</code>，因此裡面的括弧不能被轉換（如果遇到 PoEdit 自動轉換的狀況請告訴我）

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"“”。 這意味著, 通過在模組的末尾添加以下代碼：\n"
這邊的句點後面有多的空格，另外逗點應使用全形逗點

s/通過/透過/
s/代碼/程式碼/

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"你可以選擇將檔案作為腳本使用或做為欲導入的模組使用，因為解析（parse）命令列的"
s/做為/作為/

另外這邊的意思是「同時」可以作為腳本也同時可以作為被 import 的模組，所以不應該用「或」。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"如果導入模組，則不會執行（”main” 區塊內的）程式碼：\n"
這邊不需要特地註明 main 區塊內，因為範例中的程式碼就只有 main 區塊

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"這通常是用來為模組提供方便的使用者介面，或者用於測試目的（運作測試套件時，以"
s/運作/執行/

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"導入一個名為\\ :mod:`spam`\\ 的模組時，直譯器首先會搜尋具有該名稱的內建模組。"
spam 前後應有空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"如果找不到，接下來會在變數\\ :data:`sys.path`:\\ 所給定的資料夾清單之中，搜尋"
sys.path 前後應有空格，另外 sys.path 後面有多一個冒號

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"一個名為\\ :file:`spam.py`:\\ 的檔案。\\ :data:`sys.path`:\\ 從這些位置開始進"
spam.py 前後應有空格，另外其後有多餘的冒號

sys.path 的前面那個分隔符號是必須的，因為前面是句點，但其後需要有一個實質的空格。另外 sys.path 後面也有多餘的冒號。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"\\ :envvar:`PYTHONPATH`\\ （一連串和 shell 變數\\ :envvar:`PATH`\\ 的語法相同"
<code>:envvar:\`PATH\`</code> 的前後應該要有實質的空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"初始化之後，Python 程式可以修改\\ :data:`sys.path`\\ 。執行中腳本的所在資料夾"
sys.path 的前面需要空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"個錯誤。 請參見\\ : ref: `tut-standardmodules`\\ 以瞭解更多資訊。"
這邊的句點後面多了一個空格，另外這個 rST 語法彼此之間不能有空格，不然會產生不出對應的連結。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"為了加快載入模組的速度，Python 將每個模組的編譯版本緩存 \\ ``__pycache__``\\ "
\_\_pycache\_\_ 前後應該要有空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"資料夾下，並命名為\\ :file:`module.{version}.pyc`\\ ，此編譯版本是將編譯後的"
module 之前要有實質的空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"檔案格式進行編碼，且名稱通常會包含 Python 的版本邊號。 例如，在 CPython 3.3 "
我想 "where the version encodes the format of the compiled file" 的意思是，前面那個字串（`module.{version}.pyc`）裡面的 "version" 是編譯後的檔案的格式名稱。會這樣講是因為不同的 CPython 版本可能會編譯出不一樣的 bytecode，而只有對應版本的 Python 直譯器（精確來說是 Python virtual machine）讀得懂那個 bytecode（也就是那個編譯完的檔案）。

另外「例如」前面有多餘的空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"完全自動的過程。另外，編譯後的模組獨立於平台，因此不同體系結構的系統之間可以"
「不同體系結構的系統」如果改成「不同架構的作業系統」也許會比較順一點？

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"的模組的結果。 第二，如果沒有源模組，則不會檢查緩存。要支援非源模組（僅編譯）"
句點後有多餘的空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"可以在 Python 命令上使用命令參數（switch）\\ :option:`-O`\\ 或\\ :option:`-"
除了 switch 以及右括弧和 -O 之間應保持現在的樣子之外，-O 後面需要有空格，-OO 前後也都需要空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"OO`\\ 來減小已編譯模組的大小。命令參數\\ ``-O``\\ 刪除 assert 語句，\\ ``OO``"
-O 後面要有空格

這邊最後面的 OO 前面少了一個減號，另外它後面要有空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"\\ 同時刪除 assert 語句和 __doc__ 字串。由於某些程式本身可能已經很依賴於可用"
"Since some programs may rely on having these available" 這句的意思應該是「由於有些程式可能依賴於上述這些內容」（即 assert 和  doc strings）

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"這些選項，因此只有在您知道自己在做什麼時，才應使用此選項。 「已優化"
s/選項/參數/

句點後面有多餘的空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"（Optimized）」模組有\\ ``opt-``\\ 標記，且通常較小。未來的版本可能會改變優化"
opt- 前後應該有空格

另外，我覺得這邊這個 "Optimized" 並不是個專業術語，在原文裡使用引號也只是因為它「嚴格來說」是優化，但實質上只是把 assert 拿掉而已，並不是真的對計算效率上的改善。

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +"讀取\\ ``. pyc``\\ 檔案時，程式的執行速度並不會比讀取\\ ``. py``\\ 檔案快。唯"
.pyc 以及 .py 前後應該要有空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +msgstr "模組\\ : mod: `compileall`\\ 可以為資料夾中的所有模組創建 .pyc 檔。"
這邊的 rST 語法需要中間沒有任何空格才能正確產生連結，另外 compileall 前後都應該有空格

2018-09-07 08:23 UTC, adrianliaw commented on tutorial/modules.po
> +msgstr "更多的細節，包括決策流程圖，請參考\\ :pep: `3147`\\ 。"
這邊的 rST 語法需要中間沒有任何空格，另外 pep 3147 的前面應該要有實質空格

2021-05-21 08:05 UTC, StevenHsuYL commented
I will continue from this commit, revise and complete it.
Thanks for your work previously.

2021-10-26 08:33 UTC, mattwang44 commented
closed by #72

2021-10-26 08:33 UTC, closed without merging