Translate tutorial/controlflow.po
python/python-docs-zh-tw pull request #283
Opened 2022-06-09 00:50 UTC by StevenHsuYL

Complete ``match`` statement part in controlflow.po

Any suggestion would be welcomed. Thanks for the review!

Reference: [pattern](https://terms.naer.edu.tw/search/?q=pattern&field=ti&op=AND&match=full&q=&field=ti&op=AND&q=noun%3A%22%E9%9B%BB%E5%AD%90%E8%A8%88%E7%AE%97%E6%A9%9F%E5%90%8D%E8%A9%9E%22&field=&op=AND&order=&num=10&show=&page=10&group=&heading=#result), [guard](https://terms.naer.edu.tw/search/?q=guard&field=ti&op=AND&match=full&q=&field=ti&op=AND&q=noun%3A%22%E9%9B%BB%E5%AD%90%E8%A8%88%E7%AE%97%E6%A9%9F%E5%90%8D%E8%A9%9E%22&field=&op=AND&order=&num=10&show=&page=10&group=&heading=#result).

2022-06-09 01:28 UTC, ezio-melotti commented on tutorial/controlflow.po
> +"關於更詳細的解釋和其他範例，你可以閱讀 :pep:`636`\\ ，它是以教學的格式編寫而"
```suggestion
"關於更詳細的解釋和其他範例，你可以閱讀 :pep:`636`，它是以教學的格式編寫而"
```

2022-07-05 08:14 UTC, StevenHsuYL commented
Update ``match`` section.

Preview:
![controlflow match](https://user-images.githubusercontent.com/81967953/177282103-7173e48b-6f8f-4fb1-aeca-1a2d6e720dd0.jpeg)

2022-07-05 18:37 UTC, mattwang44 commented
commit history 有點嚇人XD 好像包含到一些非關 controlflow 的改動
@StevenHsuYL 可以幫忙 rebase 一下嗎 🙏🏽

2022-07-06 01:15 UTC, StevenHsuYL commented
已修復 ^^"
會變這樣好像是因為上週 CPython 有更新此檔，我 merge ``3.10`` branch 更新原文檔，
之後就跑出一大堆 commit history...
目前已還原到只有更改 tutorial/controlflow.po，再麻煩確認，謝謝！

2022-07-06 16:59 UTC, mattwang44 commented
我有再整理了一下，現在應該是只留下需要的 commit 
會再找時間 review 🙏🏽

2022-07-23 05:44 UTC, mattwang44 requested changes

2022-07-23 05:44 UTC, mattwang44 commented on tutorial/controlflow.po
> +":keyword:`match` 陳述式會拿取一個運算式，並將其值與多個連續的型樣 (pattern) "
還是比較希望 pattern 被翻成「模式」，感覺比較口語化？

2022-07-23 05:44 UTC, mattwang44 commented on tutorial/controlflow.po
> +"請注意最後一段：「變數名稱」\\ ``_`` 是作為\\ *通用字元*\\ 的角色，且永遠不會"
補一下原文好了

```suggestion
"請注意最後一段：「變數名稱」\\ ``_`` 是作為\\ *通用字元 (wildcard)*\\ 的角色，且永遠不會"
```

2022-07-23 05:44 UTC, mattwang44 commented on tutorial/controlflow.po
> +"延伸。但是接下來的兩個型樣結合了一個字面值和一個變數，且該變數\\ *連結*\\ 了"
nit: 既有翻譯大多譯作「繫結」
```suggestion
"延伸。但是接下來的兩個型樣結合了一個字面值和一個變數，且該變數\\ *繫結 (bind)*\\ 了"
```

2022-07-23 05:44 UTC, mattwang44 commented on tutorial/controlflow.po
> +"``__match_args__``，來定義型樣中屬性們的特定位置。如果它被設定為 (“x”, “y”)，"
```suggestion
"``__match_args__``，來定義型樣中屬性們的特定位置。如果它被設定為 (\"x\", \"y\")，"
```

2022-07-23 05:44 UTC, mattwang44 commented on tutorial/controlflow.po
> +"``True``\\ 、\\ ``False`` 和 ``None`` 是藉由身份 (identity) 來比較。"
https://docs.python.org/zh-tw/3/library/functions.html#id

```suggestion
"``True``\\ 、\\ ``False`` 和 ``None`` 是藉由標識值 (identity) 來比較。"
```

2022-07-24 07:21 UTC, mattwang44 approved these changes

2022-07-24 07:21 UTC, merged