Translate faq/gui.po
python/python-docs-zh-tw pull request #292
Opened 2022-07-02 09:51 UTC by StevenHsuYL

Complete translation of faq/gui.po.

Thanks for the review.

HTML preview:
![faq-gui](https://user-images.githubusercontent.com/81967953/176995425-ea0a6aa9-22b6-4a4d-bc2d-36ad66fc35e4.jpeg)

2022-07-05 19:40 UTC, mattwang44 requested changes

2022-07-05 19:40 UTC, mattwang44 commented on faq/gui.po
> +msgstr "一般的圖形使用者介面 (GUI) 問題"
```suggestion
msgstr "圖形使用者介面 (GUI) 的常見問題"
```

2022-07-05 19:40 UTC, mattwang44 commented on faq/gui.po
> +"數\\ `二進位發行版本 <https://www.python.org/downloads/>`_\\ 中）和使用的。有"
```suggestion
"數\\ `二進制發行版本 <https://www.python.org/downloads/>`_\\ 中）和使用的。有"
```

2022-07-05 19:40 UTC, mattwang44 commented on faq/gui.po
> +"一種解決方法，是將應用程式與 Tcl 和 Tk 函式庫一起提供，並在運行時使用 :"
```suggestion
"將應用程式與 Tcl 和 Tk 函式庫一併發送是一種解決方法，並在運行時使用 :"
```

2022-07-05 19:40 UTC, mattwang44 commented on faq/gui.po
> +"在 Windows 以外的平台上，是可以的，你甚至不需要執行緒！但是，你必須稍微調整你"
```suggestion
"在 Windows 以外的平台上是可以的，你甚至不需要執行緒！但是，你必須稍微調整你"
```

2022-07-05 19:40 UTC, mattwang44 commented on faq/gui.po
> +"以進行時，該函式將會從 Tk mainloop 被呼叫。請參閱\\ :ref:`tkinter-file-"
```suggestion
"你記錄一個回呼 (callback) 函式，當 I/O 在一個檔案描述符 (file descriptor) 上"
"可進行時，該函式將會從 Tk mainloop 被呼叫。請參閱\\ :ref:`tkinter-file-"
```

2022-07-05 19:40 UTC, mattwang44 commented on faq/gui.po
> +msgstr "我無法讓鍵連結 (key binding) 在 Tkinter 中作用：為什麼？"
```suggestion
msgstr "我無法讓鍵繫結 (key binding) 在 Tkinter 中作用：為什麼？"
```

2022-07-05 19:40 UTC, mattwang44 commented on faq/gui.po
> +"一個經常聽到的抱怨是，儘管事件處理程式 (event handler) 已經連結到帶有 :meth:"
```suggestion
"一個經常聽到的抱怨是，儘管事件處理程式 (event handler) 已經繫結到帶有 :meth:"
```

2022-07-05 19:40 UTC, mattwang44 commented on faq/gui.po
>  #~ msgid "Qt"
以下可以刪除了

2022-07-05 19:40 UTC, mattwang44 commented on faq/gui.po
> +"最常見的原因是，該連結所應用的小工具並沒有「鍵盤焦點」。請查看 Tk 說明文件中"
```suggestion
"最常見的原因是，繫結到的小工具並沒有「鍵盤焦點 (keyboard focus)」。請查看 Tk 說明文件中"
```

2022-07-06 00:53 UTC, StevenHsuYL commented on faq/gui.po
>  #~ msgid "Qt"
All suggestions were applied. 
Thanks for the review! :smile:

2022-07-06 11:31 UTC, mattwang44 approved these changes
LGTM!

2022-07-06 11:31 UTC, merged