Translate `library/graphlib.po`
python/python-docs-zh-tw pull request #374
Opened 2023-01-04 15:57 UTC by mattwang44

resolve #373 

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/24987826/210596047-3954dbd0-e048-4e80-975a-496adf2f25b5.png">

2023-02-28 06:30 UTC, mattwang44 commented on library/graphlib.po
> +"提供對包含可雜湊 (hashable) 節點之圖 (graph) 進行拓撲排序 (topologically "
```suggestion
"提供對包含\\ :term:`可雜湊 (hashable) <hashable>` 節點之圖 (graph) 進行拓撲排序 (topologically "
```

2023-02-28 06:30 UTC, mattwang44 commented on library/graphlib.po
> +"雜湊的。"
```suggestion
"向圖中新增新節點及其前驅節點。*node* 和 *predecessors* 中的所有元素都必須是\\ :term:`可雜湊 <hashable>`\\ "
"的。"
```

2023-03-01 04:10 UTC, josix requested changes

2023-03-01 04:10 UTC, josix commented on library/graphlib.po
> +":exc:`ValueError` 的子類別，如果作用的圖中有循環的存在則由 :meth:"
**issue:** 
```suggestion
":exc:`ValueError` 的子類別，如果作用的圖中存在循環則由 :meth:"
```

2023-03-01 04:10 UTC, josix commented on library/graphlib.po
> +"該類別旨在簡單支援節點準備就緒時的平行處理。例如：\n"
**issue:** 
```suggestion
"該類別設計為在節點準備就緒時，簡單支援節點的平行處理。例如：\n"
```

2023-03-01 06:22 UTC, josix approved these changes
LGTM!

2023-03-01 06:22 UTC, merged