translate the module description of archiving
python/python-docs-zh-tw pull request #391
Opened 2023-01-29 14:48 UTC by Kuo-TingKai

2023-01-29 15:02 UTC, Kuo-TingKai commented
我剛剛在本地端瀏覽library/archiving的靜態頁面時，意外發現`shutils`頁面跟`Archiving operations`頁面的超連結點開後頁面左右欄布局都會出現問題，如圖所示:
![image](https://user-images.githubusercontent.com/13663890/215334765-3b7020e9-ca4f-4d45-9c1a-35319a5faec2.png)

後來發現只要是左邊欄位出現太長的字串的頁面都會有類似問題。
由於我對前端樣式沒那麼熟，不知道要如何改進。

2023-01-29 15:45 UTC, mattwang44 requested changes
可以修正幾個偏向簡中用法的詞彙

2023-01-29 15:45 UTC, mattwang44 commented on library/archiving.po
> +"創建 ZIP 和 tar 格式的存檔。另請參閱 :mod:`shutil` 模塊提供的 :ref:"
```suggestion
"建立 ZIP 和 tar 格式的存檔。另請參閱 :mod:`shutil` 模組提供的 :ref:"

```

2023-01-29 15:45 UTC, mattwang44 commented on library/archiving.po
> +"本章中描述的模組支持使用 zlib、gzip、bzip2 和 lzma 演算法進行資料壓縮，以及"
```suggestion
"本章中描述的模組支援使用 zlib、gzip、bzip2 和 lzma 演算法進行資料壓縮，以及"

```

2023-01-29 17:59 UTC, mattwang44 commented
關於 local 頁面跑版，我自己 local build (mac) 是沒出現這個問題，但目前有個 GitHub action workflow 會把這個 repo 的最新翻譯內容 build 出來[用 github page serve](https://python.github.io/python-docs-zh-tw/library/shutil.html)，這個版本也是有這問題，應該是跟環境有關，但我還找不到問題在哪裡，我先開個 issue 紀錄，不過這個問題不影響翻譯內容、review 看翻譯內容 ok 就會 merge

2023-01-29 18:18 UTC, mattwang44 commented
btw 你用的換行符號好像是 Windows 用的 CRLF（用 git diff 看 CR 會顯示成 `^M`）、但 project 目前習慣用的是 *nix 的 LF，如果換行符號不同的話在 github review 頁面上就會顯示檔案中的每一行都有被變更過，不好看出被修正的地方，如果可以的話請你[更改一下 git 設定](https://stackoverflow.com/a/1889699)來讓你的檔案統一使用 LF。

<img width="718" alt="image" src="https://user-images.githubusercontent.com/24987826/215346708-df4a7aff-111b-4e22-bef2-eb3d3d89ef64.png">

2023-01-29 22:41 UTC, Kuo-TingKai commented
好的 感謝review 上述建議我有空更正一下！

2023-02-18 06:27 UTC, mattwang44 commented
已修正：`CRLF` -> `LF` 和 review comment 提到的問題

2023-02-18 06:27 UTC, merged