Translate howto/logging
python/python-docs-zh-tw pull request #408
Opened 2023-03-10 16:15 UTC by josix

2023-03-10 16:16 UTC, josix commented on howto/argparse.po
> +"Language: argparse\n"
**issue:** need to correct these two fields into original ones

2023-03-10 16:17 UTC, josix commented on howto/logging.po
> +"Language: logging\n"
**issue:** need to correct these two fields into original ones

2023-03-19 07:34 UTC, mattwang44 requested changes
review round 1

2023-03-19 07:34 UTC, mattwang44 commented on howto/argparse.po
> +msgstr "到目前為止，我們一直在玩位置參數。 讓我們看看如何添加可選的::"
```suggestion
msgstr "到目前為止，我們一直在使用位置引數。讓我們看看如何添加可選引數::"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"紀錄（Logging）提供方便使用的一組簡單紀錄函式。這些函式包括：:func:`debug`、:"
logging 相關翻譯還很少，logging 一詞目前多翻為「日誌」，但可以討論一下

```suggestion
"日誌（Logging）提供方便使用的一組簡單紀錄函式。這些函式包括：:func:`debug`、:"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"debug` （用於診斷目的的非常詳細的輸出））"
```suggestion
msgstr ":func:`logging.info` （或者在需要診斷用的詳細輸出時使用 :func:`logging."
"debug` ）"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +":func:`warnings.warn` 警告"
```suggestion
msgstr "如果問題是可以避免的，請在函式庫程式中使用 :func:`warnings.warn` "
"警告，並應修改客戶端應用程式來消除警告"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +msgstr "引發異常"
```suggestion
msgstr "引發例外"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +msgstr "報告錯誤但不引發異常（如長時間執行的伺服器進程中的錯誤處理程序）"
```suggestion
msgstr "報告錯誤的抑制 (suppression) 但不引發例外（如長時間執行的伺服器行程中的錯誤處理程序）"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"根據錯誤及應用領域的特定需要，使用 :func:`logging.error`、:func:`logging."
```suggestion
"根據特定錯誤及應用領域的需求來選擇使用 :func:`logging.error`、:func:`logging."
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +msgstr "日誌紀錄函數的命名方式是根據它們所用於追蹤的事件等級或嚴重程度。以下是標準等"
- logging 要統一用詞
- function 統一翻譯為「函式」

```suggestion
msgstr "日誌函數的命名方式是根據它們所用於追蹤的事件等級或嚴重程度。以下是標準等"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +msgstr "預設的級別是「警告」(``WARNING``)，這意味著除非配置記錄器套件進行其他設定，否"
```suggestion
msgstr "預設的級別是「警告」(``WARNING``)，這意味著除非為日誌套件配置其他設定，否"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"則隻會追蹤這個級別及以上的事件。"
```suggestion
"則隻會追蹤這個級別以上的事件。"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"制台。另一個常見的方法是將它們寫入磁盤文件。"
```suggestion
"制台。另一個常見的方法是將它們寫入磁碟文件中。"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +msgstr "將記錄寫入檔案"
```suggestion
msgstr "將日誌寫入檔案"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"這段訊息顯示在控制台上。由於預設級別為 WARNING，所以 INFO 訊息並未出現。"
```suggestion
"這段訊息顯示在控制台上。由於預設級別為 ``WARNING``，所以 ``INFO`` 訊息並未出現。"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"印出的訊息包含級別以及在 logging 呼叫中提供的事件說明，例如 'Watch out!'。"
```suggestion
"印出的訊息包含級別以及在日誌呼叫中提供的事件說明，例如 'Watch out!'。"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"目前不必擔心 'root' 部分，稍後將會說明。如果您需要的話，可以彈性地格式化實際"
```suggestion
"目前不必擔心 'root' 部分，稍後將會說明。如果有需要的話，可以彈性地格式化實際"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"一個非常普遍的情況是將記錄事件記錄在文件中，因此讓我們接下來來看看這個情況。"
```suggestion
"一個非常普遍的情況是將日誌事件記錄在文件中，因此讓我們接著看看這個情況。"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"請務必在新啟動的 Python 解譯器中嘗試以下操作，而不是繼續以上描述的會話：\n"
```suggestion
"請務必在新啟動的 Python 直譯器中嘗試以下操作，而不是繼續以上描述的會話：\n"
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"新增了 *encoding* 參數。在早期的 Python 版本中，如果未指定，將使用 "
```suggestion
"新增了 *encoding* 引數。在早期的 Python 版本中，如果未指定，將使用 "
```

2023-03-19 07:34 UTC, mattwang44 commented on howto/logging.po
> +"參數，以決定如何處理編碼錯誤，詳情請參閱 :func:`open` 的文件。"
```suggestion
"引數，以決定如何處理編碼錯誤。可用的值與其預設值，請參閱 :func:`open` 的文件。"
```

2023-03-19 11:55 UTC, josix commented on howto/logging.po
> +"紀錄（Logging）提供方便使用的一組簡單紀錄函式。這些函式包括：:func:`debug`、:"
我覺得可以先用日誌 (noun) ，logging 作為動作的話翻譯成記錄，當初翻的時候還沒統一，chatgpt 也沒有統一後續會再檢查一下

2023-03-19 11:57 UTC, mattwang44 commented on howto/logging.po
> +"紀錄（Logging）提供方便使用的一組簡單紀錄函式。這些函式包括：:func:`debug`、:"
Ok

2023-04-10 17:59 UTC, closed without merging