20230716 pathlib_1162_to_1279
python/python-docs-zh-tw pull request #479
Opened 2023-07-16 12:09 UTC by englam

20230716

2023-07-18 13:49 UTC, englam commented
20230718 Reopen PR

2023-07-18 13:52 UTC, cschan1828 commented on library/pathlib.po
> +msgstr "An :exc:`OSError` 如果任何一個文件因為一些原因不能被使用。"
建議：
若任何一個檔案因為某些原因無法存取，則引發 :exc:`OSError`。

2023-07-18 13:55 UTC, cschan1828 commented on library/pathlib.po
> +msgstr "參數的順序「連結，目標」是  :func:`os.symlink`'s 的保留。"
argument: 引數
parameter: 參數
reverse: 相反、反轉、倒轉

特殊符號與前個字留一個空格即可。

2023-07-18 13:59 UTC, cschan1828 commented on library/pathlib.po
> +"*target_is_directory*  應該為 true (default ``False``)  。如果在  POSIX   的"
- 中文與英文之間留一個空格即可。
- 專有名詞第一次出現時附上原文，例如 symbolic link，這通常譯為「符號連結」或者「軟連結」（相對於 hard link 而言）。

2023-07-18 14:01 UTC, cschan1828 commented on library/pathlib.po
> +msgstr "讓這個路徑的一個硬連結到相同的檔案如  *target* 。"
請再想看看，這語句並不是很通順。
同樣地，中文與英文之間留一個空格即可。

2023-07-18 14:06 UTC, cschan1828 requested changes
Congratulate you on your first commit! It is a significant milestone!

Noticed that some areas that can be improved with a little extra attention. Please have a look and improve the remaining parts to ensure the high quality of our shared work.

2023-07-18 14:08 UTC, cschan1828 commented
Additionally, I suggest you resolve the conflicts so that the CI checks can be enabled.

2023-07-18 14:47 UTC, mattwang44 commented on library/pathlib.po
> +msgstr "參數的順序「連結，目標」是  :func:`os.symlink`'s 的保留。"
`(link, target)` 應該不用翻

2023-07-27 05:58 UTC, mattwang44 reviewed
多餘的 empty line

2023-07-27 05:58 UTC, mattwang44 commented on library/pathlib.po
>  "Last-Translator: Adrian Liaw <adrianliaw2000@gmail.com>\n"
```suggestion
"PO-Revision-Date: 2023-07-16 19:10+0800\n"
"Last-Translator: Adrian Liaw <adrianliaw2000@gmail.com>\n"
```

2023-07-27 05:58 UTC, mattwang44 commented on library/pathlib.po
```suggestion
"X-Generator: Poedit 3.3.2\n"

```

2023-11-05 09:53 UTC, mattwang44 commented
嗨 @englam 
想請問你會繼續修這隻 PR 嗎？

2023-11-07 00:18 UTC, englam commented
啊 抱歉 可以先請你 請別人修復嗎 最近事情太多爆炸了

Wei-Hsiang (Matt) Wang ***@***.***>於 2023年11月5日 週日，17:53寫道：

> 嗨 @englam <https://github.com/englam>
> 想請問你會繼續修這隻 PR 嗎？
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/python/python-docs-zh-tw/pull/479#issuecomment-1793689098>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEJPRW7DH7HBR7MRI3KMN2LYC5OZVAVCNFSM6AAAAAA2L42ZBWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJTGY4DSMBZHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-09 13:19 UTC, mattwang44 approved these changes

2023-11-09 15:12 UTC, merged