[UPDATE] Translate `library/os.path`
python/python-docs-zh-tw pull request #492
Opened 2023-07-19 06:54 UTC by jacksonchen1998

#480 
有針對上次 review 做更改，包括：
- 函數」改為「函式」，文中仍有混用情形。
- 「返回」改為「回傳」，文中仍有混用情形。
- implement 請統一翻為「實作」，文中仍見「實作」與「實做」混用情形。
- call 的繁體中文翻譯為「呼叫」（參考：國家教育研究院樂詞網）。
- string 的繁體中文翻譯為「字串」（參考：國家教育研究院樂詞網），文中仍有部份地方為「字符串」。

目前維持原先「適用」的翻譯。Drive 目前暫翻驅動機，因為 drive letter (drive name) 在術語列表翻譯為驅動機字母 (驅動機名)

![image](https://github.com/python/python-docs-zh-tw/assets/56949000/156fda83-27d5-4116-92dc-8ccf7205ed90)

![image](https://github.com/python/python-docs-zh-tw/assets/56949000/0cbfb79e-2974-41a2-be21-c2cf2c89336b)

![image](https://github.com/python/python-docs-zh-tw/assets/56949000/f70ad833-7c99-4392-98db-a6f33c2684e0)

![image](https://github.com/python/python-docs-zh-tw/assets/56949000/6a2f43ed-c7ac-4efa-be44-44fa7c52d66e)

![image](https://github.com/python/python-docs-zh-tw/assets/56949000/9a6ace01-29d4-4055-8e6f-f06ba248eb10)

![image](https://github.com/python/python-docs-zh-tw/assets/56949000/5fa0ef54-5afe-43c0-bdf7-f41425b364d7)

![image](https://github.com/python/python-docs-zh-tw/assets/56949000/2b321b7f-402f-424a-9ed7-dd82ee134ad3)

![image](https://github.com/python/python-docs-zh-tw/assets/56949000/1e4b6243-4ddd-49af-9a65-8ff822669d29)

![image](https://github.com/python/python-docs-zh-tw/assets/56949000/e3c2e283-bf18-4097-adcf-fdbbc49f4231)

2023-07-19 22:29 UTC, cschan1828 reviewed
Thanks for your commit!

這次的翻譯有點多，我沒有每句都很仔細讀，可能會需要更多的時間 review。
先給個初步的回饋給你參考修正。

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"傳 ``True``。如果 Python 執行時不支持符號連結，則始終回傳 ``False``。"
前後一致，這邊請用「支援」。

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"如果路徑名 *path* 是一個掛載點 （:dfn:`mount point`），則回傳 ``True``。在 "
"A point in a file system ..." 這句似乎沒有翻譯到。

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"建置目錄、封包緩存和其他 I/O 密集型操作。"
cache 繁體中文一般譯為 「快取」，或者不翻譯。

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"com/windows/dev-drive/>`_\\ 以了解有關啟用和建立 Dev 驅動機的信息。"
document 繁體中文翻譯為「文件」
information 繁體中文翻譯為「資訊」

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"html#tag_04_13>`_ 標準，如果一個路徑名以確切的兩個斜線開頭，則在前導字元後的"
exactly two 為恰好兩個之意。

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"此函式模擬操作系統的使路徑規範化的程序，在處理連結和後續路徑部份之間，在 "
how links and subsequent path components interact. 這句是不是沒有翻完整？感覺語意不太通順

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"智能地連接一個或多個路徑段。回傳值是 *path* 和 *\\*paths* 的所有成員的串聯，"
```suggestion
"聰明地連接一個或多個路徑段。回傳值是 *path* 和 *\\*paths* 的所有成員的串聯，"
```

intelligent 在繁體中文一般翻譯成「智慧的」、「智慧型」、「有才智的」或「聰明的」。（來源：國家教育研究院樂詞網）

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +msgstr "操作系統的 API 會根據需要自動使路徑規範化，因此通常不需要呼叫此函式。"
canonical 一般翻譯成「正則」、「標準」或者「典型」。

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +msgstr "操作系統的 API 會根據需要自動使路徑規範化，因此通常不需要呼叫此函式。"
Operation system: 作業系統

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"回傳指定檔案名稱的規範路徑，消除路徑中遇到的所有符號連結（如果操作系統支"
operating system: 作業系統

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +msgstr "*start* 的默認值為 :attr:`os.curdir`。"
```suggestion
msgstr "*start* 的預設值為 :attr:`os.curdir`。"
```

default: 預設、內定、既定之意。

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"結的路徑的含義。在 Windows 上，它將正斜線轉換為反斜線。要規範化大小寫，請使"
normalize: 標準化

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"結的路徑的含義。在 Windows 上，它將正斜線轉換為反斜線。要規範化大小寫，請使"
```suggestion
"結的路徑的含義。在 Windows 上，它將正斜線轉換為反斜線。要標準化大小寫，請使"
```

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"如果路徑包含 UNC 路徑，則驅動機將包含主機名和共享名，不包括第四個分隔符："
原文沒有「不包括第四個分隔符」這句。
:: 是特殊符號，表示接下來會有 code block.

```suggestion
"如果路徑包含 UNC 路徑，則驅動機將包含主機名和共享名：\n"
"\n"
"::"
```

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"在 Windows 上，*drive* 可能為空，是驅動機名稱，UNC 共享或設備名稱。*root* 可"
```suggestion
"在 Windows 上，*drive* 可能為空、驅動機名稱、UNC 共享或是設備名稱。*root* 可"
```

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_13>`_ 的實現定義）。例"
```suggestion
"onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_13>`_ 的實作定義）。例"
```

2023-07-19 22:29 UTC, cschan1828 commented on library/os.path.po
> +"檔名 *ext* 為空或以點開頭且最多包含一個點。"
```suggestion
"檔名 *ext* 為空或以點開頭且最多包含一個點 (period)。"
```

「點」在中文上語意很多，建議附上原文讓讀者知道是指英文句子結尾的那個 "."。

2023-07-20 04:58 UTC, jacksonchen1998 commented
@cschan1828 Thanks. I have modified.

2023-07-20 15:11 UTC, cschan1828 commented on library/os.path.po
> +msgstr "如果路徑包含 UNC 路徑，則驅動機將包含主機名和共享名："
參考[rST 語法注意事項](https://github.com/python/python-docs-zh-tw#id29)最後一項，`::` 是rST特殊語法。

```suggestion
msgstr "如果路徑包含 UNC 路徑，則驅動機將包含主機名和共享名：\\n"
"\n"
"::"
```

2023-07-20 15:13 UTC, cschan1828 commented on library/os.path.po
> +"在 Windows 上，*drive* 可能為空、驅動機名稱，UNC 共享或設備名稱。*root* 可能"
```suggestion
"在 Windows 上，*drive* 可能為空、驅動機名稱、UNC 共享或設備名稱。*root* 可能"
```

2023-07-20 15:16 UTC, cschan1828 commented on library/os.path.po
> +"檔名 *ext* 為空或以點開頭且最多包含一個點（periord）。"
括號內是英文，則括號用半形，且與前一個中文字空一格。見[翻譯守則](https://github.com/python/python-docs-zh-tw#id27)第二項以及[括號的使用](https://github.com/python/python-docs-zh-tw#id28)。

```suggestion
"檔名 *ext* 為空或以點開頭且最多包含一個點 (period)。"
```

2023-07-20 15:20 UTC, cschan1828 requested changes
Thanks for your modification! I've reviewed it. You've made some nice improvements.
There is some minor feedback that needs your attention.

2023-07-20 15:29 UTC, cschan1828 commented
剛剛發現前面也有不少誤用中文全形括號的部份，請參考

- [翻譯守則](https://github.com/python/python-docs-zh-tw#id7) - 中英文交雜時要插入空白；符號英文間不用。
- [括號的使用](https://github.com/python/python-docs-zh-tw#id28) - 如果括號中的文字包含中文，使用全形括號；如果括號中只有英文，使用半形括號並比照英文的形式加入前後文的空白。

自行檢查與修正。

2023-07-20 15:34 UTC, cschan1828 commented on library/os.path.po
> +msgstr "如果路徑包含 UNC 路徑，則驅動機將包含主機名和共享名：\\n"
My bad. The first time suggestion I unexpectedly typed "\\n", the correct one is "\n".

```suggestion
msgstr "如果路徑包含 UNC 路徑，則驅動機將包含主機名和共享名：\n"
```

2023-07-20 15:38 UTC, cschan1828 commented on library/os.path.po
>  "basedefs/V1_chap04.html#tag_04_13>`_.) For example::"
ditto.

你可以在這個 repo 中找到許多類似範例，基本上就是
"：\n"
"\n"
"::"

這樣的模式。後續有 `::` 的部份我就不一一列出了，請自行找出並修正。

2023-07-21 04:56 UTC, jacksonchen1998 commented
@cschan1828 I have modified. Please check.

2023-07-22 09:15 UTC, cschan1828 commented on library/os.path.po
> +"斜線），否則從 *head* 中刪除尾部的斜線。在所有情況下，``join(head, tail)`` 返"
```suggestion
"斜線），否則從 *head* 中刪除尾部的斜線。在所有情況下，``join(head, tail)`` 回"
```

2023-07-22 09:15 UTC, cschan1828 commented on library/os.path.po
> +"回指向與 *path* 相同位置的路徑（但字串可能不同）。還可以參考函式 :func:"
```suggestion
"傳指向與 *path* 相同位置的路徑（但字串可能不同）。還可以參考函式 :func:"
```

2023-07-22 09:18 UTC, cschan1828 requested changes
Nice job done! Just request a small change then this commit is good to merge.

2023-07-22 09:19 UTC, cschan1828 commented
另外一個建議是，遇到 Python 內建的資料結構如 sequence, list, tuple 等，可以不必翻譯，直接比照原文即可。

2023-07-22 10:40 UTC, jacksonchen1998 commented
@cschan1828 OK. Thanks for your review.

2023-07-22 11:07 UTC, cschan1828 approved these changes
LGTM! Thank you for your efforts.

2023-07-22 11:07 UTC, merged