Translate CSV Module rst:71 to rst:152
python/python-docs-zh-tw pull request #582
Opened 2023-08-12 12:42 UTC by rockleona

#188 

![image](https://github.com/python/python-docs-zh-tw/assets/34214497/cc53d6e1-a08b-426b-978c-a6915382993b)
![image](https://github.com/python/python-docs-zh-tw/assets/34214497/ec360c76-b3fe-488e-a16f-9392cd0cbb58)

2023-08-12 15:15 UTC, rockleona commented
啊....是不是因為我共用前幾天的 PR 的 Branch 造成多個 commit .....@@

2023-08-13 13:20 UTC, mattwang44 commented
> 啊....是不是因為我共用前幾天的 PR 的 Branch 造成多個 commit .....@@

對歐，可以學一下 `git rebase` 指令怎麼使用，如果不確定怎麼做再請你找我討論 🙏🏽

2023-08-14 16:12 UTC, mattwang44 commented
@cschan1828 想請問最近有來幫忙 review 嗎？

2023-08-15 08:57 UTC, cschan1828 commented on library/csv.po
> +"具有 :func:`write` method 的任何物件。若 *csvfile* 為一個檔案物件，它應該使用"
```suggestion
"具有 :func:`write` 方法的任何物件。若 *csvfile* 為一個檔案物件，它應該使用"
```

2023-08-15 08:59 UTC, cschan1828 commented on library/csv.po
> +"回傳一個寫入器物件 (writer object)，其負責在給予的類檔案物件 (file-like "
```suggestion
"回傳一個寫入器物件 (writer object)，其負責在給定的類檔案物件 (file-like "
```

given 一般翻成「給定」。

2023-08-15 09:08 UTC, cschan1828 commented on library/csv.po
> +"從 CSV 檔案讀取的每一行會回傳為一個字串列表。除非格式選項 "
```suggestion
"從 CSV 檔案讀取的每一列會回傳為一個字串列表。除非格式選項 "
```

直行 (column) 橫列 (row)

2023-08-15 09:09 UTC, cschan1828 commented on library/csv.po
> +"獨立的格式化參數。關於 dialect 及格式化參數的完整說明，請見段落"
```suggestion
"個別的格式化參數。關於 dialect 及格式化參數的完整說明，請見段落"
```

2023-08-15 09:10 UTC, cschan1828 commented on library/csv.po
> +"另一個可選填的關鍵字引數 *fmtparams* 可以在這個 dialect 中 override"
```suggestion
"另一個可選填的關鍵字引數 *fmtparams* 可以在這個 dialect 中覆寫"
```

2023-08-15 09:17 UTC, cschan1828 commented on library/csv.po
> +" :ref:`csv-fmt-params`。為了讓它與實作 DB API 的模組之間的介面 (interface) "
> To make it as easy as possible to interface with modules which implement the DB API, the value ...

可以再稍微修一下，個人建議：

> 為了更容易與有實作 DB API 的模組互相接合，

原文意思並沒有要修改介面，或是讓介面更容易使用的修改之意，是這個 csv module 要去配合 DB API 介面，也就是那些有實作 DB API 介面的模組。

2023-08-15 09:26 UTC, cschan1828 commented on library/csv.po
> +"的呼叫以回傳預處理資料 (preprocessing data)。其餘非字串的資料則會在寫入之前"
這句請再想看看，`cursor.fetch*` 應該沒有預處理資料的功能。

原文意思較接近：（假設有個資料庫）若 `cursor.fetch` 回傳的資料具有 NULL，在 dump 資料到 CSV 檔案上就不需要額外的預處理。如果沒有這個設計： “the value None is written as the empty string"，資料庫當中的 NULL dump 出來到 CSV 上就會看到 ”NULL“ 字串，但實際上它是 NULL （空值）而不是 "NULL" 字串。

2023-08-15 09:26 UTC, cschan1828 commented on library/csv.po
> +"回傳當前的剖析器 (parser) 允許的最大字串大小。"
後面那句沒有翻譯到。

2023-08-15 09:28 UTC, cschan1828 commented on library/csv.po
> +"建立一個物件，其運作上就像一般的讀取器，但可以將每一行資訊 map （對映）"
同理，直行橫列。

2023-08-15 09:30 UTC, cschan1828 commented on library/csv.po
> +"類別 :class:`Dialect`。"
```suggestion
":class:`Dialect`。"
```

一個 immutable :class:`Dialect`。

2023-08-15 09:34 UTC, cschan1828 commented on library/csv.po
> +"將 *dialect* 與 *name* 進行關聯 (associate)。*name* 必須為字串。這個方言可以"
專有名詞請前後一致，一律用中文或英文，除非是該文件第一次提及時用括號註明。

2023-08-15 09:35 UTC, cschan1828 commented on library/csv.po
> +"被特指為 :class:`Dialect` 的子類別；或是關鍵字引數 *fmtparams*；或是以上"
> 被特指為 :class:`Dialect` 的子類別

這句意思有點奇怪，請再看下。

2023-08-15 09:37 UTC, cschan1828 requested changes
Thanks for the commit!

有些常見的動詞其實可以考慮直接找中文慣用動詞來用哦，保留原文主要是指專有名詞。

2023-08-15 09:37 UTC, rockleona commented on library/csv.po
> +"的呼叫以回傳預處理資料 (preprocessing data)。其餘非字串的資料則會在寫入之前"
了解 這邊的功能我知道
但我的翻譯不通順導致誤解，我晚點有空修改

2023-08-15 09:39 UTC, rockleona commented on library/csv.po
> +" :ref:`csv-fmt-params`。為了讓它與實作 DB API 的模組之間的介面 (interface) "
這邊也是因為翻譯不通順，感謝提醒

2023-08-15 09:43 UTC, rockleona commented on library/csv.po
> +"另一個可選填的關鍵字引數 *fmtparams* 可以在這個 dialect 中 override"
前面我是翻譯成 "override （覆寫）"
你會建議我修改成 "覆寫 (override)" 嗎？

2023-08-15 10:02 UTC, rockleona commented on library/csv.po
> +"另一個可選填的關鍵字引數 *fmtparams* 可以在這個 dialect 中 override"
我先改了XD

2023-08-15 10:06 UTC, rockleona commented on library/csv.po
> +"具有 :func:`write` method 的任何物件。若 *csvfile* 為一個檔案物件，它應該使用"
這邊有提及翻譯時可以保留原文，所以這邊我會不更動

https://github.com/python/python-docs-zh-tw/wiki/%E8%A1%93%E8%AA%9E%E5%88%97%E8%A1%A8

2023-08-15 10:10 UTC, rockleona commented
Hi @cschan1828 , thanks for the review!

感謝你的細心，再麻煩幫我看看了，感謝！

2023-08-15 11:49 UTC, cschan1828 commented on library/csv.po
> +"另一個可選填的關鍵字引數 *fmtparams* 可以在這個 dialect 中 override"
如果前面有出現並翻譯過，後面可以直接用中文而不必再附上原文。

2023-08-15 11:55 UTC, cschan1828 commented on library/csv.po
> +"具有 :func:`write` method 的任何物件。若 *csvfile* 為一個檔案物件，它應該使用"
我搜尋了一下這個 repo，看起來翻譯 method 與不翻譯的都有，雖然翻譯為「方法」的比較多。

2023-08-15 11:58 UTC, cschan1828 commented on library/csv.po
> +"可以透過 :class:`Dialect` 的子類別進行指定；或是關鍵字引數 *fmtparams*；或是以上"
這邊還是覺得應該要把 passing（傳遞）翻譯出來欸，你怎麼看？
雖然應該不太影響語意。

2023-08-15 12:00 UTC, cschan1828 reviewed
相當不錯了，僅想再釐清一些小細節。

2023-08-15 12:04 UTC, rockleona commented on library/csv.po
> +"可以透過 :class:`Dialect` 的子類別進行指定；或是關鍵字引數 *fmtparams*；或是以上"
我看這句看到昏頭了XD
但我覺得你說的很關鍵 我加上去

2023-08-15 12:10 UTC, cschan1828 reviewed
很通用的詞語直接用中文即可。

2023-08-15 12:10 UTC, cschan1828 commented on library/csv.po
> +"可以透過 passing（傳遞） :class:`Dialect` 的子類別進行指定；或是關鍵字引數 "
```suggestion
"可以透過傳遞 :class:`Dialect` 的子類別進行指定；或是關鍵字引數 "
```

2023-08-15 12:24 UTC, cschan1828 approved these changes
LGTM! Approved.

2023-08-15 12:38 UTC, mattwang44 approved these changes
Thanks guys!

2023-08-15 12:53 UTC, merged