Translate library/calendar part 1/2
python/python-docs-zh-tw pull request #593
Opened 2023-08-19 01:49 UTC by mindihx

issue: #587

2023-08-19 01:57 UTC, mindihx commented on library/calendar.po
> +"Calculations」這本書定義的「proleptic Gregorian」日曆，是做所有計算的基礎日"
不確定 proleptic Gregorian 要翻什麼，「前推公曆」?

2023-08-19 01:57 UTC, mindihx commented on library/calendar.po
> +"類似 :meth:`itermonthdates`，回傳一個在 *year* 年 *month* 月的疊代器，但不受"
其實這邊有點不確定不受限 datetime.date 的範圍是什麼意思，總之先照翻
我猜他想說的只是這個物件不是一個 datetime.date，而且也會出現這個月以外的數字

2023-08-21 18:21 UTC, cschan1828 commented on library/calendar.po
> +"Calculations」這本書定義的「proleptic Gregorian」日曆，是做所有計算的基礎日"
有很多種翻譯：前格里高曆法、逆推格里曆等。這牽涉到之前更換曆法系統的歷史。

2023-08-21 18:22 UTC, cschan1828 commented on library/calendar.po
> +"const:`MONDAY` 是 ``0``\\ （預設值），:const:`SUNDAY` 是 ``6``\\ 。"
```suggestion
"const:`MONDAY` 是 ``0`` （預設值），:const:`SUNDAY` 是 ``6``。"
```

數字與文字之間要留空格，所以不需要加\\

2023-08-21 18:26 UTC, cschan1828 commented on library/calendar.po
> +msgstr "一週每一天的別名，其中  ``MONDAY`` 是 ``0`` 而 ``SUNDAY`` 是 ``6``。"
```suggestion
msgstr "一週每一天的別名，其中 ``MONDAY`` 是 ``0`` 而 ``SUNDAY`` 是 ``6``。"
```

似乎不小心多了空格？

2023-08-21 18:29 UTC, cschan1828 requested changes
Thanks for your commit!

先看到 line 119，剩下的我這兩天抽空看。

2023-08-22 00:38 UTC, mindihx commented on library/calendar.po
> +"const:`MONDAY` 是 ``0``\\ （預設值），:const:`SUNDAY` 是 ``6``\\ 。"
英文數字遇到中文的左右括號或其它標點符號我都是不加空格的 (例如這句裡的句號前面的 6)，
因為中文的符號旁邊已經有多的空間，還是說都需要加?

2023-08-22 00:40 UTC, mindihx commented on library/calendar.po
> +"Calculations」這本書定義的「proleptic Gregorian」日曆，是做所有計算的基礎日"
因為我前面的 Gregorian calendar 已經翻成公曆
那這裡的我就先翻成「逆推公曆」附註原文好了

2023-08-22 00:41 UTC, mindihx commented
> Thanks for your commit!
> 
> 先看到 line 119，剩下的我這兩天抽空看。

了解，謝謝~
我等全部看完再一次改，先繼續翻下半段的

2023-08-22 18:56 UTC, cschan1828 commented on library/calendar.po
> +"類似 :meth:`itermonthdates`，回傳一個在 *year* 年 *month* 月的疊代器，但不受"
我自己實驗了一下 `itermonthdates` 與 `itermonthdays` 的差異，前者會回傳 `datetime.date` 物件但後者回傳的是 day numbers，故稱不受限 `datetime.date` 的範圍。

2023-08-22 19:19 UTC, cschan1828 commented on library/calendar.po
> +"const:`MONDAY` 是 ``0``\\ （預設值），:const:`SUNDAY` 是 ``6``\\ 。"
我的說法可能有點造成誤解，應該說碰到 rST 特殊語法時，加上 `\\ ` (double backslash + space) 經過 render 過後會有把原本會產生的空格消除掉的效果。可參考[這裡](https://github.com/python/python-docs-zh-tw#rst-語法注意事項)。

@mattwang44 如果有說錯或者不夠清楚的部份還請幫忙補充。

2023-08-22 19:20 UTC, cschan1828 commented on library/calendar.po
> +"以 HTML 表格的形式回傳一整年的日曆。*width*\\ （預設為 3）指定一列有幾個月。"
double backslash 同前面的討論，待有結論後一併修改。

2023-08-22 19:20 UTC, cschan1828 commented on library/calendar.po
> +"以完整 HTML 頁面的形式回傳一整年的日曆。*width*\\ （預設為 3）指定一列有幾個"
double backslash 同前面的討論，待有結論後一併修改。

2023-08-22 19:21 UTC, cschan1828 requested changes
Initial review completed.

2023-08-22 19:45 UTC, mattwang44 commented on library/calendar.po
> +"const:`MONDAY` 是 ``0``\\ （預設值），:const:`SUNDAY` 是 ``6``\\ 。"
你說的沒有錯歐，只是這裡有些小小 tricky 的地方：
- 阿拉伯數字與全形標點符號間不要有空格，所以預期 render 出來要長這樣：`是 0（預設值）`
- 但是若 rst/sphinx 語法與全形括號相連（無空格）時卻會 build failed（但與全形逗號、句號、頓號等相連則不會有問題）

所以我目前認知中是會這樣改

```suggestion
"const:`MONDAY` 是 ``0``\\ （預設值），:const:`SUNDAY` 是 ``6``。"
```

單純憑印象回答，可以再幫我跑指令看看這樣的說法正不正確 🙏🏽

2023-08-23 02:09 UTC, mindihx commented on library/calendar.po
> +"const:`MONDAY` 是 ``0``\\ （預設值），:const:`SUNDAY` 是 ``6``\\ 。"
的確只有全形括號需要 escape 空白，句號不需要
而英數字跟全形符號之間維持沒有空白
這邊我再改一下~ 謝謝

2023-08-23 02:26 UTC, cschan1828 commented on library/calendar.po
> +"const:`MONDAY` 是 ``0``\\ （預設值），:const:`SUNDAY` 是 ``6``\\ 。"
謝謝 Matt 的說明，忘記這邊是全形括號了，若是半形括號還是要留空格（no double backslash) 對吧？

2023-08-23 02:56 UTC, mattwang44 commented on library/calendar.po
> +"const:`MONDAY` 是 ``0``\\ （預設值），:const:`SUNDAY` 是 ``6``\\ 。"
> 半形括號還是要留空格（no double backslash) 對吧？

是的！

2023-08-23 03:24 UTC, mindihx commented on library/calendar.po
> +"以 HTML 表格的形式回傳一整年的日曆。*width*\\ （預設為 3）指定一列有幾個月。"
因為英數字和全形符號間不空白，這裡就維持需要 escape

2023-08-23 03:25 UTC, mindihx commented on library/calendar.po
> +"以完整 HTML 頁面的形式回傳一整年的日曆。*width*\\ （預設為 3）指定一列有幾個"
因為英數字和全形符號間不空白，這裡就維持需要 escape

2023-08-23 11:27 UTC, cschan1828 approved these changes
LGTM, Approved.

2023-08-23 11:27 UTC, merged