secrets translation v 1.0
python/python-docs-zh-tw pull request #66
Opened 2021-03-10 16:27 UTC by bonzoyang

please review my work and see if it should be merged. thx

2021-05-17 07:20 UTC, adrianliaw requested changes
感謝您的貢獻，不好意思拖了這麼久才 review :bow:

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +"尤其應優先使用 :mod:`secrets` 作為預設來替代 :mod:`random` 模組中的預設虛擬亂"
不太確定台灣怎麼翻譯 pseudo-random，查了一下比較常見的好像是「偽亂數」。但「虛擬」感覺不太能表達「pseudo」。

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +"數產生器 (pseudo-random number generator)，此模組被設計用於建模和模擬，而非用"
s/此模組/該模組

「此模組」所指的會是 secrets，但被設計用於建模和模擬的模組是 random。

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +" :mod:`secrets` 模組使你得以存取作業系統所能提供的最安全隨機性來源 (source)。"
這邊的 source 並非專有名詞，可以不用提及原文。

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +" :mod:`secrets` 模組使你得以存取作業系統所能提供的最安全隨機性來源 (source)。"
這一句感覺有點難翻譯，我想「the most secure source of randomness that your operating system provides」是一個比較攏統的說法，如果說的明確一點也許就是「作業系統所提供安全性最高的亂數產生器」

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +msgstr "返回從一非空序列中隨機選取的元素。"
我想把順序調換一下會比較順：「從一非空序列中，回傳一個隨機選取的元素」

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +msgstr "返回一個 [0, *n*) 範圍之內的隨機整數。"
s/返回/回傳

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +"返回一以十六進位表示的隨機文本字串 (text string)。 字串具有 *nbytes* 個隨機位"
「隨機字串」即可，這邊感覺不需要註釋原文。

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +"元組，每個位元組會轉成兩個十六進位的位數 (digit)。 如果 *nbytes* 為 ``None`` "
「兩個十六進位的數字」即可，digit 在這裡並非專有名詞

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +"或未提供，則會使用一個合理的預設值預設。"
則會使用一個合理的預設值<del>預設</del>

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +"Base64 編碼，因此平均來說每個位元組會對應到 1.3 個字元。 如果 *nbytes* 為 "
「approximately 1.3 characters」，應該要把 approximately 翻譯過來：「約 1.3 個字元」

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +"class:`int` 引數 (argument) 來指定權杖要使用的隨機性程度 :class:`int` 。 該引"
這邊多了一個

```
:class:`int`
```

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +msgstr "其他功能"
這邊說的應該就是程式語言裡面的 function，所以應該翻譯成「函式」會比較好

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +msgstr "產生八個字元長的字母數字密碼:"
請使用全形冒號

2021-05-17 07:20 UTC, adrianliaw commented on library/secrets.po
> +"definitions/257.html>`_，無論是用純文本還是經過加密。 它們應當先加鹽，再使用"
這邊所說的鹽我覺得是需要註記原文的專有名詞：`它們應當先加鹽（salt）`

2021-08-27 15:49 UTC, bonzoyang commented
> 感謝您的貢獻，不好意思拖了這麼久才 review 🙇

不會不會，辛苦了

2021-08-29 22:38 UTC, adrianliaw approved these changes

2021-08-29 23:41 UTC, merged