interpreter zh-tw 3.9
python/python-docs-zh-tw pull request #67
Opened 2021-04-28 20:04 UTC by StevenHsuYL

Modified from zh-cn 3.9.4 version by Traditional Chinese.

2021-05-17 06:13 UTC, adrianliaw requested changes

2021-05-17 06:13 UTC, adrianliaw commented on tutorial/interpreter.po
> +"Python解釋器一般安裝在 :file:`/usr/local/bin/python3.9` 路徑下；將 :file:`/"
s/解釋器/直譯器

另外，中英交換的部分麻煩中間加一個空格，感恩！

2021-05-17 06:13 UTC, adrianliaw commented on tutorial/interpreter.po
> +"usr/local/bin` 加入Unix終端的搜索路徑，鍵入以下命令就可以啟動Python："
我們目前應該是選擇不翻譯 Unix shell，直接保留原文即可。「終端」指的應該是 terminal 而不是 shell。

s/鍵入/輸入
s/命令/指令

2021-05-17 06:13 UTC, adrianliaw commented on tutorial/interpreter.po
> +"php/chet/readline/rltop.html>` 函式庫的系統上包含：互動編輯、歷史取代、指令補"
rST 的超連結語法應該要在最後加一個底線：
```
`GNU Readline <https://tiswww.case.edu/php/chet/readline/rltop.html>`_
```

請參考：https://docutils.sourceforge.io/docs/user/rst/quickref.html#hyperlink-targets

2021-05-17 06:13 UTC, adrianliaw commented on tutorial/interpreter.po
> +"另一個啟動直譯器的方式為 ``python -c command [arg] ...`` ，它會執行在 "
這邊的反斜線是有必要的，這樣 code block 和全形逗點之間才不會有空格。請參考：https://github.com/python/python-docs-zh-tw#rst

同樣，在其他幾條翻譯裡刪除的反斜線都是有存在的必要的。

2021-05-17 06:13 UTC, adrianliaw commented on tutorial/interpreter.po
> +msgstr "其中， *encoding* 可以是Python支持的任意一種 :mod:`codecs`  。"
s/支持/支援

另外，也麻煩移除句號前面多餘的空格，謝謝

2021-05-17 06:13 UTC, adrianliaw commented on tutorial/interpreter.po
> +"入解釋器時，首先顯示歡迎信息、版本信息、版權聲明，然後才是提示符：\n"
s/信息/訊息

2021-05-17 06:13 UTC, adrianliaw commented on tutorial/interpreter.po
> +"如果不使用預設編碼，則要聲明文件的編碼，文件的*第一*行要寫成特殊註釋。句法如"
s/文件/檔案
s/註釋/註解
s/句法/語法

2021-05-17 06:13 UTC, adrianliaw commented on tutorial/introduction.po
> +"相同的意思。兩種引號的唯一差別，在於使用單引號時，不需要避免 ``\"``\\ （但必"
引號 :+1: :pray:

不過這邊的 escape 說的確實是跳脫而不是避免（當然我們還是會習慣直接說 escape），請改回原本的說法：https://zh.wikipedia.org/zh-tw/%E8%BD%AC%E4%B9%89%E5%AD%97%E7%AC%A6

2021-05-17 06:13 UTC, adrianliaw commented on tutorial/interpreter.po
> +"在終端（tty）輸入並執行指令時，解釋器在*互動模式（interactive mode）*中運行。"
這邊目前 build 出來的結果是這樣：
<img width="831" alt="Screen Shot 2021-05-16 at 10 17 26 PM" src="https://user-images.githubusercontent.com/2776892/118439379-bc948180-b69a-11eb-8f13-1c3caaa4d981.png">

因為 rST 標記斜體的語法裡，開頭的星號前面必須是空格或是標準英文的標點符號，但如果前面是中文字或全形標點符號的話，則需要在開頭的星號前加上反斜線和空格；結尾的星號亦同，不過是加在星號後面。請參見：https://github.com/python/python-docs-zh-tw#rst

2021-05-17 06:13 UTC, adrianliaw commented on tutorial/interpreter.po
> +"*第一行*的規則也有一種例外情況，在源碼以 :ref:`UNIX \"shebang\" line <tut-"
這邊的 `*第一行*的規則` 需要在中間加上反斜線和空格（`*第一行*\ 的規則`），否則 rST 會沒辦法 build

2021-05-17 14:15 UTC, StevenHsuYL commented
上述錯誤已全數修正完畢，感謝提醒！

2021-05-18 08:15 UTC, adrianliaw reviewed
謝謝您的修改，幾個詞語再麻煩您幫忙統一一下，就可以 merge 了 :)

2021-05-18 08:15 UTC, adrianliaw commented on tutorial/interpreter.po
> +"在終端 (tty) 輸入並執行指令時，解釋器在\\ *互動模式（interactive mode）*\\ 中"
s/解釋器/直譯器

再麻煩您幫我把其他有「解釋器」的部分修正過來，感謝！

2021-05-18 08:15 UTC, adrianliaw commented on tutorial/interpreter.po
> +"如果不使用預設編碼，則要聲明檔案的編碼，文件的\\ *第一*\\ 行要寫成特殊註解。"
s/文件/檔案

同上，麻煩修正其他把「file」翻譯成「文件」的地方（文件應該是 document，file 應該翻譯為檔案） 🙏

2021-05-18 08:30 UTC, StevenHsuYL commented
這次應該都有完成了，感謝提醒！佩服您的眼力！

2021-05-18 08:47 UTC, adrianliaw approved these changes
✨ 🍰 ✨

2021-05-18 08:48 UTC, merged