Origin/translate-email-charset
python/python-docs-zh-tw pull request #736
Opened 2023-12-05 07:43 UTC by isabellechiu

2023-12-05 08:41 UTC, mattwang44 commented
要記得 rebase 歐

2023-12-06 17:52 UTC, mattwang44 reviewed
先請你修掉標點與空格問題後我再來看翻譯正確性～

2023-12-06 17:52 UTC, mattwang44 commented on library/email.charset.po
> +＂如果字元集合被用在電子郵件標題前必須被編碼的話，＂
不少地方用到全形引號了，要改成半形
```suggestion
"如果字元集合被用在電子郵件標題前必須被編碼的話，"
```

2023-12-06 17:52 UTC, mattwang44 commented on library/email.charset.po
> +＂ ``charset.BASE64`` （表base64編碼格式），或是 ``charset.SHORTEST`` 表示最短的 QP或是base64編碼格式。"
- 半形引號
- 中英文間要有空格
```suggestion
"``charset.BASE64`` （表 base64 編碼格式），或是 ``charset.SHORTEST`` 表示最短的 QP 或是base64編碼格式。"
```

2023-12-12 16:08 UTC, isabellechiu commented on library/email.charset.po
> +＂ ``charset.BASE64`` （表base64編碼格式），或是 ``charset.SHORTEST`` 表示最短的 QP或是base64編碼格式。"
OKOK~~

2023-12-12 16:08 UTC, isabellechiu commented on library/email.charset.po
> +＂如果字元集合被用在電子郵件標題前必須被編碼的話，＂
OK~

2023-12-19 09:52 UTC, isabellechiu reviewed
update rst:49-100

2024-03-26 16:37 UTC, cschan1828 requested changes
Please update the symbol, thanks!

2024-03-26 16:37 UTC, cschan1828 commented on library/email.charset.po
> +＂如果字元集合被用在電子郵件標題前必須被編碼的話，＂
在 github 上看還是怪怪的，可以的話請跟原文的 "" 符號比對一下，可以發現並不一樣（雖然乍看之下不容易分辨）。

2024-03-26 16:37 UTC, cschan1828 commented on library/email.charset.po
> +＂部分的字元集合在用於電子郵件的標題或內文前必須先被轉換。＂
```suggestion
"部分的字元集合在用於電子郵件的標題或內文前必須先被轉換。"
```

2024-03-26 16:37 UTC, cschan1828 commented on library/email.charset.po
> +＂如果 *input_charset* 是這些字元集合中的其中之一，這個屬性將會包含輸出時被轉換的字元集合名稱。＂
```suggestion
"如果 *input_charset* 是這些字元集合中的其中之一，這個屬性將會包含輸出時被轉換的字元集合名稱。"
```

2024-03-26 16:37 UTC, cschan1828 commented on library/email.charset.po
> +＂與 *header_encoding* 相同，但敘述郵件訊息內文的編碼格式，則與上述的標題編碼格式不同。＂
```suggestion
"與 *header_encoding* 相同，但敘述郵件訊息內文的編碼格式，則與上述的標題編碼格式不同。"
```

2024-03-26 16:37 UTC, cschan1828 commented on library/email.charset.po
> +＂ ``charset.SHORTEST`` 是不被允許在 *body_encoding* 使用。＂
```suggestion
"``charset.SHORTEST`` 是不被允許在 *body_encoding* 使用。"
```

2024-10-13 18:20 UTC, mattwang44 commented
close it in favor of #989

2024-10-13 18:20 UTC, closed without merging