Continue tutorial/classes.po
python/python-docs-zh-tw pull request #77
Opened 2021-06-05 18:19 UTC by StevenHsuYL

This PR is continued from #52 , with minor revision to previous translation.
The rest of the file was updated and finished.

Thanks for the patient review.

Reference: https://terms.naer.edu.tw/

2021-08-14 16:16 UTC, josix commented
Resolve Issue #4.
Thank you @StevenHsuYL for the translating this chapter. I'll try to review this translation and other members in sprint today will review other chapters so that this project could move faster. (for more detail you could read the listed action items [here](https://hackmd.io/@sciwork/HyHIACNeK)) We will exchange our reviews after we made the phase one review and try to make the rule of reviewing the translation and make the review process more smoothly.

2021-09-18 18:32 UTC, josix requested changes
感謝 @StevenHsuYL 後續的翻譯，主要有兩個想要請教及討論的地方：
1. 哪些專有名詞會需要以中文為主括號內使用英文，哪些會以英文括號內使用中文呢？
2. reference 這個詞在不同段落有翻譯成不同詞的情形發生，想確認應該要以哪個為主比較好？
再麻煩 @StevenHsuYL 了，謝謝！

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"class（基底類別），一個 derived class（衍生類別）可以覆寫 (override) 其 base "
想要確認一下我們哪些詞會需要統一以中文為主括號內寫英文，哪些詞會是英文為主括號內寫中文？這邊判定的規則會是什麼？
```suggestion
"計 (Object Oriented Programming) 的標準特色：class 繼承機制允許多個基底類別（base "
"class），一個衍生類別 （derived class）可以覆寫 (override) 其 base "
```

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"class 所定義的）method（方法），用於修改該實例的狀態。"
同上想請教 @StevenHsuYL  這邊想法
```suggestion
"class 所定義的）方法（method），用於修改該實例的狀態。"
```

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"class 的任何 method，且一個 method 可以用相同的名稱呼叫其 base class 的 "
同上，是否需要讓 "method" 統一使用 "方法"、"base class" 統一用 "基底類別" 呢？

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"definition（類別定義）以命名空間展現了一些俐落的技巧，而你需要了解作用域和命名"
這邊同樣是想要討論 class definition 是否需要以中文為主？

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"含了非區域 (non-local) 也非全域 (non-global) 的名稱"
這邊“也”改成“和”可能會比較口語？
```suggestion
"任何外圍函式 (enclosing function) 的作用域，會從最近的外圍作用域開始搜尋，它包"
"含了非區域 (non-local) 和非全域 (non-global) 的名稱"
```

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"如果一個名稱被宣告為全域，則所有的引用和賦值將直接轉到包含模組全域名稱的中間作"
references 翻譯有些不一致，前面的部分大多翻譯成引用但後半的段落會翻譯成參照

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"串 (docstring)：\\ ``\"A simple example class\"``。"
A simple example class 沒有翻譯到

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"看過疊代器流程的幕後機制後，在你的 class 加入疊代器的行為就很容易了。定義一"
protocol 我覺得翻成協定會比較適合，protocol 應該不是只 iterator 的行為，是指與 iterator 使用相關的規範/規則。

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"資料屬性可能被 method 或是被物件的一般使用者（「客戶端」）所參照。也就是說，"
這邊也有 reference 翻譯不一致， 在上面的段落被翻為引用但這裡翻譯成參照。

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"客戶端應該小心使用資料屬性——客戶端可能會因為標記他們的資料屬性，而破壞了被 "
stamping on their data attributes 感覺有客戶端自行覆蓋了資料屬性的意味，不太確定翻譯成標記合不合適？

2021-09-18 18:32 UTC, josix commented on tutorial/classes.po
> +"在 method 中參照資料屬性（或其他 method！）是沒有簡寫的。我發現這實際上增加了 "
這邊 reference 翻譯也有與前文不一致的現象，不確定是以 "引用" 還是 "參照" 為主？

2021-09-21 04:18 UTC, StevenHsuYL commented
> 感謝 @StevenHsuYL 後續的翻譯，主要有兩個想要請教及討論的地方：
> 
> 1. 哪些專有名詞會需要以中文為主括號內使用英文，哪些會以英文括號內使用中文呢？
> 2. reference 這個詞在不同段落有翻譯成不同詞的情形發生，想確認應該要以哪個為主比較好？
>    再麻煩 @StevenHsuYL 了，謝謝！

感謝審閱！我表達一下翻譯時的想法，但也都可以討論再修正：

1. 大部分的特殊專有名詞，都是以 "中文 (english)" 的模式來翻譯，除了以下的詞條：class, method, list...，原因是 README 的 [glossary table](https://github.com/python/python-docs-zh-tw#glossary) 如此建議，我必須依照此規則進行翻譯。所以在文中第一次遇到這些字時，會變成 class（類別）、method（方法）、list（串列），然後這些字之後再出現時，就只會出現原文，不會再括號中文。
因為有 "class" 必須保留原文的前提規則，所以 base class, class definition 等字，我也會一併保留完整名詞，翻譯規則就如同 class 的方式。我想 coordinator 當初訂此規則，是希望保留 "class" 的獨特性，不希望用「類別」來描述此字。method, list...似乎也是如此。
如果要修改此規則，那麼有許多檔案都必須做出相應的修正，這個留給大家討論。

2. Reference: 
   當用於表示某個位址值時，我使用「參照」，如同[維基百科](https://zh.wikipedia.org/wiki/%E5%8F%83%E7%85%A7)的翻譯，通常是名詞。
   若用於表示使用上述位址連結到目標的「過程」，我會翻成「引用」，可能是名詞或動詞。
   例如：The reference will be referenced by this object -> 該參照會被此物件所引用。
   但我剛剛有發現，似乎有幾個地方翻錯了，應該要修正為「引用」，感謝指正！

以上是我的想法，在翻譯規則上有任何需要修正改進之處，也都可以討論修正，謝謝！

2021-09-21 04:28 UTC, StevenHsuYL commented on tutorial/classes.po
> +"串 (docstring)：\\ ``\"A simple example class\"``。"
這句話是上段 [code example](https://docs.python.org/zh-tw/3/tutorial/classes.html#class-objects) 內的 code，這部分我是認為應該不用翻譯（因為 code 都是原文，如果翻譯了，讀者會找不到真正的回傳結果）。

2021-09-21 04:28 UTC, StevenHsuYL commented on tutorial/classes.po
> +"資料屬性可能被 method 或是被物件的一般使用者（「客戶端」）所參照。也就是說，"
這裡我會修改為「引用」，感謝提醒！

2021-09-21 04:40 UTC, StevenHsuYL commented on tutorial/classes.po
> +"客戶端應該小心使用資料屬性——客戶端可能會因為標記他們的資料屬性，而破壞了被 "
同意需要修正。
"Stamp on" 在字典裡是翻作「蓋戳於，銘刻在...」，也許這句可以改成「客戶端可能會因為覆寫他們的資料屬性，...」
雖然原文沒有 override，但此處意思相似，您覺得如何？

2021-09-21 04:40 UTC, StevenHsuYL commented on tutorial/classes.po
> +"在 method 中參照資料屬性（或其他 method！）是沒有簡寫的。我發現這實際上增加了 "
這裡我會修改為「引用」，感謝提醒！

2021-09-21 05:22 UTC, StevenHsuYL commented on tutorial/classes.po
> +"在 method 中參照資料屬性（或其他 method！）是沒有簡寫的。我發現這實際上增加了 "
我目前是希望我們能夠統一使用「參照」作為 reference 的翻譯，理由如末段回覆。

2021-09-21 05:23 UTC, StevenHsuYL commented on tutorial/classes.po
> +"資料屬性可能被 method 或是被物件的一般使用者（「客戶端」）所參照。也就是說，"
我目前是希望我們能夠統一使用「參照」作為 reference 的翻譯，理由如末段回覆。

2021-09-21 05:23 UTC, StevenHsuYL commented on tutorial/classes.po
> +"如果一個名稱被宣告為全域，則所有的引用和賦值將直接轉到包含模組全域名稱的中間作"
我目前是希望我們能夠統一使用「參照」作為 reference 的翻譯，理由如末段回覆。

2021-09-22 04:31 UTC, josix commented on tutorial/classes.po
> +"串 (docstring)：\\ ``\"A simple example class\"``。"
抱歉我沒有注意到，瞭解了感謝說明🙏

2021-09-23 08:37 UTC, josix commented on tutorial/classes.po
> +"客戶端應該小心使用資料屬性——客戶端可能會因為標記他們的資料屬性，而破壞了被 "
沒問題，我覺得應該可以

2021-09-23 08:41 UTC, josix approved these changes
LGTM, 謝謝 @StevenHsuYL

2021-09-25 05:58 UTC, merged