Translate logging document  No. 187 and 193
python/python-docs-zh-tw pull request #846
Opened 2024-03-10 08:39 UTC by seal0112

<img width="920" alt="截圖 2024-03-10 下午4 36 55" src="https://github.com/python/python-docs-zh-tw/assets/5734907/a80fdb75-e5ff-4815-904d-1dd3b7b19656">

2024-03-10 08:54 UTC, rockleona requested changes

2024-03-10 08:54 UTC, rockleona commented on library/logging.po
> +"紀錄 :const:`DEBUG` 等級的訊息到 logger 上。 *msg* 是訊息格式字串，"
特殊語法之前，若為中文標點符號則無須空格

```suggestion
"紀錄 :const:`DEBUG` 等級的訊息到 logger 上。*msg* 是訊息格式字串，"
```

2024-03-10 08:54 UTC, rockleona commented on library/logging.po
> +"而 *args* 是一些將要被整合進 *msg* 的關鍵字參數。"
`argument` 應翻譯為 `引數`
然後原文應該沒有關鍵字？
```suggestion
"而 *args* 是一些將要被整合進 *msg* 的引數。"
```

2024-03-10 08:54 UTC, rockleona commented on library/logging.po
> +"*exc_info*, *stack_info*, *stacklevel* 以及 *extra*."
- 請用中文標點符號
- 請看這個[檔案](https://github.com/python/python-docs-zh-tw/wiki/___%E8%A9%B2%E7%BF%BB%E6%88%90%E4%BB%80%E9%BA%BC%EF%BC%9F)，看一下專有名詞要怎麼翻譯

```suggestion
"*kwargs* 中將會有四個關鍵字引數會被檢查："
"*exc_info*、*stack_info*、*stacklevel* 以及 *extra*."
```

2024-03-12 00:21 UTC, ken71301 commented on library/logging.po
> +"紀錄 :const:`DEBUG` 等級的訊息到 logger 上。 *msg* 是訊息格式字串，"
`level` 應譯為 `層級`
```suggestion
"紀錄 :const:`DEBUG` 層級的訊息到 logger 上。 *msg* 是訊息格式字串，"
```

2024-03-12 00:23 UTC, ken71301 commented on library/logging.po
> +"而 *args* 是一些將要被整合進 *msg* 的關鍵字參數。"
using the string formatting operator 漏翻~

2024-03-12 00:31 UTC, ken71301 commented on library/logging.po
> +"(請注意，這表示你可以使用單一的 dictionary 物件將關鍵字放入格式字串中。)"
together with 在字典中的定義是 [in addition to; and also:](https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E/addition) 
這句也沒有物件
這句應該比較接近這樣
`你可以在與單一字典引數與格式字串中一同使用關鍵字`

2024-03-28 14:32 UTC, rockleona commented
嗨嗨 @seal0112，請問這邊的修正還會繼續嗎?

2024-03-28 15:23 UTC, seal0112 commented
嗨 @rockleona, 抱歉活動結束隔天我得了a型流感, 身體復原後回去上班都在趕工作落後的進度, 這個issue我週末會把它完成, 謝謝你的提醒

2024-03-28 15:25 UTC, rockleona commented
> 嗨 @rockleona, 抱歉活動結束隔天我得了a型流感, 身體復原後回去上班都在趕工作落後的進度, 這個issue我週末會把它完成, 謝謝你的提醒

沒問題喔👌保重身體！
有時間再處理就好

2024-03-29 01:45 UTC, closed without merging