Update string.po translation
python/python-docs-zh-tw pull request #850
Opened 2024-03-10 10:54 UTC by marychiou

Update translation of #: ../../library/string.rst:81
![string81](https://github.com/python/python-docs-zh-tw/assets/50230427/67ddf656-43d9-4703-8c77-7618ef2ea538)

Update translation of #: ../../library/string.rst:98
![string98](https://github.com/python/python-docs-zh-tw/assets/50230427/dfd26cde-bb4a-4f33-b992-47f7596a3dbb)

2024-03-10 10:56 UTC, marychiou commented
Update string.po translation rst:81, rst:98

2024-03-10 14:00 UTC, rockleona requested changes

2024-03-10 14:00 UTC, rockleona commented on library/string.po
> +"串格式化行為。"
- 中文標點符號 與 特殊符號 中間不用增加空格

```suggestion
"透過 :pep:`3101` 中描述的 :meth:`~str.format` 方法，內建字串類別提供了進行複"
"雜變數替換和數值格式化的能力。:mod:`string` 模組中的 :class:`Formatter` 類別"
"模組可讓你使用與內建 :meth:`~str.format` 方法相同的實作來建立和自訂你自己的字"
"串格式化行為。"
```

2024-03-10 14:00 UTC, rockleona commented on library/string.po
> +msgstr "現在格式字串引數是 :ref:`positional-only <positional-only_parameter>`。"
- 這裡是 rST 特殊語法，請記得翻譯
- 因為文中顯示的是中文，但須配合 rST 語法，所以需要改成如下的寫法，[ref](https://github.com/python/python-docs-zh-tw/wiki/rST-%E7%89%B9%E6%AE%8A%E8%AA%9E%E6%B3%95%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A0%85)

```suggestion
msgstr "現在格式字串引數是\\ :ref:`僅限位置參數 <positional-only_parameter>`。"
```

2024-03-11 06:16 UTC, rockleona approved these changes, later dismissed
LGTM

2024-03-11 07:27 UTC, merged