Add Translate of library/_thread.po
python/python-docs-zh-tw pull request #860
Opened 2024-03-24 13:07 UTC by Mayavi345

https://github.com/python/python-docs-zh-tw/issues/805

2024-05-29 09:11 UTC, mattwang44 commented
@cschan1828 @josix 最近有空幫忙 review 這個 PR 嗎～

2024-05-31 06:44 UTC, cschan1828 commented
> @cschan1828 or @josix 最近有空幫忙 review 這個 PR 嗎～

沒問題，我這幾天可以看。

2024-06-07 05:57 UTC, cschan1828 commented on library/_thread.po
> +"的低階原始物件 --- 多個控制緒分享其全域資料空間。為了處理同步問題，也提供了簡"
```suggestion
"的低階原始物件 --- 多個控制執行緒分享其全域資料空間。為了處理同步問題，也提供了簡"
```

2024-06-07 05:57 UTC, cschan1828 commented on library/_thread.po
> +"單的鎖 (lock) 機制（也稱為:dfn:`互斥鎖`或:dfn:`二進位號誌`）。 :mod:"
```suggestion
"單的鎖 (lock) 機制（也稱為:dfn:`互斥鎖` 或 :dfn:`二進位號誌`）。 :mod:"
```

2024-06-07 05:59 UTC, cschan1828 commented on library/_thread.po
> +msgstr "這是鎖物件的類型。"
```suggestion
msgstr "這是鎖物件的型別。"
```

這裡指的應該是像 int, boolean 或者 long 種資料型別。

2024-06-07 06:02 UTC, cschan1828 commented on library/_thread.po
> +"開始一個新的執行緒並返回其識別碼 (identifier) 。該執行緒執行帶有參數列表 "
```suggestion
"開始一個新的執行緒並回傳其識別碼 (identifier) 。該執行緒執行帶有參數列表 "
```

此翻譯文件用「回傳」居多。

2024-06-07 06:03 UTC, cschan1828 commented on library/_thread.po
> +msgstr "當函式返回時，執行緒會靜默退出。"
```suggestion
msgstr "當函式回傳時，執行緒會靜默退出。"
```

2024-06-07 06:04 UTC, cschan1828 commented on library/_thread.po
> +"當函式因未處理的異常終止時，將調用 :func:`sys.unraisablehook` 來處理異常。鉤"
```suggestion
"當函式因未處理的異常終止時，將呼叫 :func:`sys.unraisablehook` 來處理該異常。鉤"
```

繁體中文講「呼叫」而不用「調用」。

2024-06-07 06:05 UTC, cschan1828 commented on library/_thread.po
> +"子參數的 *object* 屬性是 *function*。預設情況下，會打印堆疊跟蹤，然後執行緒退"
parameter 翻譯為「參數」，argument 則是 「引數」。近日雖然這兩者的區別逐漸模糊，為維持一致性，還是請你照這樣的規則來翻譯。

2024-06-07 06:07 UTC, cschan1828 commented on library/_thread.po
> +msgstr "新增了 *signum* 參數以自定義信號編號。"
```suggestion
msgstr "新增了 *signum* 引數以自定義信號編號。"
```

2024-06-07 06:08 UTC, cschan1828 commented on library/_thread.po
> +msgstr "返回一個新的鎖物件。鎖物件的方法如下所述。初始狀況下鎖是解鎖狀態。"
```suggestion
msgstr "回傳一個新的鎖物件。鎖物件的方法如下所述。初始狀況下鎖是解鎖狀態。"
```

2024-06-07 06:18 UTC, cschan1828 commented on library/_thread.po
> +"返回當前執行緒的「執行緒識別碼」。這是一個非零的整數。它的值沒有直接的含義；"
```suggestion
"回傳當前執行緒的「執行緒識別碼」。這是一個非零的整數。它的值沒有直接的含義；"
```

2024-06-07 06:19 UTC, cschan1828 commented on library/_thread.po
> +"並創建另一個執行緒時，執行緒識別碼可能會被重複使用。"
```suggestion
"並建立另一個執行緒時，執行緒識別碼可能會被重複使用。"
```

2024-06-07 06:22 UTC, cschan1828 commented on library/_thread.po
> +"keyword:`finally` 子句），並且標準 I/O 文件不會被刷新。"
若這裡將 files 翻譯成文件，那麼跟 document 的差異又在哪邊呢？
File 在繁體中文語系是指「檔案」，包含音樂檔、二進位執行檔與影音等，不只單純是文件型的檔案。

2024-06-07 06:24 UTC, cschan1828 commented on library/_thread.po
> +msgstr "除了這些方法之外，鎖物件還可以通過 :keyword:`with` 語句來使用，例如："
```suggestion
msgstr "除了這些方法之外，鎖物件還可以透過 :keyword:`with` 語句來使用，例如："
```

2024-06-07 06:34 UTC, cschan1828 requested changes
請先參閱[術語列表](https://github.com/python/python-docs-zh-tw/wiki/%E8%A1%93%E8%AA%9E%E5%88%97%E8%A1%A8)。

常見詞語誤用：
- Return: 「返回」改為「回傳」
- Exception: 「異常」改為「例外」。這個專案內還是用例外居多。
- Call: 「調用」改為「呼叫」。術語表中類似的部份很久以前已明確譯為「呼叫」。
- Argument: 引數
- Parameter: 參數
- File: 檔案

2024-06-16 14:36 UTC, Mayavi345 commented on library/_thread.po
> +"並創建另一個執行緒時，執行緒識別碼可能會被重複使用。"
創建=>建立

2024-06-16 14:36 UTC, Mayavi345 commented on library/_thread.po
> +"keyword:`finally` 子句），並且標準 I/O 文件不會被刷新。"
* File =>檔案
* document =>文件

2024-06-17 06:46 UTC, mattwang44 commented on library/_thread.po
> +"開始一個新的執行緒並回傳其識別碼 (identifier) 。該執行緒執行帶有引數列表 "
參考 https://github.com/python/python-docs-zh-tw/discussions/809

2024-06-17 06:46 UTC, mattwang44 commented on library/_thread.po
> +"子引數的 *object* 屬性是 *function*。預設情況下，會打印堆疊跟蹤，然後執行緒退"
print: 打印 -> 列印

2024-06-17 06:46 UTC, mattwang44 commented on library/_thread.po
> +"模擬一個信號到達主執行緒的效果。執行緒可以使用此函式來中斷主執行緒，但無法保"
signal: 信號 -> 訊號
ref: https://hackmd.io/@l10n-tw/glossaries

2024-06-17 06:46 UTC, mattwang44 commented on library/_thread.po
> -msgstr ""
自這一行以下的內容僅會出現在[索引頁面](https://docs.python.org/zh-tw/3/genindex-all.html)，建議翻譯內容是以原文開頭、後面括號附註譯文，以保持該詞彙在索引表列中的位置

2024-06-18 13:09 UTC, cschan1828 requested changes
Looks good overall! Matt and I just have a few minor suggestions for changes.

2024-06-24 14:28 UTC, Mayavi345 commented
I'm really happy to receive your comment.  thank you so much!

2024-06-27 14:54 UTC, mattwang44 commented
LGTM, @cschan1828 please have a final review 🙏🏽

2024-06-29 06:49 UTC, cschan1828 approved these changes
LGTM, Approval

2024-06-29 06:49 UTC, merged