Translate time
python/python-docs-zh-tw pull request #921
Opened 2024-07-15 14:50 UTC by ken71301

2024-07-15 16:09 UTC, ken71301 commented
`或者使用 ``nanosleep()``（`
像這樣接左大括號就會失敗

2024-08-05 02:43 UTC, beccalzh requested changes
好囉~ 嘿嘿

2024-08-05 02:43 UTC, beccalzh commented on library/time.po
> +"隔的時鐘。它包括睡眠期間經過的時間，並且涵蓋整個系統。回傳值的參考點沒有定"
```suggestion
"隔的時鐘。它包括睡眠經過的時間，並且涵蓋整個系統。回傳值的參考點沒有定"
```
期間好像就包含時間的意思，這樣會比較順嗎？

2024-08-05 02:43 UTC, beccalzh commented on library/time.po
> +"回傳當前行程的系統和用戶 CPU 時間之和（以秒的小數部分表示）。它不包括睡眠期間"
```suggestion
"回傳當前行程的系統和用戶 CPU 時間之和（以秒的小數部分表示）。它不包括睡眠時"
```
那這邊也是「期間」改成「時」~

2024-08-05 02:43 UTC, beccalzh commented on library/time.po
> +"行。在 Windows 8.1 及更高版本中，此實作使用\\ `高解析度計時器 <https://docs."
```suggestion
"行。在 Windows 8.1 及更新版本中，此實作使用\\ `高解析度計時器 <https://docs."
```

2024-08-05 02:43 UTC, beccalzh commented on library/time.po
> +msgstr "或者使用 ``nanosleep()``\\ （解析度：1 奈秒）；"
```suggestion
msgstr "如果可以，或者使用 ``nanosleep()``\\ （解析度：1 奈秒）；"
```

2024-08-05 02:43 UTC, beccalzh commented on library/time.po
> +"即使休眠被信號中斷，此函式現在至少還是會休眠 *secs*，除非信號處理器引發例外"
```suggestion
"即使睡眠被信號中斷，此函式現在至少還是會睡眠 *secs*，除非信號處理器引發例外"
```

2024-08-05 02:43 UTC, beccalzh commented on library/time.po
> +"將由 :func:`gmtime` 或 :func:`localtime` 回傳的代表時間的元組或 :class:"
```suggestion
"將由 :func:`gmtime` 或 :func:`localtime` 回傳代表時間的一個元組或 :class:"
```

2024-08-05 02:43 UTC, beccalzh commented on library/time.po
> +"一年中的週數（星期天作為一週的第一天），表示為十進位數 [00,53]。新的一年中，"
週，有需要固定都用「週」或「周」嗎？

2024-08-05 02:43 UTC, beccalzh commented on library/time.po
> +"當與 :func:`strptime` 函式一起使用時，``%U`` 和 ``%W`` 僅在指定星期幾和年份時"
```suggestion
"當與 :func:`strptime` 函式一起使用時，``%U`` 和 ``%W`` 僅在指定週間的某天和年份時"
```
星期幾好像偏口語~

2024-08-05 02:43 UTC, beccalzh commented on library/time.po
> +"某些平台可能支援其他指令，但只有這裡列出的指令具有 ANSI C 標準化的意義。要查"
```suggestion
"某些平台可能支援額外的指令，但只有這裡列出的指令具有 ANSI C 標準化的意義。要查"
```

2024-08-05 03:35 UTC, ken71301 commented on library/time.po
> +"隔的時鐘。它包括睡眠期間經過的時間，並且涵蓋整個系統。回傳值的參考點沒有定"
還是用這個？
```suggestion
"隔的時鐘。它包括睡眠時經過的時間，並且涵蓋整個系統。回傳值的參考點沒有定"
```

2024-08-05 03:36 UTC, ken71301 commented on library/time.po
> +"隔的時鐘。它包括睡眠期間經過的時間，並且涵蓋整個系統。回傳值的參考點沒有定"
那個 期間 主要是翻給during用的就是了

2024-08-05 03:37 UTC, ken71301 commented on library/time.po
> +"行。在 Windows 8.1 及更高版本中，此實作使用\\ `高解析度計時器 <https://docs."
總覺得會被看成 update那個更新所以
```suggestion
"行。在 Windows 8.1 及更新的版本中，此實作使用\\ `高解析度計時器 <https://docs."
```

2024-08-05 03:38 UTC, ken71301 commented on library/time.po
> +msgstr "或者使用 ``nanosleep()``\\ （解析度：1 奈秒）；"
我當時把它拿掉是因為我覺得以條列式（見原文排版）來說，這個 if available 翻起來超卡的

2024-08-05 03:43 UTC, ken71301 commented on library/time.po
> +"一年中的週數（星期天作為一週的第一天），表示為十進位數 [00,53]。新的一年中，"
我看了一下應該是同義沒問題，我個人是偏好使用 週，不過我想不強制要求應該也沒關係吧？

2024-08-05 04:41 UTC, beccalzh commented on library/time.po
> +msgstr "或者使用 ``nanosleep()``\\ （解析度：1 奈秒）；"
確實 我只是想說原文有就加了
不加應該也可以吧~~~

2024-08-05 04:46 UTC, beccalzh commented on library/time.po
> +"一年中的週數（星期天作為一週的第一天），表示為十進位數 [00,53]。新的一年中，"
不確定統一會不會比較好讀，就前後看起來一樣？
問個 @mattwang44

2024-08-06 07:40 UTC, mattwang44 commented on library/time.po
> +"一年中的週數（星期天作為一週的第一天），表示為十進位數 [00,53]。新的一年中，"
單篇文章內盡量統一，不同文章不一樣的話我覺得沒關係

2024-08-06 13:27 UTC, ken71301 commented on library/time.po
> +msgstr "區域設定的周間日 (weekday) 縮寫名稱。"
```suggestion
msgstr "區域設定的週間日 (weekday) 縮寫名稱。"
```

2024-08-06 13:27 UTC, ken71301 commented on library/time.po
> +msgstr "區域設定的完整周間日名稱。"
```suggestion
msgstr "區域設定的完整週間日名稱。"
```

2024-08-06 13:27 UTC, ken71301 commented on library/time.po
> +msgstr "周間日，表示為十進位數 [0（星期天）,6]。"
```suggestion
msgstr "週間日，表示為十進位數 [0（星期天）,6]。"
```

2024-08-06 16:49 UTC, beccalzh submitted a review, later dismissed
LGTM 💯

2024-08-07 03:31 UTC, mattwang44 commented on library/time.po
> +"函式 :func:`strptime` 在給定 ``%y`` 格式碼時可以解析兩位數的年份。當剖析兩位"
```suggestion
"函式 :func:`strptime` 在給定 ``%y`` 格式碼時可以剖析兩位數的年份。當剖析兩位"
```

2024-08-07 03:31 UTC, mattwang44 commented on library/time.po
> +"回傳單調 (monotonic) 時鐘（即不能倒轉的時鐘）的值（以秒的小數部分表示）。該時"
nit
```suggestion
"回傳單調時鐘（monotonic clock，即不能倒轉的時鐘）的值（以秒的小數部分表示）。該時"
```

2024-08-07 03:31 UTC, mattwang44 commented on library/time.po
> +"回傳單調 (monotonic) 時鐘（即不能倒轉的時鐘）的值（以秒的小數部分表示）。該時"
原本翻譯看起來像是不帶整數部分的小數
```suggestion
"回傳單調 (monotonic) 時鐘（即不能倒轉的時鐘）的值（以帶有小數的秒數表示）。該時"
```

2024-08-07 03:31 UTC, mattwang44 commented on library/time.po
> +"回傳性能計數器的值（以秒的小數部分表示），即具有最高可用解析度來測量短時間間"
ditto
```suggestion
"回傳性能計數器的值（以帶有小數部分的秒數表示），即具有最高可用解析度來測量短時間間"
```

2024-08-07 03:31 UTC, mattwang44 commented on library/time.po
> +"回傳當前行程的系統和用戶 CPU 時間之和（以秒的小數部分表示）。它不包括睡眠期間"
ditto

2024-08-07 03:31 UTC, mattwang44 commented on library/time.po
> +"如果睡眠被信號中斷且信號處理器未引發例外，則睡眠將以重新計算過的暫停 "
timeout 過去應該翻成「[超時](https://terms.naer.edu.tw/detail/b316dcacf7c43ca64b4cb0a1b99d0070/)」或「[逾時](https://terms.naer.edu.tw/detail/5ec4707e741903dc0097bea3df71ab63/)」
```suggestion
"如果睡眠被信號中斷且信號處理器未引發例外，則睡眠將以重新計算過的超時 "
```

2024-08-07 03:31 UTC, mattwang44 commented on library/time.po
> +"如果睡眠被信號中斷且信號處理器未引發例外，則睡眠將以重新計算過的暫停 "
nit: somehow 體感覺得 signal 在繁中文章比較常翻譯成「訊號」而非「信號」，但我找不到有力的材料說明兩者差異，不改沒關係
```suggestion
"如果睡眠被訊號中斷且訊號處理器未引發例外，則睡眠將以重新計算過的暫停 "
```

2024-08-07 03:31 UTC, mattwang44 commented on library/time.po
> +"十進位的小時數位，M 代表十進位的分鐘數位 [-23:59, +23:59]。 [1]_"
這邊的 digits 翻成「位數」或「數字」會不會比較精準？

2024-08-07 04:13 UTC, beccalzh commented on library/time.po
> +"十進位的小時數位，M 代表十進位的分鐘數位 [-23:59, +23:59]。 [1]_"
翻成「數碼」呢？
［ref](https://byvoid.com/zht/blog/region-phrases-comparison-digital/)

2024-08-07 06:09 UTC, mattwang44 commented on library/time.po
> +"十進位的小時數位，M 代表十進位的分鐘數位 [-23:59, +23:59]。 [1]_"
it seems to be legit.
consider adding the term (with that reference) to the glossary table 🙏🏽

2024-08-14 08:00 UTC, ken71301 commented on library/time.po
> +"如果睡眠被信號中斷且信號處理器未引發例外，則睡眠將以重新計算過的暫停 "
同意~

2024-08-14 08:07 UTC, mattwang44 commented on library/time.po
> +"十進位的小時數位，M 代表十進位的分鐘數位 [-23:59, +23:59]。 [1]_"
just for reference #944

2024-08-14 08:09 UTC, mattwang44 approved these changes
LGTM

2024-08-14 10:00 UTC, beccalzh approved these changes

2024-08-14 10:31 UTC, merged