Translate distributing/index.po
python/python-docs-zh-tw pull request #96
Opened 2021-07-04 13:20 UTC by StevenHsuYL

Full translation of distributing/index.po
Thanks for review.

Reference: https://terms.naer.edu.tw/

2021-09-30 03:21 UTC, josix requested changes
感謝 @StevenHsuYL 翻譯，主要想討論的只有 `packaging` 會是翻成打包比較好還是用`封裝`，由於在 OOP 中會常將 `encapsulation` 翻成封裝，打包這個詞相對只有在發布時比較常見，不知道你覺得怎麼樣？感謝🙏

2021-09-30 03:21 UTC, josix commented on distributing/index.po
> +"罕見）的問題已經建立的解決方案，更可以在公用社群中潛在地貢獻他們自己的解決方"
"公用社群" 改成 "公開社群" 不知道怎麼樣，公用感覺比較像是描述物品

2021-09-30 03:21 UTC, josix commented on distributing/index.po
> +msgstr "Python 封裝使用者指南包含了關於\\ `當今推薦工具`_\\ 的更多細節。"
封裝比較常見到是翻譯 `encapsulation` 這個詞，packaging 不知道翻成打包如何？

2021-09-30 03:21 UTC, josix commented on distributing/index.po
> +msgstr "`上傳專案至 Python 套件索引`_"
Python Packaging Index 可以保留原文會比較清楚這邊指的是 [PyPI](https://pypi.org/)

2021-09-30 03:21 UTC, josix commented on distributing/index.po
>  msgstr ""
想確認這邊是重複了嗎？

2021-10-01 12:28 UTC, StevenHsuYL commented on distributing/index.po
> +msgstr "Python 封裝使用者指南包含了關於\\ `當今推薦工具`_\\ 的更多細節。"
感謝建議！
這邊我可以說明一下，packaging 翻成「封裝」的參考來源有兩處：
1. [教育部辭典](https://terms.naer.edu.tw/search/?q=%22packaging%22&field=ti&op=AND&num=10&match=smart&q=noun:%22%E9%9B%BB%E5%AD%90%E8%A8%88%E7%AE%97%E6%A9%9F%E5%90%8D%E8%A9%9E%22&field=&op=AND)
2. [Microsoft Docs](https://docs.microsoft.com/zh-tw/windows/msix/desktop/desktop-to-uwp-packaging-dot-net)：右上角可以切換語言。

但我不確定「打包」是不是也有人使用，只是我目前沒有查到相關的來源，這裡我覺得可以再討論一下。^^"

2021-10-01 13:08 UTC, StevenHsuYL commented on distributing/index.po
> +msgstr "`上傳專案至 Python 套件索引`_"
感謝！
因為在上面第84行那邊有加註原文，所以我想說之後可以不用再加，不過因為您的建議，我這邊會再加註一次。
另外，[PyPI](https://pypi.org/) 的全名已經改成 "Python Package Index" 而非 "Packaging"，所以這篇我遇到這個詞，都會翻成「Python 套件索引」。

2021-10-01 15:42 UTC, josix commented on distributing/index.po
> +msgstr "Python 封裝使用者指南包含了關於\\ `當今推薦工具`_\\ 的更多細節。"
Oh.. 教育部辭典這麼說的話那就先以教育部辭典為準好了，那沒問題了感謝補充～

2021-10-01 15:44 UTC, josix commented on distributing/index.po
> +msgstr "`上傳專案至 Python 套件索引`_"
感謝~ 考慮到可能有些讀者不會直接從一開始讀我想這邊也補上應該會比較好。

2021-10-01 15:45 UTC, josix approved these changes
Thanks @StevenHsuYL. LGTM!

2021-10-02 03:09 UTC, StevenHsuYL commented
Handling the name of PyPI now.
Please don't merge this PR until PR 28687 (https://github.com/python/cpython/pull/28687/files) in cpython was merged.

2021-10-02 17:15 UTC, StevenHsuYL commented
Done. It could be merged now. 😃

2021-10-08 05:47 UTC, merged